/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TS_STSFDG_SM
-- 생성일 : 2017-03-17 오후 1:32:14
-- 최종수정일 : 2017-03-17 오후 1:32:14
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TS_STSFDG_SM CASCADE CONSTRAINTS;

CREATE TABLE TS_STSFDG_SM (
  SM_NO          NUMBER(22)       NOT NULL,
  SM_DE          CHAR(8)          NOT NULL,
  SITE_ID        VARCHAR2(32)     NOT NULL,
  MENU_NO        NUMBER(10)       NOT NULL,
  PRTCPNT_CO     NUMBER(10)       NOT NULL,
  STSFDG_1_CO    NUMBER(10)      DEFAULT 0       NOT NULL,
  STSFDG_2_CO    NUMBER(10)      DEFAULT 0       NOT NULL,
  STSFDG_3_CO    NUMBER(10)      DEFAULT 0       NOT NULL,
  STSFDG_4_CO    NUMBER(10)      DEFAULT 0       NOT NULL,
  STSFDG_5_CO    NUMBER(10)      DEFAULT 0       NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TS_STSFDG_SM IS '만족도집계';

COMMENT ON COLUMN TS_STSFDG_SM.SM_NO IS '집계번호';

COMMENT ON COLUMN TS_STSFDG_SM.SM_DE IS '집계일자';

COMMENT ON COLUMN TS_STSFDG_SM.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TS_STSFDG_SM.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TS_STSFDG_SM.PRTCPNT_CO IS '총참여자수';

COMMENT ON COLUMN TS_STSFDG_SM.STSFDG_1_CO IS '만족도1개수';

COMMENT ON COLUMN TS_STSFDG_SM.STSFDG_2_CO IS '만족도2개수';

COMMENT ON COLUMN TS_STSFDG_SM.STSFDG_3_CO IS '만족도3개수';

COMMENT ON COLUMN TS_STSFDG_SM.STSFDG_4_CO IS '만족도4개수';

COMMENT ON COLUMN TS_STSFDG_SM.STSFDG_5_CO IS '만족도5개수';

ALTER TABLE TS_STSFDG_SM ADD
(
    CONSTRAINT PK_TS_STSFDG_SM
    PRIMARY KEY ( SM_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TS_SITE_CONECT_STATS_SM
-- 생성일 : 2017-03-16 오후 6:11:09
-- 최종수정일 : 2017-03-22 오후 2:42:38
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TS_SITE_CONECT_STATS_SM CASCADE CONSTRAINTS;

CREATE TABLE TS_SITE_CONECT_STATS_SM (
  SM_NO          NUMBER(22)        NOT NULL,
  SM_DE          CHAR(8),
  SM_SE          VARCHAR2(16),
  MENU_NO        NUMBER(10),
  SM_SE_VALUE    VARCHAR2(256),
  VISITR_CO      NUMBER(10),
  PGE_VIEW_CO    NUMBER(10),
  SITE_ID        VARCHAR2(32)      NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TS_SITE_CONECT_STATS_SM IS '사이트접속통계집계';

COMMENT ON COLUMN TS_SITE_CONECT_STATS_SM.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TS_SITE_CONECT_STATS_SM.SM_NO IS '관리번호';

COMMENT ON COLUMN TS_SITE_CONECT_STATS_SM.SM_DE IS '접속일자';

COMMENT ON COLUMN TS_SITE_CONECT_STATS_SM.SM_SE IS '집계구분';

COMMENT ON COLUMN TS_SITE_CONECT_STATS_SM.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TS_SITE_CONECT_STATS_SM.SM_SE_VALUE IS '집계구분값';

COMMENT ON COLUMN TS_SITE_CONECT_STATS_SM.VISITR_CO IS '방문자수';

COMMENT ON COLUMN TS_SITE_CONECT_STATS_SM.PGE_VIEW_CO IS '페이지뷰수';

ALTER TABLE TS_SITE_CONECT_STATS_SM ADD
(
    CONSTRAINT PK_TC_SITE_CONECT_STATS_SUMRY
    PRIMARY KEY ( SM_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TS_CMMN_FILE_DWLD_SM
-- 생성일 : 2017-03-17 오전 9:29:26
-- 최종수정일 : 2017-03-22 오후 2:41:22
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TS_CMMN_FILE_DWLD_SM CASCADE CONSTRAINTS;

CREATE TABLE TS_CMMN_FILE_DWLD_SM (
  SM_NO           NUMBER(22)       NOT NULL,
  SM_DE           CHAR(8),
  ATCH_FILE_ID    CHAR(20),
  FILE_SN         NUMBER(10),
  MENU_NO         NUMBER(10),
  DWLD_CO         NUMBER(10)      DEFAULT 0,
  SITE_ID         VARCHAR2(32)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TS_CMMN_FILE_DWLD_SM IS '공통파일다운로드집계';

COMMENT ON COLUMN TS_CMMN_FILE_DWLD_SM.SM_NO IS '집계번호';

COMMENT ON COLUMN TS_CMMN_FILE_DWLD_SM.SM_DE IS '집계일자';

COMMENT ON COLUMN TS_CMMN_FILE_DWLD_SM.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TS_CMMN_FILE_DWLD_SM.FILE_SN IS '파일일련번호';

COMMENT ON COLUMN TS_CMMN_FILE_DWLD_SM.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TS_CMMN_FILE_DWLD_SM.DWLD_CO IS '다운로드수';

COMMENT ON COLUMN TS_CMMN_FILE_DWLD_SM.SITE_ID IS '사이트ID';

ALTER TABLE TS_CMMN_FILE_DWLD_SM ADD
(
    CONSTRAINT PK_TC_CMMN_FILE_DWLD_SM
    PRIMARY KEY ( SM_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TM_USER_SECSN
-- 생성일 : 2017-01-05 오전 9:53:03
-- 최종수정일 : 2017-05-02 오후 2:07:25
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TM_USER_SECSN CASCADE CONSTRAINTS;

CREATE TABLE TM_USER_SECSN (
  MNNO               NUMBER(22)         NOT NULL,
  USER_ID            VARCHAR2(64),
  USER_NM            VARCHAR2(256),
  USER_SECSN_DT      DATE,
  USER_SECSN_MEMO    VARCHAR2(4000)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TM_USER_SECSN IS '사용자탈퇴';

COMMENT ON COLUMN TM_USER_SECSN.MNNO IS '관리번호';

COMMENT ON COLUMN TM_USER_SECSN.USER_ID IS '사용자ID';

COMMENT ON COLUMN TM_USER_SECSN.USER_NM IS '사용자명';

COMMENT ON COLUMN TM_USER_SECSN.USER_SECSN_DT IS '사용자탈퇴일시';

COMMENT ON COLUMN TM_USER_SECSN.USER_SECSN_MEMO IS '사용자탈퇴메모';

ALTER TABLE TM_USER_SECSN ADD
(
    CONSTRAINT PK_TM_USER_SECSN
    PRIMARY KEY ( MNNO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TM_USER_PIN
-- 생성일 : 2017-02-16 오후 5:55:23
-- 최종수정일 : 2017-02-17 오후 4:52:12
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TM_USER_PIN CASCADE CONSTRAINTS;

CREATE TABLE TM_USER_PIN (
  USER_SN          NUMBER(10)        NOT NULL,
  USER_PIN         VARCHAR2(128)    DEFAULT '0'     NOT NULL,
  USER_NM          VARCHAR2(256),
  CRTFC_SE_CD      CHAR(2),
  CHLD_CRTFC_AT    CHAR(1)          DEFAULT 'N'           NOT NULL,
  REGIST_DT        DATE              NOT NULL,
  UPDT_DT          DATE              NOT NULL,
  BRTHDY           VARCHAR2(32),
  SEX_CD           CHAR(1)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TM_USER_PIN IS '사용자개인식별번호';

COMMENT ON COLUMN TM_USER_PIN.USER_SN IS '사용자일련번호';

COMMENT ON COLUMN TM_USER_PIN.USER_PIN IS '사죵자개인식별번호';

COMMENT ON COLUMN TM_USER_PIN.BRTHDY IS '생년월일';

COMMENT ON COLUMN TM_USER_PIN.USER_NM IS '사용자명';

COMMENT ON COLUMN TM_USER_PIN.CRTFC_SE_CD IS '인증구분코드';

COMMENT ON COLUMN TM_USER_PIN.CHLD_CRTFC_AT IS '미성년자인증여부(14세미만)';

COMMENT ON COLUMN TM_USER_PIN.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TM_USER_PIN.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TM_USER_PIN.SEX_CD IS '성별코드';

ALTER TABLE TM_USER_PIN ADD
(
    CONSTRAINT PK_TM_USER_PIN
    PRIMARY KEY ( USER_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TM_USER_PIN ADD
(
    CONSTRAINT UQ_TM_USER_PIN
    UNIQUE ( USER_PIN, CHLD_CRTFC_AT, BRTHDY )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TM_USER_INFO_PRTC
-- 생성일 : 2017-02-06 오전 11:09:21
-- 최종수정일 : 2017-02-06 오후 5:17:14
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TM_USER_INFO_PRTC CASCADE CONSTRAINTS;

CREATE TABLE TM_USER_INFO_PRTC (
  MNNO               NUMBER(22)        NOT NULL,
  PAGE_NO            NUMBER(10),
  USER_ID            VARCHAR2(64),
  READNG_USER_ID     VARCHAR2(64),
  READNG_DT          DATE,
  READNG_IPAD        VARCHAR2(128),
  READNG_URLAD       VARCHAR2(512),
  READNG_PURPS_SE    CLOB             DEFAULT '홈페이지관리'
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TM_USER_INFO_PRTC IS '사용자정보보호';

COMMENT ON COLUMN TM_USER_INFO_PRTC.MNNO IS '관리번호';

COMMENT ON COLUMN TM_USER_INFO_PRTC.PAGE_NO IS '페이지번호';

COMMENT ON COLUMN TM_USER_INFO_PRTC.USER_ID IS '사용자ID';

COMMENT ON COLUMN TM_USER_INFO_PRTC.READNG_USER_ID IS '열람사용자ID';

COMMENT ON COLUMN TM_USER_INFO_PRTC.READNG_DT IS '열람일시';

COMMENT ON COLUMN TM_USER_INFO_PRTC.READNG_IPAD IS '열람IP주소';

COMMENT ON COLUMN TM_USER_INFO_PRTC.READNG_URLAD IS '열람URL주소';

COMMENT ON COLUMN TM_USER_INFO_PRTC.READNG_PURPS_SE IS '열람목적구분';

ALTER TABLE TM_USER_INFO_PRTC ADD
(
    CONSTRAINT PK_TM_USER_INFO_PRTC
    PRIMARY KEY ( MNNO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TM_USER_INFO
-- 생성일 : 2017-05-02 오전 10:45:36
-- 최종수정일 : 2017-05-02 오전 10:45:40
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TM_USER_INFO CASCADE CONSTRAINTS;

CREATE TABLE TM_USER_INFO (
  USER_ID               VARCHAR2(64)      NOT NULL,
  USER_SN               NUMBER(10)        NOT NULL,
  PASSWORD              VARCHAR2(256)     NOT NULL,
  USER_TY_CD            VARCHAR2(16),
  USER_NM               VARCHAR2(256),
  USER_EMAD             VARCHAR2(512),
  USER_CPNO             VARCHAR2(32),
  USER_TELNO            VARCHAR2(32),
  USER_ZIP              VARCHAR2(7),
  USER_ADRES1           VARCHAR2(256),
  USER_ADRES2           VARCHAR2(512),
  EMAIL_RECPTN_AT       CHAR(1),
  SMS_RECPTN_AT         CHAR(1),
  ENTRPRS_NO            NUMBER(10),
  STTUS_CD              VARCHAR2(16)     DEFAULT 'Y',
  AUTHOR_CD             VARCHAR2(32)      NOT NULL,
  MNG_AT                CHAR(1)          DEFAULT 'N',
  ENT_AT                CHAR(1)          DEFAULT 'N',
  SEAT_NO               NUMBER(10),
  ATCH_FILE_ID          CHAR(20),
  SITE_ID               VARCHAR2(32)      NOT NULL,
  DEPT_ID               VARCHAR2(16),
  LAST_LOGIN_DT         DATE,
  PASSWORD_CHANGE_DT    DATE             DEFAULT SYSDATE,
  STPLAT_AGRE_DT        DATE             DEFAULT SYSDATE,
  DELETE_CD             CHAR(1)          DEFAULT '0'           NOT NULL,
  USE_AT                CHAR(1),
  REGIST_ID             VARCHAR2(64)      NOT NULL,
  REGIST_DT             DATE             DEFAULT SYSDATE              NOT NULL,
  UPDT_ID               VARCHAR2(64),
  UPDT_DT               DATE             DEFAULT SYSDATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TM_USER_INFO IS '사용자정보';

COMMENT ON COLUMN TM_USER_INFO.USER_ID IS '사용자ID';

COMMENT ON COLUMN TM_USER_INFO.USER_SN IS '사용자일련번호';

COMMENT ON COLUMN TM_USER_INFO.PASSWORD IS '비밀번호';

COMMENT ON COLUMN TM_USER_INFO.USER_TY_CD IS '사용자타입코드';

COMMENT ON COLUMN TM_USER_INFO.USER_NM IS '사용자명';

COMMENT ON COLUMN TM_USER_INFO.USER_EMAD IS '사용자이메일주소';

COMMENT ON COLUMN TM_USER_INFO.USER_CPNO IS '사용자휴대전화번호';

COMMENT ON COLUMN TM_USER_INFO.USER_TELNO IS '사용자전화번호';

COMMENT ON COLUMN TM_USER_INFO.USER_ZIP IS '사용자우편번호';

COMMENT ON COLUMN TM_USER_INFO.USER_ADRES1 IS '사용자주소1';

COMMENT ON COLUMN TM_USER_INFO.USER_ADRES2 IS '사용자주소2';

COMMENT ON COLUMN TM_USER_INFO.EMAIL_RECPTN_AT IS '이메일수신여부';

COMMENT ON COLUMN TM_USER_INFO.SMS_RECPTN_AT IS 'SMS수신여부';

COMMENT ON COLUMN TM_USER_INFO.ENTRPRS_NO IS '기업체번호';

COMMENT ON COLUMN TM_USER_INFO.STTUS_CD IS '상태코드';

COMMENT ON COLUMN TM_USER_INFO.AUTHOR_CD IS '권한코드';

COMMENT ON COLUMN TM_USER_INFO.MNG_AT IS '관리자여부';

COMMENT ON COLUMN TM_USER_INFO.ENT_AT IS '승인여부';

COMMENT ON COLUMN TM_USER_INFO.SEAT_NO IS '좌석번호';

COMMENT ON COLUMN TM_USER_INFO.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TM_USER_INFO.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TM_USER_INFO.DEPT_ID IS '부서ID';

COMMENT ON COLUMN TM_USER_INFO.LAST_LOGIN_DT IS '마지막로그인일시';

COMMENT ON COLUMN TM_USER_INFO.PASSWORD_CHANGE_DT IS '비밀번호변경일시';

COMMENT ON COLUMN TM_USER_INFO.STPLAT_AGRE_DT IS '약관동의일시';

COMMENT ON COLUMN TM_USER_INFO.DELETE_CD IS '삭제코드';

COMMENT ON COLUMN TM_USER_INFO.USE_AT IS '사용여부';

COMMENT ON COLUMN TM_USER_INFO.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TM_USER_INFO.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TM_USER_INFO.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TM_USER_INFO.UPDT_DT IS '수정일시';

ALTER TABLE TM_USER_INFO ADD
(
    CONSTRAINT PK_TM_USER_INFO
    PRIMARY KEY ( USER_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TM_MNGR_INFO
-- 생성일 : 2017-01-09 오후 4:28:02
-- 최종수정일 : 2017-03-29 오후 11:36:49
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TM_MNGR_INFO CASCADE CONSTRAINTS;

CREATE TABLE TM_MNGR_INFO (
  USER_ID      VARCHAR2(64)      NOT NULL,
  USER_SN      NUMBER(10)        NOT NULL,
  USER_NM      VARCHAR2(256),
  PASSWORD     VARCHAR2(256)     NOT NULL,
  SEAT_NO      NUMBER(10),
  AUTHOR_CD    VARCHAR2(32)      NOT NULL,
  USER_CPNO    VARCHAR2(32),
  USER_IPAD    VARCHAR2(64),
  USER_EMAD    VARCHAR2(512),
  STTUS_CD     VARCHAR2(16),
  DELETE_CD    CHAR(1)          DEFAULT 0           NOT NULL,
  USE_AT       CHAR(1),
  REGIST_ID    VARCHAR2(64)      NOT NULL,
  REGIST_DT    DATE             DEFAULT SYSDATE              NOT NULL,
  UPDT_ID      VARCHAR2(64),
  UPDT_DT      DATE             DEFAULT SYSDATE,
  DEPT_ID      VARCHAR2(16)      NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TM_MNGR_INFO IS '관리자정보';

COMMENT ON COLUMN TM_MNGR_INFO.USER_ID IS '사용자ID';

COMMENT ON COLUMN TM_MNGR_INFO.USER_SN IS '사용자일련번호';

COMMENT ON COLUMN TM_MNGR_INFO.USER_NM IS '사용자명';

COMMENT ON COLUMN TM_MNGR_INFO.PASSWORD IS '비밀번호';

COMMENT ON COLUMN TM_MNGR_INFO.SEAT_NO IS '좌석번호';

COMMENT ON COLUMN TM_MNGR_INFO.AUTHOR_CD IS '권한코드';

COMMENT ON COLUMN TM_MNGR_INFO.USER_CPNO IS '사용자휴대전화번호';

COMMENT ON COLUMN TM_MNGR_INFO.USER_IPAD IS '사용자IP주소';

COMMENT ON COLUMN TM_MNGR_INFO.USER_EMAD IS '사용자이메일주소';

COMMENT ON COLUMN TM_MNGR_INFO.STTUS_CD IS '상태코드';

COMMENT ON COLUMN TM_MNGR_INFO.DELETE_CD IS '삭제코드';

COMMENT ON COLUMN TM_MNGR_INFO.USE_AT IS '사용여부';

COMMENT ON COLUMN TM_MNGR_INFO.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TM_MNGR_INFO.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TM_MNGR_INFO.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TM_MNGR_INFO.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TM_MNGR_INFO.DEPT_ID IS '부서ID';

ALTER TABLE TM_MNGR_INFO ADD
(
    CONSTRAINT PK_TM_MNGR_INFO
    PRIMARY KEY ( USER_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TM_MNGR_INFO ADD
(
    CONSTRAINT FK_TM_DEPT_INFO
    FOREIGN KEY ( DEPT_ID )
        REFERENCES UCMS22.TM_DEPT_INFO ( DEPT_ID )
);

ALTER TABLE TM_MNGR_INFO ADD
(
    CONSTRAINT FK_TC_AUTHOR_INFO_MNGR_INFO
    FOREIGN KEY ( AUTHOR_CD )
        REFERENCES UCMS22.TC_AUTHOR_INFO ( AUTHOR_CD )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TM_LOGIN_HIST
-- 생성일 : 2017-02-17 오후 2:14:55
-- 최종수정일 : 2017-02-17 오후 2:18:36
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TM_LOGIN_HIST CASCADE CONSTRAINTS;

CREATE TABLE TM_LOGIN_HIST (
  HIST_NO      NUMBER(10)       NOT NULL,
  SITE_ID      VARCHAR2(32)    DEFAULT 'bos'     NOT NULL,
  USER_ID      VARCHAR2(64)     NOT NULL,
  USER_IPAD    VARCHAR2(64),
  STTUS_CD     VARCHAR2(16),
  LOGIN_DT     DATE             NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TM_LOGIN_HIST IS '로그인이력';

COMMENT ON COLUMN TM_LOGIN_HIST.HIST_NO IS '이력번호';

COMMENT ON COLUMN TM_LOGIN_HIST.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TM_LOGIN_HIST.USER_ID IS '사용자ID';

COMMENT ON COLUMN TM_LOGIN_HIST.USER_IPAD IS '사용자IP주소';

COMMENT ON COLUMN TM_LOGIN_HIST.STTUS_CD IS '상태코드';

COMMENT ON COLUMN TM_LOGIN_HIST.LOGIN_DT IS '로그인일시';

ALTER TABLE TM_LOGIN_HIST ADD
(
    CONSTRAINT PK_TM_LOGIN_HIST
    PRIMARY KEY ( HIST_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TM_DEPT_INFO
-- 생성일 : 2017-02-09 오후 5:42:03
-- 최종수정일 : 2017-03-16 오후 2:28:11
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TM_DEPT_INFO CASCADE CONSTRAINTS;

CREATE TABLE TM_DEPT_INFO (
  DEPT_ID          VARCHAR2(16)      NOT NULL,
  DEPT_CD          VARCHAR2(32),
  DEPT_KOR_NM      VARCHAR2(512)     NOT NULL,
  DEPT_ENG_NM      VARCHAR2(512),
  UPPER_DEPT_ID    VARCHAR2(16),
  DEPT_LEVEL       NUMBER(10),
  SORT_ORDR        NUMBER(10)        NOT NULL,
  DEPT_JOB_CN      CLOB,
  DEPT_INFO        CLOB,
  DEPT_TELNO       VARCHAR2(128),
  DEPT_FAXNO       VARCHAR2(128),
  DELETE_CD        CHAR(1)          DEFAULT 0           NOT NULL,
  USE_AT           CHAR(1)          DEFAULT 'Y',
  REGIST_ID        VARCHAR2(64)      NOT NULL,
  REGIST_DT        DATE             DEFAULT SYSDATE              NOT NULL,
  UPDT_ID          VARCHAR2(64),
  UPDT_DT          DATE             DEFAULT SYSDATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TM_DEPT_INFO IS '부서정보';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_ID IS '부서ID';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_CD IS '부서코드';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_KOR_NM IS '부서한글명';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_ENG_NM IS '부서영문명';

COMMENT ON COLUMN TM_DEPT_INFO.UPPER_DEPT_ID IS '상위부서코드';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_LEVEL IS '부서레벨';

COMMENT ON COLUMN TM_DEPT_INFO.SORT_ORDR IS '정렬순서';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_JOB_CN IS '부서업무내용';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_INFO IS '부서정보';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_TELNO IS '부서전화번호';

COMMENT ON COLUMN TM_DEPT_INFO.DEPT_FAXNO IS '부서팩스번호';

COMMENT ON COLUMN TM_DEPT_INFO.DELETE_CD IS '삭제코드';

COMMENT ON COLUMN TM_DEPT_INFO.USE_AT IS '사용여부';

COMMENT ON COLUMN TM_DEPT_INFO.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TM_DEPT_INFO.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TM_DEPT_INFO.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TM_DEPT_INFO.UPDT_DT IS '수정일시';

ALTER TABLE TM_DEPT_INFO ADD
(
    CONSTRAINT PK_TM_DEPT_INFO
    PRIMARY KEY ( DEPT_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_WORD_DICARY
-- 생성일 : 2017-01-06 오후 3:34:22
-- 최종수정일 : 2017-02-20 오전 10:43:12
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_WORD_DICARY CASCADE CONSTRAINTS;

CREATE TABLE TC_WORD_DICARY (
  MNNO                NUMBER(10)         NOT NULL,
  WORD_SE             VARCHAR2(64),
  WORD_NM             VARCHAR2(256),
  WORD_ENG_NM         VARCHAR2(1024),
  WORD_ENG_ABRV_NM    VARCHAR2(1024),
  WORD_DFN            VARCHAR2(4000),
  THEMA_AREA_SE       VARCHAR2(1024),
  CREAT_DE            VARCHAR2(10),
  USE_AT              CHAR(1)           DEFAULT 'Y'            NOT NULL,
  REGIST_ID           VARCHAR2(64),
  REGIST_DT           DATE              DEFAULT SYSDATE,
  UPDT_ID             VARCHAR2(64),
  UPDT_DT             DATE              DEFAULT SYSDATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_WORD_DICARY IS '용어사전';

COMMENT ON COLUMN TC_WORD_DICARY.MNNO IS '관리번호';

COMMENT ON COLUMN TC_WORD_DICARY.WORD_SE IS '용어구분';

COMMENT ON COLUMN TC_WORD_DICARY.WORD_NM IS '용어명';

COMMENT ON COLUMN TC_WORD_DICARY.WORD_ENG_NM IS '용어영문명';

COMMENT ON COLUMN TC_WORD_DICARY.WORD_ENG_ABRV_NM IS '용어영문약어명';

COMMENT ON COLUMN TC_WORD_DICARY.WORD_DFN IS '용어정의';

COMMENT ON COLUMN TC_WORD_DICARY.THEMA_AREA_SE IS '주제영역구분';

COMMENT ON COLUMN TC_WORD_DICARY.CREAT_DE IS '생성일자';

COMMENT ON COLUMN TC_WORD_DICARY.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_WORD_DICARY.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_WORD_DICARY.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_WORD_DICARY.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_WORD_DICARY.UPDT_DT IS '수정일시';

/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.I_TC_WORD_DICARY_01
-- 생성일 : 2017-02-20 오전 10:43:12
-- 최종수정일 : 2017-02-20 오전 10:43:12
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP INDEX I_TC_WORD_DICARY_01;

CREATE INDEX I_TC_WORD_DICARY_01
ON TC_WORD_DICARY (WORD_SE, WORD_ENG_ABRV_NM)
TABLESPACE TSDT_UCMS22
LOGGING
NOPARALLEL;

ALTER TABLE TC_WORD_DICARY ADD
(
    CONSTRAINT PK_TC_WORD_DICARY
    PRIMARY KEY ( MNNO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_USER_MAIN_CNTNTS
-- 생성일 : 2017-03-20 오후 4:33:35
-- 최종수정일 : 2017-05-02 오전 10:28:10
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_USER_MAIN_CNTNTS CASCADE CONSTRAINTS;

CREATE TABLE TC_USER_MAIN_CNTNTS (
  RELM_SE_CD        VARCHAR2(2)       NOT NULL,
  MAIN_CNTNTS_CD    VARCHAR2(16),
  BBS_ID            VARCHAR2(16),
  MENU_LINK         VARCHAR2(512),
  ATCH_FILE_ID      CHAR(20),
  REGIST_DT         DATE,
  REGIST_ID         VARCHAR2(64),
  UPDT_DT           DATE,
  UPDT_ID           VARCHAR2(64),
  POPUP_AT          CHAR(1),
  MENU_NO           NUMBER,
  USE_AT            CHAR(1)          DEFAULT 'Y'
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_USER_MAIN_CNTNTS IS '사용자메인콘텐츠관리';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.POPUP_AT IS '팝업여부';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.RELM_SE_CD IS '영역구분코드';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.MAIN_CNTNTS_CD IS '메인콘텐츠코드';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.BBS_ID IS '게시판ID';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.MENU_LINK IS '메뉴링크';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_USER_MAIN_CNTNTS.MENU_NO IS '메뉴번호';

ALTER TABLE TC_USER_MAIN_CNTNTS ADD
(
    PRIMARY KEY ( RELM_SE_CD )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_USER_AUTHOR
-- 생성일 : 2017-01-05 오전 9:53:12
-- 최종수정일 : 2017-02-03 오후 4:31:49
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_USER_AUTHOR CASCADE CONSTRAINTS;

CREATE TABLE TC_USER_AUTHOR (
  USER_ID       VARCHAR2(64)     NOT NULL,
  USER_TY_CD    VARCHAR2(16)     NOT NULL,
  AUTHOR_CD     VARCHAR2(32)     NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_USER_AUTHOR IS '사용자별권한';

COMMENT ON COLUMN TC_USER_AUTHOR.USER_ID IS '사용자ID';

COMMENT ON COLUMN TC_USER_AUTHOR.USER_TY_CD IS '사용자구분코드';

COMMENT ON COLUMN TC_USER_AUTHOR.AUTHOR_CD IS '권한코드';

ALTER TABLE TC_USER_AUTHOR ADD
(
    CONSTRAINT PK_TC_USER_AUTHOR
    PRIMARY KEY ( USER_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TC_USER_AUTHOR ADD
(
    CONSTRAINT FK_TC_USER_AUTHOR_AUTHOR_INFO
    FOREIGN KEY ( AUTHOR_CD )
        REFERENCES UCMS22.TC_AUTHOR_INFO ( AUTHOR_CD )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_TMPLAT_INFO
-- 생성일 : 2017-01-06 오전 11:49:55
-- 최종수정일 : 2017-02-03 오후 4:31:53
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_TMPLAT_INFO CASCADE CONSTRAINTS;

CREATE TABLE TC_TMPLAT_INFO (
  TMPLAT_ID       CHAR(20)          NOT NULL,
  TMPLAT_NM       VARCHAR2(256),
  TMPLAT_SE_CD    CHAR(16),
  TMPLAT_COURS    VARCHAR2(512),
  USE_AT          CHAR(1)          DEFAULT 'Y'           NOT NULL,
  REGIST_ID       VARCHAR2(64)      NOT NULL,
  REGIST_DT       DATE              NOT NULL,
  UPDT_ID         VARCHAR2(64),
  UPDT_DT         DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_TMPLAT_INFO IS '템플릿정보';

COMMENT ON COLUMN TC_TMPLAT_INFO.TMPLAT_ID IS '템플릿ID';

COMMENT ON COLUMN TC_TMPLAT_INFO.TMPLAT_NM IS '템플릿명';

COMMENT ON COLUMN TC_TMPLAT_INFO.TMPLAT_SE_CD IS '템플릿구분코드';

COMMENT ON COLUMN TC_TMPLAT_INFO.TMPLAT_COURS IS '템플릿경로';

COMMENT ON COLUMN TC_TMPLAT_INFO.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_TMPLAT_INFO.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_TMPLAT_INFO.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_TMPLAT_INFO.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_TMPLAT_INFO.UPDT_DT IS '수정일시';

ALTER TABLE TC_TMPLAT_INFO ADD
(
    CONSTRAINT PK_TC_TMPLAT_INFO
    PRIMARY KEY ( TMPLAT_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_STSFDG
-- 생성일 : 2017-02-15 오전 10:45:18
-- 최종수정일 : 2017-03-16 오후 2:35:14
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_STSFDG CASCADE CONSTRAINTS;

CREATE TABLE TC_STSFDG (
  STSFDG_NO      NUMBER(10)         NOT NULL,
  SITE_ID        VARCHAR2(32)       NOT NULL,
  MENU_NO        NUMBER(10)         NOT NULL,
  STSFDG_IDEX    NUMBER(10)         NOT NULL,
  OPINION_CN     VARCHAR2(4000),
  USER_ID        VARCHAR2(64),
  USER_IPAD      VARCHAR2(64)       NOT NULL,
  REGIST_DT      DATE               NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_STSFDG IS '만족도';

COMMENT ON COLUMN TC_STSFDG.STSFDG_NO IS '만족도번호';

COMMENT ON COLUMN TC_STSFDG.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_STSFDG.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TC_STSFDG.STSFDG_IDEX IS '만족도지수';

COMMENT ON COLUMN TC_STSFDG.OPINION_CN IS '의견내용';

COMMENT ON COLUMN TC_STSFDG.USER_ID IS '사용자ID';

COMMENT ON COLUMN TC_STSFDG.USER_IPAD IS '사용자IP주소';

COMMENT ON COLUMN TC_STSFDG.REGIST_DT IS '등록일시';

ALTER TABLE TC_STSFDG ADD
(
    CONSTRAINT PK_TC_STSFDG
    PRIMARY KEY ( STSFDG_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_SITE_INFO
-- 생성일 : 2017-03-22 오전 9:06:12
-- 최종수정일 : 2017-03-22 오전 9:06:16
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_SITE_INFO CASCADE CONSTRAINTS;

CREATE TABLE TC_SITE_INFO (
  SITE_ID             VARCHAR2(32)       NOT NULL,
  SITE_NM             VARCHAR2(256)      NOT NULL,
  SITE_DC             VARCHAR2(4000),
  SITE_URLAD          VARCHAR2(512),
  SITE_IPAD           VARCHAR2(64),
  SITE_PORT_NO        VARCHAR2(32),
  SITE_ESTBS_CD       VARCHAR2(16),
  STSFDG_USE_AT       CHAR(1)           DEFAULT 'N',
  DTA_MNGR_USE_AT     CHAR(1)           DEFAULT 'N',
  ATCH_FILE_ID        CHAR(20),
  ACCES_IPAD          VARCHAR2(2048),
  SITE_SN             NUMBER(10),
  INSTT_NM            VARCHAR2(256),
  INSTT_NM_USE_AT     CHAR(1),
  CPYRHT_CN           VARCHAR2(4000),
  CPYRHT_CN_USE_AT    CHAR(1),
  ZIP                 VARCHAR2(7),
  ZIP_USE_AT          CHAR(1),
  ADRES1              VARCHAR2(256),
  ADRES1_USE_AT       CHAR(1),
  ADRES2              VARCHAR2(512),
  ADRES2_USE_AT       CHAR(1),
  TELNO               VARCHAR2(32),
  TELNO_USE_AT        CHAR(1),
  FAXNO               VARCHAR2(32),
  FAXNO_USE_AT        CHAR(1),
  USE_AT              CHAR(1)           DEFAULT 'Y'            NOT NULL,
  REGIST_ID           VARCHAR2(64)       NOT NULL,
  REGIST_DT           DATE               NOT NULL,
  UPDT_ID             VARCHAR2(64),
  UPDT_DT             DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_SITE_INFO IS '사이트정보';

COMMENT ON COLUMN TC_SITE_INFO.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_SITE_INFO.SITE_NM IS '사이트명';

COMMENT ON COLUMN TC_SITE_INFO.SITE_DC IS '사이트설명';

COMMENT ON COLUMN TC_SITE_INFO.SITE_URLAD IS '사이트URL주소';

COMMENT ON COLUMN TC_SITE_INFO.SITE_IPAD IS '사이트IP주소';

COMMENT ON COLUMN TC_SITE_INFO.SITE_PORT_NO IS '사이트포트번호';

COMMENT ON COLUMN TC_SITE_INFO.SITE_ESTBS_CD IS '사이트설정코드';

COMMENT ON COLUMN TC_SITE_INFO.STSFDG_USE_AT IS '만족도사용여부';

COMMENT ON COLUMN TC_SITE_INFO.DTA_MNGR_USE_AT IS '자료관리자사용여부';

COMMENT ON COLUMN TC_SITE_INFO.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_SITE_INFO.ACCES_IPAD IS '접근아이피주소';

COMMENT ON COLUMN TC_SITE_INFO.SITE_SN IS '사이트일련번호';

COMMENT ON COLUMN TC_SITE_INFO.INSTT_NM IS '기관명';

COMMENT ON COLUMN TC_SITE_INFO.INSTT_NM_USE_AT IS '기관명사용여부';

COMMENT ON COLUMN TC_SITE_INFO.CPYRHT_CN IS '저작권내용';

COMMENT ON COLUMN TC_SITE_INFO.CPYRHT_CN_USE_AT IS '저작권내용사용여부';

COMMENT ON COLUMN TC_SITE_INFO.ZIP IS '우편번호';

COMMENT ON COLUMN TC_SITE_INFO.ZIP_USE_AT IS '우편번호사용여부';

COMMENT ON COLUMN TC_SITE_INFO.ADRES1 IS '주소1';

COMMENT ON COLUMN TC_SITE_INFO.ADRES1_USE_AT IS '주소1사용여부';

COMMENT ON COLUMN TC_SITE_INFO.ADRES2 IS '주소2';

COMMENT ON COLUMN TC_SITE_INFO.ADRES2_USE_AT IS '주소2사용여부';

COMMENT ON COLUMN TC_SITE_INFO.TELNO IS '전화번호';

COMMENT ON COLUMN TC_SITE_INFO.TELNO_USE_AT IS '전화번호사용여부';

COMMENT ON COLUMN TC_SITE_INFO.FAXNO IS '팩스번호';

COMMENT ON COLUMN TC_SITE_INFO.FAXNO_USE_AT IS '팩스번호사용여부';

COMMENT ON COLUMN TC_SITE_INFO.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_SITE_INFO.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_SITE_INFO.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_SITE_INFO.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_SITE_INFO.UPDT_DT IS '수정일시';

ALTER TABLE TC_SITE_INFO ADD
(
    UNIQUE ( SITE_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_SITE_HPCM_MENU
-- 생성일 : 2017-05-16 오전 10:56:14
-- 최종수정일 : 2017-05-16 오전 10:58:49
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_SITE_HPCM_MENU CASCADE CONSTRAINTS;

CREATE TABLE TC_SITE_HPCM_MENU (
  HPCM_NO    NUMBER(11)     NOT NULL,
  MENU_NO    NUMBER(10)     NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_SITE_HPCM_MENU IS '사이트도움말메뉴';

COMMENT ON COLUMN TC_SITE_HPCM_MENU.HPCM_NO IS '도움말번호';

COMMENT ON COLUMN TC_SITE_HPCM_MENU.MENU_NO IS '메뉴번호';

ALTER TABLE TC_SITE_HPCM_MENU ADD
(
    PRIMARY KEY ( HPCM_NO, MENU_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_SITE_HPCM
-- 생성일 : 2017-03-24 오후 1:22:41
-- 최종수정일 : 2017-03-24 오후 4:03:54
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_SITE_HPCM CASCADE CONSTRAINTS;

CREATE TABLE TC_SITE_HPCM (
  HPCM_NO          NUMBER(11)         NOT NULL,
  HPCM_NM          VARCHAR2(256)      NOT NULL,
  UPPER_HPCM_NO    NUMBER(11)         NOT NULL,
  GROUP_ID         VARCHAR2(256),
  SRVC_ID          VARCHAR2(256),
  SRVC_NM          VARCHAR2(256),
  METHOD_ID        VARCHAR2(256),
  HPCM_ORDR        NUMBER(11),
  HPCM_CN          CLOB,
  KWRD_NM          VARCHAR2(1024),
  ADI_INFO         CLOB,
  USE_AT           CHAR(1)           DEFAULT 'Y'            NOT NULL,
  REGIST_ID        VARCHAR2(64)       NOT NULL,
  REGIST_DT        DATE               NOT NULL,
  UPDT_ID          VARCHAR2(64),
  UPDT_DT          DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_SITE_HPCM IS '사이트도움말';

COMMENT ON COLUMN TC_SITE_HPCM.HPCM_NO IS '도움말번호';

COMMENT ON COLUMN TC_SITE_HPCM.HPCM_NM IS '도움말명';

COMMENT ON COLUMN TC_SITE_HPCM.UPPER_HPCM_NO IS '상위도움말번호';

COMMENT ON COLUMN TC_SITE_HPCM.GROUP_ID IS '그룹ID';

COMMENT ON COLUMN TC_SITE_HPCM.SRVC_ID IS '서비스ID';

COMMENT ON COLUMN TC_SITE_HPCM.SRVC_NM IS '서비스명';

COMMENT ON COLUMN TC_SITE_HPCM.METHOD_ID IS '메소드ID';

COMMENT ON COLUMN TC_SITE_HPCM.HPCM_ORDR IS '도움말순서';

COMMENT ON COLUMN TC_SITE_HPCM.HPCM_CN IS '도움말내용';

COMMENT ON COLUMN TC_SITE_HPCM.KWRD_NM IS '키워드명';

COMMENT ON COLUMN TC_SITE_HPCM.ADI_INFO IS '추가정보';

COMMENT ON COLUMN TC_SITE_HPCM.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_SITE_HPCM.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_SITE_HPCM.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_SITE_HPCM.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_SITE_HPCM.UPDT_DT IS '수정일시';

ALTER TABLE TC_SITE_HPCM ADD
(
    CONSTRAINT PK_TC_SIITE_HPCM
    PRIMARY KEY ( HPCM_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_SITE_GUIDE_MENU
-- 생성일 : 2017-03-06 오후 1:05:33
-- 최종수정일 : 2017-03-06 오후 1:05:33
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_SITE_GUIDE_MENU CASCADE CONSTRAINTS;

CREATE TABLE TC_SITE_GUIDE_MENU (
  MNNO          NUMBER(22)        NOT NULL,
  SITE_ID       VARCHAR2(32)      NOT NULL,
  MENU_SE_CD    VARCHAR2(16)      NOT NULL,
  MENU_NO       NUMBER(10),
  MENU_NM       VARCHAR2(256)     NOT NULL,
  MENU_LINK     VARCHAR2(512),
  MENU_ORDR     NUMBER(10)        NOT NULL,
  POPUP_AT      CHAR(1)           NOT NULL,
  USE_AT        CHAR(1)          DEFAULT 'Y'           NOT NULL,
  REGIST_ID     VARCHAR2(64)      NOT NULL,
  REGIST_DT     DATE              NOT NULL,
  UPDT_ID       VARCHAR2(64),
  UPDT_DT       DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_SITE_GUIDE_MENU IS '사이트가이드메뉴';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.MNNO IS '관리번호';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.MENU_SE_CD IS '메뉴구분코드';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.MENU_NM IS '메뉴명';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.MENU_LINK IS '메뉴링크';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.MENU_ORDR IS '메뉴순서';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.POPUP_AT IS '팝업여부';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_SITE_GUIDE_MENU.UPDT_DT IS '수정일시';

ALTER TABLE TC_SITE_GUIDE_MENU ADD
(
    CONSTRAINT PK_TC_SITE_GUIDE_MENU
    PRIMARY KEY ( MNNO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_SITE_CONECT_STATS
-- 생성일 : 2017-03-16 오후 5:18:28
-- 최종수정일 : 2017-03-16 오후 5:18:32
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_SITE_CONECT_STATS CASCADE CONSTRAINTS;

CREATE TABLE TC_SITE_CONECT_STATS (
  CONECT_SN              NUMBER(22)        NOT NULL,
  SESION_ID              VARCHAR2(256)     NOT NULL,
  SITE_ID                VARCHAR2(32)      NOT NULL,
  CONECT_URLAD           VARCHAR2(512),
  MENU_NO                NUMBER(10),
  CONECT_OPERSYSM_NM     VARCHAR2(256),
  CONECT_WBSR_NM         VARCHAR2(256),
  CONECT_PC_MOBILE_SE    VARCHAR2(64),
  CONECT_YM              CHAR(6)           NOT NULL,
  CONECT_DE              CHAR(8)           NOT NULL,
  REGIST_DT              DATE              NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_SITE_CONECT_STATS IS '사이트접속통계';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.CONECT_SN IS '접속일련번호';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.SESION_ID IS '세션ID';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.CONECT_URLAD IS '접속URL주소';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.CONECT_OPERSYSM_NM IS '접속운영체제명';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.CONECT_WBSR_NM IS '접속브라우저명';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.CONECT_PC_MOBILE_SE IS '접속PC모바일구분';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.CONECT_YM IS '접속년월';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.CONECT_DE IS '접속일자';

COMMENT ON COLUMN TC_SITE_CONECT_STATS.REGIST_DT IS '등록일시';

/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.I_TC_SITE_CONECT_STATS_01
-- 생성일 : 2017-03-16 오후 5:18:32
-- 최종수정일 : 2017-03-16 오후 5:18:32
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP INDEX I_TC_SITE_CONECT_STATS_01;

CREATE INDEX I_TC_SITE_CONECT_STATS_01
ON TC_SITE_CONECT_STATS (SITE_ID, CONECT_DE, SESION_ID)
TABLESPACE TSDT_UCMS22
LOGGING
NOPARALLEL;

ALTER TABLE TC_SITE_CONECT_STATS ADD
(
    CONSTRAINT PK_TC_SITE_CONECT_STATS
    PRIMARY KEY ( CONECT_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_QUSTNR_USER_ANSWER
-- 생성일 : 2017-02-14 오전 10:43:30
-- 최종수정일 : 2017-02-17 오후 2:32:35
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_QUSTNR_USER_ANSWER CASCADE CONSTRAINTS;

CREATE TABLE TC_QUSTNR_USER_ANSWER (
  USER_ANSWER_SN    NUMBER(10)         NOT NULL,
  QESITM_SN         NUMBER(10)         NOT NULL,
  ANSWER_SN         NUMBER(10),
  USER_SN           NUMBER(10),
  USER_ID           VARCHAR2(64),
  ANSWER_CN         VARCHAR2(4000)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_QUSTNR_USER_ANSWER IS '설문사용자답변';

COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.USER_ANSWER_SN IS '사용자답변일련번호';

COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.QESITM_SN IS '문항일련번호';

COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.ANSWER_SN IS '답변일련번호';

COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.USER_SN IS '사용자일련번호';

COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.USER_ID IS '사용자ID';

COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.ANSWER_CN IS '답변내용';

ALTER TABLE TC_QUSTNR_USER_ANSWER ADD
(
    CONSTRAINT PK_TC_QUSTNR_USER_ANSWER
    PRIMARY KEY ( USER_ANSWER_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_QUSTNR_QESITM
-- 생성일 : 2017-02-10 오후 2:37:14
-- 최종수정일 : 2017-05-02 오전 10:20:47
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_QUSTNR_QESITM CASCADE CONSTRAINTS;

CREATE TABLE TC_QUSTNR_QESITM (
  QESITM_SN           NUMBER(10)         NOT NULL,
  QUSTNR_SN           NUMBER(10)         NOT NULL,
  QESITM_TY_CD        CHAR(1)            NOT NULL,
  QESITM_SJ           VARCHAR2(1024)     NOT NULL,
  ESSNTL_ANSWER_AT    CHAR(1)           DEFAULT 'N'            NOT NULL,
  ESSNTL_CHOISE_QY    NUMBER(10)        DEFAULT 0
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_QUSTNR_QESITM IS '설문항목';

COMMENT ON COLUMN TC_QUSTNR_QESITM.QESITM_SN IS '문항일련번호';

COMMENT ON COLUMN TC_QUSTNR_QESITM.QUSTNR_SN IS '설문일련번호';

COMMENT ON COLUMN TC_QUSTNR_QESITM.QESITM_TY_CD IS '문항유형코드';

COMMENT ON COLUMN TC_QUSTNR_QESITM.QESITM_SJ IS '문항제목';

COMMENT ON COLUMN TC_QUSTNR_QESITM.ESSNTL_ANSWER_AT IS '필수답변여부';

COMMENT ON COLUMN TC_QUSTNR_QESITM.ESSNTL_CHOISE_QY IS '필수선택건수';

ALTER TABLE TC_QUSTNR_QESITM ADD
(
    CONSTRAINT PK_TC_QUSTNR_QESITM
    PRIMARY KEY ( QESITM_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_QUSTNR_ANSWER
-- 생성일 : 2017-02-10 오후 2:37:14
-- 최종수정일 : 2017-05-02 오전 10:20:36
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_QUSTNR_ANSWER CASCADE CONSTRAINTS;

CREATE TABLE TC_QUSTNR_ANSWER (
  ANSWER_SN    NUMBER(10)         NOT NULL,
  QESITM_SN    NUMBER(10)         NOT NULL,
  ANSWER_CN    VARCHAR2(4000),
  SORT_ORDR    NUMBER(10)        DEFAULT 0         NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_QUSTNR_ANSWER IS '설문답변';

COMMENT ON COLUMN TC_QUSTNR_ANSWER.ANSWER_SN IS '답변일련번호';

COMMENT ON COLUMN TC_QUSTNR_ANSWER.QESITM_SN IS '문항일련번호';

COMMENT ON COLUMN TC_QUSTNR_ANSWER.ANSWER_CN IS '답변내용';

COMMENT ON COLUMN TC_QUSTNR_ANSWER.SORT_ORDR IS '정렬순서';

ALTER TABLE TC_QUSTNR_ANSWER ADD
(
    CONSTRAINT PK_TC_QUSTNR_ANSWER
    PRIMARY KEY ( ANSWER_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TC_QUSTNR_ANSWER ADD
(
    CONSTRAINT FK_QUSTNR_ANSWER_QESITM
    FOREIGN KEY ( QESITM_SN )
        REFERENCES UCMS22.TC_QUSTNR_QESITM ( QESITM_SN )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_QUSTNR
-- 생성일 : 2017-02-14 오전 10:36:34
-- 최종수정일 : 2017-02-14 오전 10:36:35
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_QUSTNR CASCADE CONSTRAINTS;

CREATE TABLE TC_QUSTNR (
  QUSTNR_SN          NUMBER(10)         NOT NULL,
  QUSTNR_SJ          VARCHAR2(1024)     NOT NULL,
  BGNDE              DATE,
  ENDDE              DATE,
  STTUS_CD           VARCHAR2(16),
  TRGET_CD           VARCHAR2(16),
  RESULT_OTHBC_AT    CHAR(1)           DEFAULT 'Y'            NOT NULL,
  DEPT_ID            VARCHAR2(16),
  TELNO              VARCHAR2(32),
  QESTNAR_CN         CLOB,
  DELETE_CD          CHAR(1)           DEFAULT '0',
  REGIST_DT          DATE              DEFAULT SYSDATE               NOT NULL,
  REGIST_ID          VARCHAR2(64)       NOT NULL,
  UPDT_DT            DATE              DEFAULT SYSDATE,
  UPDT_ID            VARCHAR2(64)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_QUSTNR IS '설문조사';

COMMENT ON COLUMN TC_QUSTNR.QUSTNR_SN IS '설문일련번호';

COMMENT ON COLUMN TC_QUSTNR.QUSTNR_SJ IS '설문제목';

COMMENT ON COLUMN TC_QUSTNR.BGNDE IS '시작일';

COMMENT ON COLUMN TC_QUSTNR.ENDDE IS '종료일';

COMMENT ON COLUMN TC_QUSTNR.STTUS_CD IS '상태코드';

COMMENT ON COLUMN TC_QUSTNR.TRGET_CD IS '대상코드';

COMMENT ON COLUMN TC_QUSTNR.RESULT_OTHBC_AT IS '결과보기공개여부';

COMMENT ON COLUMN TC_QUSTNR.DEPT_ID IS '부서ID';

COMMENT ON COLUMN TC_QUSTNR.TELNO IS '전화번호';

COMMENT ON COLUMN TC_QUSTNR.QESTNAR_CN IS '설문조사내용';

COMMENT ON COLUMN TC_QUSTNR.DELETE_CD IS '삭제코드';

COMMENT ON COLUMN TC_QUSTNR.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_QUSTNR.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_QUSTNR.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TC_QUSTNR.UPDT_ID IS '수정ID';

ALTER TABLE TC_QUSTNR ADD
(
    CONSTRAINT PK_TC_QUSTNR
    PRIMARY KEY ( QUSTNR_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_PRHIBT_WRD_FLTER
-- 생성일 : 2017-01-05 오전 9:53:10
-- 최종수정일 : 2017-02-03 오후 4:31:48
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_PRHIBT_WRD_FLTER CASCADE CONSTRAINTS;

CREATE TABLE TC_PRHIBT_WRD_FLTER (
  WRD_SN       NUMBER(10)        NOT NULL,
  WRD_NM       VARCHAR2(256),
  USE_AT       CHAR(1)          DEFAULT 'Y',
  REGIST_ID    VARCHAR2(64),
  REGIST_DT    DATE,
  UPDT_ID      VARCHAR2(64),
  UPDT_DT      DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_PRHIBT_WRD_FLTER IS '금지단어필터';

COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.WRD_SN IS '단어일련번호';

COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.WRD_NM IS '단어명';

COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.USE_AT IS '사용여부';

ALTER TABLE TC_PRHIBT_WRD_FLTER ADD
(
    CONSTRAINT PK_TC_PRHIBT_WRD_FLTER
    PRIMARY KEY ( WRD_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_POPUP_MANAGE
-- 생성일 : 2017-02-08 오후 5:51:18
-- 최종수정일 : 2017-02-08 오후 8:13:18
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_POPUP_MANAGE CASCADE CONSTRAINTS;

CREATE TABLE TC_POPUP_MANAGE (
  POPUP_NO        NUMBER(10)         NOT NULL,
  POPUP_SJ        VARCHAR2(1024)     NOT NULL,
  POPUP_CN        CLOB,
  BGNDE           DATE              DEFAULT SYSDATE,
  ENDDE           DATE              DEFAULT SYSDATE,
  AR_VALUE        NUMBER(10),
  HG_VALUE        NUMBER(10),
  LFT_CRDNT       NUMBER(10),
  UPEND_CRDNT     NUMBER(10),
  CLOSE_USE_AT    CHAR(1),
  SITE_ID_SE      VARCHAR2(512),
  SITE_ID         VARCHAR2(32),
  ATCH_FILE_ID    CHAR(20),
  URLAD           VARCHAR2(512),
  SCRL_USE_AT     CHAR(1),
  LINK_TY_CD      VARCHAR2(16),
  MAP_CN          VARCHAR2(4000),
  USE_AT          CHAR(1)           DEFAULT 'Y'            NOT NULL,
  REGIST_ID       VARCHAR2(64)       NOT NULL,
  REGIST_DT       DATE               NOT NULL,
  UPDT_ID         VARCHAR2(64),
  UPDT_DT         DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_POPUP_MANAGE IS '팝업관리';

COMMENT ON COLUMN TC_POPUP_MANAGE.POPUP_NO IS '팝업번호';

COMMENT ON COLUMN TC_POPUP_MANAGE.POPUP_SJ IS '팝업제목';

COMMENT ON COLUMN TC_POPUP_MANAGE.POPUP_CN IS '팝업내용';

COMMENT ON COLUMN TC_POPUP_MANAGE.BGNDE IS '시작일';

COMMENT ON COLUMN TC_POPUP_MANAGE.ENDDE IS '종료일';

COMMENT ON COLUMN TC_POPUP_MANAGE.AR_VALUE IS '넓이값';

COMMENT ON COLUMN TC_POPUP_MANAGE.HG_VALUE IS '높이값';

COMMENT ON COLUMN TC_POPUP_MANAGE.LFT_CRDNT IS '좌측좌표';

COMMENT ON COLUMN TC_POPUP_MANAGE.UPEND_CRDNT IS '탑좌표';

COMMENT ON COLUMN TC_POPUP_MANAGE.CLOSE_USE_AT IS '닫기사용여부';

COMMENT ON COLUMN TC_POPUP_MANAGE.SITE_ID_SE IS '사이트ID구분';

COMMENT ON COLUMN TC_POPUP_MANAGE.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_POPUP_MANAGE.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_POPUP_MANAGE.URLAD IS '링크주소';

COMMENT ON COLUMN TC_POPUP_MANAGE.SCRL_USE_AT IS '스크롤사용여부';

COMMENT ON COLUMN TC_POPUP_MANAGE.LINK_TY_CD IS '링크타입코드';

COMMENT ON COLUMN TC_POPUP_MANAGE.MAP_CN IS '맵내용';

COMMENT ON COLUMN TC_POPUP_MANAGE.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_POPUP_MANAGE.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_POPUP_MANAGE.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_POPUP_MANAGE.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_POPUP_MANAGE.UPDT_DT IS '수정일시';

ALTER TABLE TC_POPUP_MANAGE ADD
(
    CONSTRAINT PK_TC_POPUP_MANAGE
    PRIMARY KEY ( POPUP_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_NTCN_RELM
-- 생성일 : 2017-05-02 오전 10:14:52
-- 최종수정일 : 2017-05-02 오전 10:14:54
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_NTCN_RELM CASCADE CONSTRAINTS;

CREATE TABLE TC_NTCN_RELM (
  NTCN_NO         NUMBER(10)        NOT NULL,
  NTCN_NM         VARCHAR2(256)     NOT NULL,
  NTCN_URLAD      VARCHAR2(512),
  NTCN_CN         CLOB,
  NTCN_TY_CD      VARCHAR2(16),
  SORT_ORDR       NUMBER(10),
  POPUP_AT        CHAR(1),
  MAP_USE_AT      CHAR(1),
  DEPT_ID         VARCHAR2(16),
  SITE_ID_SE      VARCHAR2(512),
  SITE_ID         VARCHAR2(32),
  ATCH_FILE_ID    CHAR(20),
  BGNDE           DATE             DEFAULT SYSDATE,
  ENDDE           DATE             DEFAULT SYSDATE,
  LINK_SE         CHAR(1),
  USE_AT          CHAR(1)          DEFAULT 'Y'           NOT NULL,
  REGIST_ID       VARCHAR2(64)      NOT NULL,
  REGIST_DT       DATE              NOT NULL,
  UPDT_ID         VARCHAR2(64),
  UPDT_DT         DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_NTCN_RELM IS '알림영역';

COMMENT ON COLUMN TC_NTCN_RELM.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TC_NTCN_RELM.NTCN_TY_CD IS '알림유형코드';

COMMENT ON COLUMN TC_NTCN_RELM.SORT_ORDR IS '정렬순서';

COMMENT ON COLUMN TC_NTCN_RELM.POPUP_AT IS '팝업여부';

COMMENT ON COLUMN TC_NTCN_RELM.MAP_USE_AT IS '맵사용여부';

COMMENT ON COLUMN TC_NTCN_RELM.DEPT_ID IS '부서ID';

COMMENT ON COLUMN TC_NTCN_RELM.SITE_ID_SE IS '사이트ID구분';

COMMENT ON COLUMN TC_NTCN_RELM.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_NTCN_RELM.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_NTCN_RELM.BGNDE IS '시작일';

COMMENT ON COLUMN TC_NTCN_RELM.ENDDE IS '종료일';

COMMENT ON COLUMN TC_NTCN_RELM.LINK_SE IS '링크구분';

COMMENT ON COLUMN TC_NTCN_RELM.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_NTCN_RELM.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_NTCN_RELM.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_NTCN_RELM.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_NTCN_RELM.NTCN_NO IS '알림번호';

COMMENT ON COLUMN TC_NTCN_RELM.NTCN_NM IS '알림명';

COMMENT ON COLUMN TC_NTCN_RELM.NTCN_URLAD IS '알림URL주소';

COMMENT ON COLUMN TC_NTCN_RELM.NTCN_CN IS '알림내용';

ALTER TABLE TC_NTCN_RELM ADD
(
    CONSTRAINT PK_TC_NTCN_RELM
    PRIMARY KEY ( NTCN_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_MNGR_MAIN_LC_ESTBS
-- 생성일 : 2017-02-08 오후 4:51:27
-- 최종수정일 : 2017-02-10 오전 11:05:52
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_MNGR_MAIN_LC_ESTBS CASCADE CONSTRAINTS;

CREATE TABLE TC_MNGR_MAIN_LC_ESTBS (
  SN             NUMBER(10)       NOT NULL,
  MNNO           NUMBER(10)       NOT NULL,
  LFT_CRDNT      NUMBER(10)       NOT NULL,
  UPEND_CRDNT    NUMBER(10)       NOT NULL,
  AR_VALUE       NUMBER(10)       NOT NULL,
  HG_VALUE       NUMBER(10)       NOT NULL,
  USE_AT         CHAR(1)         DEFAULT 'Y'          NOT NULL,
  USER_ID        VARCHAR2(64)     NOT NULL,
  UPDT_DT        DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_MNGR_MAIN_LC_ESTBS IS '관리자메인위치설정';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.SN IS '일련번호';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.MNNO IS '관리번호';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.LFT_CRDNT IS '좌측좌표';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.UPEND_CRDNT IS '탑좌표';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.AR_VALUE IS '넓이값';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.HG_VALUE IS '높이값';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.USER_ID IS '사용자ID';

COMMENT ON COLUMN TC_MNGR_MAIN_LC_ESTBS.UPDT_DT IS '수정일';

ALTER TABLE TC_MNGR_MAIN_LC_ESTBS ADD
(
    CONSTRAINT PK_TC_MNGR_MAIN_USER_ESTBS
    PRIMARY KEY ( SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_MNGR_MAIN_ESTBS_DETAIL
-- 생성일 : 2017-01-19 오후 1:19:25
-- 최종수정일 : 2017-02-03 오후 4:31:58
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_MNGR_MAIN_ESTBS_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE TC_MNGR_MAIN_ESTBS_DETAIL (
  MNNO             NUMBER(10)        NOT NULL,
  SN               NUMBER(10)        NOT NULL,
  ESTBS_NM         VARCHAR2(512),
  BBS_ID           VARCHAR2(16),
  URLAD            VARCHAR2(512),
  POPUP_AT         CHAR(1),
  ATCH_FILE_ID     CHAR(20),
  FILE_FIELD_NM    VARCHAR2(256),
  FIELD_ORDR       NUMBER(10)        NOT NULL,
  ICON_NM          VARCHAR2(64)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_MNGR_MAIN_ESTBS_DETAIL IS '관리자메인설정상세';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.MNNO IS '관리번호';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.SN IS '일련번호';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.ESTBS_NM IS '설정명';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.BBS_ID IS '게시판ID';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.URLAD IS 'URL주소';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.POPUP_AT IS '팝업여부';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.FILE_FIELD_NM IS '파일필드명';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.FIELD_ORDR IS '필드순서';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.ICON_NM IS '아이콘명';

ALTER TABLE TC_MNGR_MAIN_ESTBS_DETAIL ADD
(
    CONSTRAINT PK_TC_MNGR_MAIN_ESTBS_DETAIL
    PRIMARY KEY ( MNNO, SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TC_MNGR_MAIN_ESTBS_DETAIL ADD
(
    CONSTRAINT FK_TC_MNGR_MAIN_ESTBS_DETAIL
    FOREIGN KEY ( MNNO )
        REFERENCES UCMS22.TC_MNGR_MAIN_ESTBS ( MNNO )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_MNGR_MAIN_ESTBS
-- 생성일 : 2017-01-19 오후 1:19:25
-- 최종수정일 : 2017-02-10 오전 11:39:46
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_MNGR_MAIN_ESTBS CASCADE CONSTRAINTS;

CREATE TABLE TC_MNGR_MAIN_ESTBS (
  MNNO            NUMBER(10)       NOT NULL,
  SE_CD           VARCHAR2(16)     NOT NULL,
  BASS_MG         VARCHAR2(16)     NOT NULL,
  ESTBS_CN        CLOB,
  USE_AT          CHAR(1)         DEFAULT 'Y'          NOT NULL,
  REGIST_ID       VARCHAR2(64)     NOT NULL,
  REGIST_DT       DATE             NOT NULL,
  UPDT_ID         VARCHAR2(64),
  UPDT_DT         DATE,
  USER_ID         VARCHAR2(64),
  AR_MVL          NUMBER(10),
  AR_MNVL         NUMBER(10),
  HG_MVL          NUMBER(10),
  HG_MNVL         NUMBER(10),
  SIZE_UPDT_AT    CHAR(1)         DEFAULT 'N'
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_MNGR_MAIN_ESTBS IS '관리자메인설정';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.USER_ID IS '사용자ID';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.AR_MVL IS '넓이최대치';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.AR_MNVL IS '넓이최소치';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.MNNO IS '관리번호';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.SE_CD IS '설정구분코드';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.BASS_MG IS '기본크기';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.ESTBS_CN IS '설정내용';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.HG_MVL IS '높이최대치';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.HG_MNVL IS '높이최소치';

COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.SIZE_UPDT_AT IS '사이즈변경여부';

ALTER TABLE TC_MNGR_MAIN_ESTBS ADD
(
    CONSTRAINT PK_TC_MNGR_MAIN_ESTBS
    PRIMARY KEY ( MNNO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_MENU_INFO
-- 생성일 : 2017-05-02 오전 10:07:37
-- 최종수정일 : 2017-07-03 오전 9:35:40
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_MENU_INFO CASCADE CONSTRAINTS;

CREATE TABLE TC_MENU_INFO (
  MENU_NO                  NUMBER(10)         NOT NULL,
  MENU_NM                  VARCHAR2(256)      NOT NULL,
  UPPER_MENU_NO            NUMBER(10)         NOT NULL,
  MENU_ORDR                NUMBER(10)         NOT NULL,
  MENU_DC                  VARCHAR2(4000),
  MENU_CNTNTS_CD           VARCHAR2(16),
  MENU_LINK                VARCHAR2(512),
  POPUP_AT                 CHAR(1),
  SITE_ID                  VARCHAR2(32)       NOT NULL,
  DEPT_ID                  VARCHAR2(16),
  USER_ID                  VARCHAR2(64),
  RELATE_MENU_NM_LIST      VARCHAR2(4000),
  RELATE_MENU_LINK_LIST    VARCHAR2(4000),
  ALL_MENU_COURS           VARCHAR2(4000),
  CNTNTS_FILE_COURS        VARCHAR2(512),
  MENU_LC                  VARCHAR2(4000),
  BBS_ID                   VARCHAR2(16),
  LEAF_NODE_AT             CHAR(1),
  KWRD_NM                  VARCHAR2(1024),
  ADI_INFO                 VARCHAR2(4000),
  MENU_EXPSR_SE            VARCHAR2(10),
  USE_AT                   CHAR(1)           DEFAULT 'Y'            NOT NULL,
  DELETE_CD                CHAR(1)           DEFAULT '0'            NOT NULL,
  REGIST_ID                VARCHAR2(64)       NOT NULL,
  REGIST_DT                DATE               NOT NULL,
  UPDT_ID                  VARCHAR2(64),
  UPDT_DT                  DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_MENU_INFO IS '메뉴정보';

COMMENT ON COLUMN TC_MENU_INFO.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_MENU_INFO.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_MENU_INFO.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TC_MENU_INFO.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_MENU_INFO.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TC_MENU_INFO.MENU_NM IS '메뉴명';

COMMENT ON COLUMN TC_MENU_INFO.UPPER_MENU_NO IS '상위메뉴번호';

COMMENT ON COLUMN TC_MENU_INFO.MENU_ORDR IS '메뉴순서';

COMMENT ON COLUMN TC_MENU_INFO.MENU_DC IS '메뉴설명';

COMMENT ON COLUMN TC_MENU_INFO.MENU_CNTNTS_CD IS '메뉴콘텐츠코드';

COMMENT ON COLUMN TC_MENU_INFO.MENU_LINK IS '메뉴링크';

COMMENT ON COLUMN TC_MENU_INFO.POPUP_AT IS '팝업여부';

COMMENT ON COLUMN TC_MENU_INFO.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_MENU_INFO.DEPT_ID IS '부서ID';

COMMENT ON COLUMN TC_MENU_INFO.USER_ID IS '사용자ID';

COMMENT ON COLUMN TC_MENU_INFO.RELATE_MENU_NM_LIST IS '관련메뉴명목록';

COMMENT ON COLUMN TC_MENU_INFO.RELATE_MENU_LINK_LIST IS '관련메뉴링크목록';

COMMENT ON COLUMN TC_MENU_INFO.ALL_MENU_COURS IS '전체메뉴경로';

COMMENT ON COLUMN TC_MENU_INFO.CNTNTS_FILE_COURS IS '콘텐츠파일경로';

COMMENT ON COLUMN TC_MENU_INFO.MENU_LC IS '메뉴위치';

COMMENT ON COLUMN TC_MENU_INFO.BBS_ID IS '게시판ID';

COMMENT ON COLUMN TC_MENU_INFO.LEAF_NODE_AT IS '최종하위메뉴유무';

COMMENT ON COLUMN TC_MENU_INFO.KWRD_NM IS '키워드명';

COMMENT ON COLUMN TC_MENU_INFO.ADI_INFO IS '부가정보';

COMMENT ON COLUMN TC_MENU_INFO.MENU_EXPSR_SE IS '메뉴노출구분';

COMMENT ON COLUMN TC_MENU_INFO.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_MENU_INFO.DELETE_CD IS '삭제코드';

/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.I_TC_MENU_INFO_01
-- 생성일 : 2017-07-03 오전 9:35:40
-- 최종수정일 : 2017-07-03 오전 9:35:40
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP INDEX I_TC_MENU_INFO_01;

CREATE INDEX I_TC_MENU_INFO_01
ON TC_MENU_INFO (SITE_ID, DELETE_CD, UPPER_MENU_NO, MENU_ORDR)
TABLESPACE TSDT_UCMS22
LOGGING
NOPARALLEL;

ALTER TABLE TC_MENU_INFO ADD
(
    CONSTRAINT PK_TC_MENU_INFO
    PRIMARY KEY ( MENU_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_MENU_AUTHOR
-- 생성일 : 2017-01-06 오후 1:51:20
-- 최종수정일 : 2017-02-06 오후 6:39:45
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_MENU_AUTHOR CASCADE CONSTRAINTS;

CREATE TABLE TC_MENU_AUTHOR (
  MENU_NO         NUMBER(10)       NOT NULL,
  AUTHOR_CD       VARCHAR2(32)     NOT NULL,
  MAP_CREAT_ID    VARCHAR2(16),
  REGIST_DT       DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_MENU_AUTHOR IS '메뉴권한';

COMMENT ON COLUMN TC_MENU_AUTHOR.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TC_MENU_AUTHOR.AUTHOR_CD IS '권한코드';

COMMENT ON COLUMN TC_MENU_AUTHOR.MAP_CREAT_ID IS '맵생성ID';

COMMENT ON COLUMN TC_MENU_AUTHOR.REGIST_DT IS '등록일시';

ALTER TABLE TC_MENU_AUTHOR ADD
(
    CONSTRAINT PK_TC_MENU_AUTHOR
    PRIMARY KEY ( MENU_NO, AUTHOR_CD )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TC_MENU_AUTHOR ADD
(
    CONSTRAINT FK_TC_MENU_AUTHOR_INFO
    FOREIGN KEY ( AUTHOR_CD )
        REFERENCES UCMS22.TC_AUTHOR_INFO ( AUTHOR_CD )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_GLOBAL
-- 생성일 : 2017-01-24 오후 4:41:16
-- 최종수정일 : 2017-02-22 오후 2:28:33
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_GLOBAL CASCADE CONSTRAINTS;

CREATE TABLE TC_GLOBAL (
  ATTRB_SN       NUMBER(10)         NOT NULL,
  ATTRB_NM       VARCHAR2(256)      NOT NULL,
  ATTRB_VALUE    VARCHAR2(128),
  ATTRB_DC       VARCHAR2(4000),
  USE_AT         CHAR(1)           DEFAULT 'Y',
  REGIST_ID      VARCHAR2(64),
  REGIST_DT      DATE,
  UPDT_ID        VARCHAR2(64),
  UPDT_DT        DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_GLOBAL IS '글로벌:글로벌 변수설정하고 관리한다.';

COMMENT ON COLUMN TC_GLOBAL.ATTRB_SN IS '속성일련번호';

COMMENT ON COLUMN TC_GLOBAL.ATTRB_NM IS '속성명';

COMMENT ON COLUMN TC_GLOBAL.ATTRB_VALUE IS '속성값';

COMMENT ON COLUMN TC_GLOBAL.ATTRB_DC IS '속성설명';

COMMENT ON COLUMN TC_GLOBAL.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_GLOBAL.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_GLOBAL.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_GLOBAL.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_GLOBAL.UPDT_DT IS '수정일시';

ALTER TABLE TC_GLOBAL ADD
(
    CONSTRAINT PK_TC_GLOBAL
    PRIMARY KEY ( ATTRB_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CNTNTS_MANAGE
-- 생성일 : 2017-01-06 오후 3:08:42
-- 최종수정일 : 2017-02-06 오후 6:39:45
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CNTNTS_MANAGE CASCADE CONSTRAINTS;

CREATE TABLE TC_CNTNTS_MANAGE (
  MENU_NO        NUMBER(10)       NOT NULL,
  CNTNTS_MNNO    NUMBER(10)       NOT NULL,
  CNTNTS_CN      CLOB,
  DELETE_CD      CHAR(1)         DEFAULT '0'          NOT NULL,
  USE_AT         CHAR(1)         DEFAULT 'Y',
  REGIST_ID      VARCHAR2(64)     NOT NULL,
  REGIST_DT      DATE            DEFAULT SYSDATE             NOT NULL,
  UPDT_ID        VARCHAR2(64),
  UPDT_DT        DATE            DEFAULT SYSDATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CNTNTS_MANAGE IS '콘텐츠관리';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.CNTNTS_MNNO IS '컨텐츠관리번호';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.CNTNTS_CN IS '콘텐츠내용';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.DELETE_CD IS '삭제코드';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_CNTNTS_MANAGE.UPDT_DT IS '수정일시';

ALTER TABLE TC_CNTNTS_MANAGE ADD
(
    CONSTRAINT PK_TC_CNTNTS_MANAGE
    PRIMARY KEY ( MENU_NO, CNTNTS_MNNO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CMMN_SN
-- 생성일 : 2017-01-05 오전 9:53:22
-- 최종수정일 : 2017-02-03 오후 4:31:50
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CMMN_SN CASCADE CONSTRAINTS;

CREATE TABLE TC_CMMN_SN (
  TABLE_NM    VARCHAR2(256)     NOT NULL,
  NEXT_SN     NUMBER            NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CMMN_SN IS '공통일련번호';

COMMENT ON COLUMN TC_CMMN_SN.TABLE_NM IS '테이블명';

COMMENT ON COLUMN TC_CMMN_SN.NEXT_SN IS '다음일련번호';

ALTER TABLE TC_CMMN_SN ADD
(
    CONSTRAINT PK_TC_CMMN_SN
    PRIMARY KEY ( TABLE_NM )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CMMN_FILE_DWLD_HIST
-- 생성일 : 2017-03-16 오후 5:01:31
-- 최종수정일 : 2017-03-22 오후 2:44:32
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CMMN_FILE_DWLD_HIST CASCADE CONSTRAINTS;

CREATE TABLE TC_CMMN_FILE_DWLD_HIST (
  MNNO            NUMBER(22)       NOT NULL,
  ATCH_FILE_ID    CHAR(20)         NOT NULL,
  FILE_SN         NUMBER(10)       NOT NULL,
  MENU_NO         NUMBER(10),
  REGIST_ID       VARCHAR2(64),
  REGIST_DT       DATE             NOT NULL,
  SITE_ID         VARCHAR2(32)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CMMN_FILE_DWLD_HIST IS '공통파일다운로드이력';

COMMENT ON COLUMN TC_CMMN_FILE_DWLD_HIST.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_CMMN_FILE_DWLD_HIST.MNNO IS '관리번호';

COMMENT ON COLUMN TC_CMMN_FILE_DWLD_HIST.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_CMMN_FILE_DWLD_HIST.FILE_SN IS '파일일련번호';

COMMENT ON COLUMN TC_CMMN_FILE_DWLD_HIST.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TC_CMMN_FILE_DWLD_HIST.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_CMMN_FILE_DWLD_HIST.REGIST_DT IS '등록일시';


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CMMN_FILE_DETAIL
-- 생성일 : 2017-01-05 오전 9:53:21
-- 최종수정일 : 2017-02-03 오후 4:31:49
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CMMN_FILE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE TC_CMMN_FILE_DETAIL (
  ATCH_FILE_ID       CHAR(20)          NOT NULL,
  FILE_SN            NUMBER(10)        NOT NULL,
  FILE_STRE_COURS    VARCHAR2(512)     NOT NULL,
  STRE_FILE_NM       VARCHAR2(256)     NOT NULL,
  ORIGNL_FILE_NM     VARCHAR2(256)    DEFAULT NULL,
  FILE_EXTSN_NM      VARCHAR2(128)    DEFAULT NULL,
  FILE_SIZE          NUMBER(10)       DEFAULT NULL,
  FILE_CN            CLOB,
  FILE_FIELD_NM      VARCHAR2(256)    DEFAULT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CMMN_FILE_DETAIL IS '공통파일상세';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_SN IS '파일일련번호';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_STRE_COURS IS '파일저장경로';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.STRE_FILE_NM IS '저장파일명';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.ORIGNL_FILE_NM IS '원파일명';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_EXTSN_NM IS '파일확장자명';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_SIZE IS '파일사이즈';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_CN IS '파일내용';

COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_FIELD_NM IS '파일필드명';

ALTER TABLE TC_CMMN_FILE_DETAIL ADD
(
    CONSTRAINT PK_TC_CMMN_FILE_DETAIL
    PRIMARY KEY ( ATCH_FILE_ID, FILE_SN )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TC_CMMN_FILE_DETAIL ADD
(
    CONSTRAINT FK_TC_CMMN_FILE_DETAIL_FILE
    FOREIGN KEY ( ATCH_FILE_ID )
        REFERENCES UCMS22.TC_CMMN_FILE ( ATCH_FILE_ID )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CMMN_FILE
-- 생성일 : 2017-01-05 오전 9:53:22
-- 최종수정일 : 2017-02-03 오후 4:31:49
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CMMN_FILE CASCADE CONSTRAINTS;

CREATE TABLE TC_CMMN_FILE (
  ATCH_FILE_ID    CHAR(20)     NOT NULL,
  REGIST_DT       DATE         NOT NULL,
  USE_AT          CHAR(1)      NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CMMN_FILE IS '공통파일';

COMMENT ON COLUMN TC_CMMN_FILE.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_CMMN_FILE.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_CMMN_FILE.USE_AT IS '사용여부';

ALTER TABLE TC_CMMN_FILE ADD
(
    CONSTRAINT PK_TC_CMMN_FILE
    PRIMARY KEY ( ATCH_FILE_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CMMN_CD_MULTI
-- 생성일 : 2017-01-05 오전 9:53:23
-- 최종수정일 : 2017-02-03 오후 4:31:50
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CMMN_CD_MULTI CASCADE CONSTRAINTS;

CREATE TABLE TC_CMMN_CD_MULTI (
  CD_ID        VARCHAR2(16)       NOT NULL,
  PROGRM_ID    VARCHAR2(32)       NOT NULL,
  PROGRM_SN    NUMBER(10)         NOT NULL,
  CD           VARCHAR2(16)       NOT NULL,
  REGIST_DT    DATE,
  MEMO         VARCHAR2(4000)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CMMN_CD_MULTI IS '공통코드다중';

COMMENT ON COLUMN TC_CMMN_CD_MULTI.CD_ID IS '코드ID';

COMMENT ON COLUMN TC_CMMN_CD_MULTI.PROGRM_ID IS '프로그램ID';

COMMENT ON COLUMN TC_CMMN_CD_MULTI.PROGRM_SN IS '프로그램일련번호';

COMMENT ON COLUMN TC_CMMN_CD_MULTI.CD IS '코드';

COMMENT ON COLUMN TC_CMMN_CD_MULTI.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_CMMN_CD_MULTI.MEMO IS '메모';

ALTER TABLE TC_CMMN_CD_MULTI ADD
(
    CONSTRAINT PK_TC_CMMN_CD_MULTI
    PRIMARY KEY ( CD_ID, PROGRM_ID, PROGRM_SN, CD )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TC_CMMN_CD_MULTI ADD
(
    CONSTRAINT FK_TC_CMMN_CD_MULTI_DETAIL
    FOREIGN KEY ( CD, CD_ID )
        REFERENCES UCMS22.TC_CMMN_CD_DETAIL ( CD, CD_ID )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CMMN_CD_DETAIL
-- 생성일 : 2017-01-06 오후 2:45:31
-- 최종수정일 : 2017-02-10 오전 8:57:14
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CMMN_CD_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE TC_CMMN_CD_DETAIL (
  CD           VARCHAR2(16)       NOT NULL,
  CD_ID        VARCHAR2(16)       NOT NULL,
  CD_NM        VARCHAR2(256),
  CD_ENG_NM    VARCHAR2(256),
  CD_DC        VARCHAR2(4000),
  CD_ENG_DC    VARCHAR2(4000),
  UPPER_CD     VARCHAR2(16)      DEFAULT '0',
  DP           NUMBER(10)        DEFAULT 1,
  SORT_ORDR    NUMBER(10)        DEFAULT 0,
  OPTN1        VARCHAR2(4000),
  OPTN2        VARCHAR2(4000),
  OPTN3        VARCHAR2(4000),
  OPTN4        VARCHAR2(4000),
  OPTN5        VARCHAR2(4000),
  USE_AT       CHAR(1)           DEFAULT 'Y'            NOT NULL,
  REGIST_ID    VARCHAR2(64)       NOT NULL,
  REGIST_DT    DATE               NOT NULL,
  UPDT_ID      VARCHAR2(64),
  UPDT_DT      DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CMMN_CD_DETAIL IS '공통코드상세';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD IS '코드';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_ID IS '코드ID';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_NM IS '코드명';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_ENG_NM IS '코드영문명';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_DC IS '코드설명';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_ENG_DC IS '코드영문설명';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.UPPER_CD IS '상위코드';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.DP IS '깊이';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.SORT_ORDR IS '정렬순서';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN1 IS '옵션1';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN2 IS '옵션2';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN3 IS '옵션3';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN4 IS '옵션4';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN5 IS '옵션5';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_CMMN_CD_DETAIL.UPDT_DT IS '수정일시';

/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.I_TC_CMMN_CD_DETAIL_01
-- 생성일 : 2017-02-10 오전 8:57:14
-- 최종수정일 : 2017-02-10 오전 8:57:14
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP INDEX I_TC_CMMN_CD_DETAIL_01;

CREATE INDEX I_TC_CMMN_CD_DETAIL_01
ON TC_CMMN_CD_DETAIL (CD_ID, USE_AT)
TABLESPACE TSDT_UCMS22
LOGGING
NOPARALLEL;

ALTER TABLE TC_CMMN_CD_DETAIL ADD
(
    CONSTRAINT PK_TC_CMMN_CD_DETAIL
    PRIMARY KEY ( CD, CD_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TC_CMMN_CD_DETAIL ADD
(
    CONSTRAINT FK_TC_CMMN_CD_DETAIL_CTGRY
    FOREIGN KEY ( CD_ID )
        REFERENCES UCMS22.TC_CMMN_CD_CTGRY ( CD_ID )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CMMN_CD_CTGRY
-- 생성일 : 2017-01-06 오후 2:45:30
-- 최종수정일 : 2017-02-03 오후 4:31:55
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CMMN_CD_CTGRY CASCADE CONSTRAINTS;

CREATE TABLE TC_CMMN_CD_CTGRY (
  CD_ID           VARCHAR2(16)       NOT NULL,
  CL_CD           VARCHAR2(16)       NOT NULL,
  CD_ID_NM        VARCHAR2(256),
  CD_ID_ENG_NM    VARCHAR2(256),
  CD_ID_DC        VARCHAR2(4000),
  CD_ID_ENG_DC    VARCHAR2(4000),
  USE_AT          CHAR(1)           DEFAULT 'Y'            NOT NULL,
  REGIST_ID       VARCHAR2(64)       NOT NULL,
  REGIST_DT       DATE               NOT NULL,
  UPDT_ID         VARCHAR2(64),
  UPDT_DT         DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CMMN_CD_CTGRY IS '공통코드카테고리';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID IS '코드ID';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CL_CD IS '분류코드';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID_NM IS '코드ID명';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID_ENG_NM IS '코드ID영문명';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID_DC IS '코드ID설명';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID_ENG_DC IS '코드ID영문설명';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_CMMN_CD_CTGRY.UPDT_DT IS '수정일시';

ALTER TABLE TC_CMMN_CD_CTGRY ADD
(
    CONSTRAINT PK_TC_CMMN_CD_CTGRY
    PRIMARY KEY ( CD_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TC_CMMN_CD_CTGRY ADD
(
    CONSTRAINT FK_TC_CMMN_CD_CTGRY_CMMN_CD_CL
    FOREIGN KEY ( CL_CD )
        REFERENCES UCMS22.TC_CMMN_CD_CL ( CL_CD )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_CMMN_CD_CL
-- 생성일 : 2017-01-06 오후 2:45:30
-- 최종수정일 : 2017-02-03 오후 4:31:55
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_CMMN_CD_CL CASCADE CONSTRAINTS;

CREATE TABLE TC_CMMN_CD_CL (
  CL_CD        VARCHAR2(16)       NOT NULL,
  CL_CD_NM     VARCHAR2(256),
  CL_CD_DC     VARCHAR2(4000),
  USE_AT       CHAR(1)           DEFAULT 'Y'            NOT NULL,
  REGIST_ID    VARCHAR2(64)       NOT NULL,
  REGIST_DT    DATE               NOT NULL,
  UPDT_ID      VARCHAR2(64),
  UPDT_DT      DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_CMMN_CD_CL IS '공통코드분류';

COMMENT ON COLUMN TC_CMMN_CD_CL.CL_CD IS '분류코드';

COMMENT ON COLUMN TC_CMMN_CD_CL.CL_CD_NM IS '분류코드명';

COMMENT ON COLUMN TC_CMMN_CD_CL.CL_CD_DC IS '분류코드설명';

COMMENT ON COLUMN TC_CMMN_CD_CL.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_CMMN_CD_CL.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_CMMN_CD_CL.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_CMMN_CD_CL.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_CMMN_CD_CL.UPDT_DT IS '수정일시';

ALTER TABLE TC_CMMN_CD_CL ADD
(
    CONSTRAINT PK_TC_CMMN_CD_CL
    PRIMARY KEY ( CL_CD )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_BANNER
-- 생성일 : 2017-02-08 오후 5:51:18
-- 최종수정일 : 2017-02-08 오후 5:54:51
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_BANNER CASCADE CONSTRAINTS;

CREATE TABLE TC_BANNER (
  BANNER_NO       NUMBER(10)        NOT NULL,
  BANNER_NM       VARCHAR2(256)     NOT NULL,
  BANNER_URLAD    VARCHAR2(512),
  BANNER_SE       VARCHAR2(16),
  DONG_CD         VARCHAR2(16),
  SORT_ORDR       NUMBER(10),
  EXPSR_AT        CHAR(1),
  POPUP_AT        CHAR(1)          DEFAULT 'N',
  DEPT_ID         VARCHAR2(16),
  SITE_ID_SE      VARCHAR2(512),
  SITE_ID         VARCHAR2(32),
  ATCH_FILE_ID    CHAR(20),
  BGNDE           DATE             DEFAULT SYSDATE,
  ENDDE           DATE             DEFAULT SYSDATE,
  USE_AT          CHAR(1)          DEFAULT 'Y'           NOT NULL,
  REGIST_ID       VARCHAR2(64)      NOT NULL,
  REGIST_DT       DATE              NOT NULL,
  UPDT_ID         VARCHAR2(64),
  UPDT_DT         DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_BANNER IS '배너';

COMMENT ON COLUMN TC_BANNER.BANNER_NO IS '배너번호';

COMMENT ON COLUMN TC_BANNER.BANNER_NM IS '배너명';

COMMENT ON COLUMN TC_BANNER.BANNER_URLAD IS '배너URL주소';

COMMENT ON COLUMN TC_BANNER.BANNER_SE IS '배너구분';

COMMENT ON COLUMN TC_BANNER.DONG_CD IS '동코드';

COMMENT ON COLUMN TC_BANNER.SORT_ORDR IS '정렬순서';

COMMENT ON COLUMN TC_BANNER.EXPSR_AT IS '노출여부';

COMMENT ON COLUMN TC_BANNER.POPUP_AT IS '팝업여부';

COMMENT ON COLUMN TC_BANNER.DEPT_ID IS '부서ID';

COMMENT ON COLUMN TC_BANNER.SITE_ID_SE IS '사이트ID구분';

COMMENT ON COLUMN TC_BANNER.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TC_BANNER.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TC_BANNER.BGNDE IS '시작일';

COMMENT ON COLUMN TC_BANNER.ENDDE IS '종료일';

COMMENT ON COLUMN TC_BANNER.USE_AT IS '사용여부';

COMMENT ON COLUMN TC_BANNER.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TC_BANNER.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TC_BANNER.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TC_BANNER.UPDT_DT IS '수정일시';

ALTER TABLE TC_BANNER ADD
(
    CONSTRAINT PK_TC_BANNER
    PRIMARY KEY ( BANNER_NO )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_AUTHOR_SCLSRT
-- 생성일 : 2017-01-05 오전 9:53:49
-- 최종수정일 : 2017-02-03 오후 4:31:51
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_AUTHOR_SCLSRT CASCADE CONSTRAINTS;

CREATE TABLE TC_AUTHOR_SCLSRT (
  PARNTS_AUTHOR_CD    VARCHAR2(32)     NOT NULL,
  CHLDRN_AUTHOR_CD    VARCHAR2(32)     NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_AUTHOR_SCLSRT IS '권한계층';

COMMENT ON COLUMN TC_AUTHOR_SCLSRT.PARNTS_AUTHOR_CD IS '부모권한';

COMMENT ON COLUMN TC_AUTHOR_SCLSRT.CHLDRN_AUTHOR_CD IS '자식권한';

ALTER TABLE TC_AUTHOR_SCLSRT ADD
(
    CONSTRAINT PK_TC_AUTHOR_SCLSRT
    PRIMARY KEY ( PARNTS_AUTHOR_CD, CHLDRN_AUTHOR_CD )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TC_AUTHOR_INFO
-- 생성일 : 2017-01-05 오전 9:53:49
-- 최종수정일 : 2017-02-03 오후 4:31:51
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TC_AUTHOR_INFO CASCADE CONSTRAINTS;

CREATE TABLE TC_AUTHOR_INFO (
  AUTHOR_CD    VARCHAR2(32)       NOT NULL,
  AUTHOR_NM    VARCHAR2(256)      NOT NULL,
  AUTHOR_DC    VARCHAR2(4000)    DEFAULT NULL,
  REGIST_DT    DATE               NOT NULL
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TC_AUTHOR_INFO IS '권한정보';

COMMENT ON COLUMN TC_AUTHOR_INFO.AUTHOR_CD IS '권한코드';

COMMENT ON COLUMN TC_AUTHOR_INFO.AUTHOR_NM IS '권한명';

COMMENT ON COLUMN TC_AUTHOR_INFO.AUTHOR_DC IS '권한설명';

COMMENT ON COLUMN TC_AUTHOR_INFO.REGIST_DT IS '등록일시';

ALTER TABLE TC_AUTHOR_INFO ADD
(
    CONSTRAINT PK_TC_AUTHOR_INFO
    PRIMARY KEY ( AUTHOR_CD )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TB_FIELD_INFO
-- 생성일 : 2017-01-05 오전 9:53:50
-- 최종수정일 : 2017-02-03 오후 4:31:51
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TB_FIELD_INFO CASCADE CONSTRAINTS;

CREATE TABLE TB_FIELD_INFO (
  FIELD_ID        NUMBER(10)         NOT NULL,
  ATTRB_CD        VARCHAR2(16)       NOT NULL,
  ATTRB_TY_CD     VARCHAR2(16)       NOT NULL,
  FIELD_IEM_NM    VARCHAR2(256)      NOT NULL,
  FIELD_TY_CD     VARCHAR2(16)       NOT NULL,
  FIELD_DC        VARCHAR2(4000)     NOT NULL,
  FIELD_ORDR      NUMBER(10)        DEFAULT NULL,
  LIST_USE_AT     CHAR(1)           DEFAULT 'N'
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TB_FIELD_INFO IS '게시판 필드정보';

COMMENT ON COLUMN TB_FIELD_INFO.FIELD_ID IS '필드ID';

COMMENT ON COLUMN TB_FIELD_INFO.ATTRB_CD IS '속성코드';

COMMENT ON COLUMN TB_FIELD_INFO.ATTRB_TY_CD IS '속성유형코드';

COMMENT ON COLUMN TB_FIELD_INFO.FIELD_IEM_NM IS '필드항목명';

COMMENT ON COLUMN TB_FIELD_INFO.FIELD_TY_CD IS '필드유형코드';

COMMENT ON COLUMN TB_FIELD_INFO.FIELD_DC IS '필드설명';

COMMENT ON COLUMN TB_FIELD_INFO.FIELD_ORDR IS '필드순서';

COMMENT ON COLUMN TB_FIELD_INFO.LIST_USE_AT IS '리스트사용여부';

ALTER TABLE TB_FIELD_INFO ADD
(
    CONSTRAINT PK_TB_FIELD_INFO
    PRIMARY KEY ( FIELD_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TB_FIELD_INFO ADD
(
    CONSTRAINT FK_TB_FIELD_INFO_ATTRB_INFO
    FOREIGN KEY ( ATTRB_CD )
        REFERENCES UCMS22.TB_ATTRB_INFO ( ATTRB_CD )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TB_BBS_MASTR
-- 생성일 : 2017-01-06 오후 1:26:46
-- 최종수정일 : 2017-02-03 오후 4:31:54
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TB_BBS_MASTR CASCADE CONSTRAINTS;

CREATE TABLE TB_BBS_MASTR (
  BBS_ID                  VARCHAR2(16)       NOT NULL,
  BBS_TY_CD               VARCHAR2(16)       NOT NULL,
  BBS_ATTRB_CD            VARCHAR2(16)       NOT NULL,
  BBS_NM                  VARCHAR2(512)      NOT NULL,
  BBS_DC                  VARCHAR2(4000),
  REPLY_POSBL_AT          CHAR(1),
  FILE_ATCH_POSBL_AT      CHAR(1),
  ATCH_POSBL_FILE_CO      NUMBER(10),
  ATCH_POSBL_FILE_SIZE    VARCHAR2(32),
  NTCE_BGNDE              VARCHAR2(10),
  NTCE_ENDDE              VARCHAR2(10),
  TMPLAT_ID               CHAR(20),
  CM_POSBL_AT             CHAR(1),
  ADIT_CNTNTS_CN          CLOB,
  PAGE_SIZE               NUMBER(10),
  PAGE_UNIT               NUMBER(10),
  PREV_NEXT_POSBL_AT      CHAR(1),
  TABLE_NM                VARCHAR2(256),
  DELETE_CD               CHAR(1)           DEFAULT '0'            NOT NULL,
  USE_AT                  CHAR(1),
  REGIST_ID               VARCHAR2(64)       NOT NULL,
  REGIST_DT               DATE              DEFAULT SYSDATE               NOT NULL,
  UPDT_ID                 VARCHAR2(64),
  UPDT_DT                 DATE              DEFAULT SYSDATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TB_BBS_MASTR IS '게시판마스터';

COMMENT ON COLUMN TB_BBS_MASTR.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TB_BBS_MASTR.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TB_BBS_MASTR.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TB_BBS_MASTR.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TB_BBS_MASTR.BBS_ID IS '게시판ID';

COMMENT ON COLUMN TB_BBS_MASTR.BBS_TY_CD IS '게시판유형코드';

COMMENT ON COLUMN TB_BBS_MASTR.BBS_ATTRB_CD IS '게시판속성코드';

COMMENT ON COLUMN TB_BBS_MASTR.BBS_NM IS '게시판명';

COMMENT ON COLUMN TB_BBS_MASTR.BBS_DC IS '게시판설명';

COMMENT ON COLUMN TB_BBS_MASTR.REPLY_POSBL_AT IS '답글가능여부';

COMMENT ON COLUMN TB_BBS_MASTR.FILE_ATCH_POSBL_AT IS '파일첨부가능여부';

COMMENT ON COLUMN TB_BBS_MASTR.ATCH_POSBL_FILE_CO IS '첨부가능파일건수';

COMMENT ON COLUMN TB_BBS_MASTR.ATCH_POSBL_FILE_SIZE IS '첨부가능파일사이즈';

COMMENT ON COLUMN TB_BBS_MASTR.NTCE_BGNDE IS '게시시작일';

COMMENT ON COLUMN TB_BBS_MASTR.NTCE_ENDDE IS '게시종료일';

COMMENT ON COLUMN TB_BBS_MASTR.TMPLAT_ID IS '템플릿ID';

COMMENT ON COLUMN TB_BBS_MASTR.CM_POSBL_AT IS '코멘트가능여부';

COMMENT ON COLUMN TB_BBS_MASTR.ADIT_CNTNTS_CN IS '추가컨텐츠내용';

COMMENT ON COLUMN TB_BBS_MASTR.PAGE_SIZE IS '페이지사이즈';

COMMENT ON COLUMN TB_BBS_MASTR.PAGE_UNIT IS '페이지단위';

COMMENT ON COLUMN TB_BBS_MASTR.PREV_NEXT_POSBL_AT IS '이전글다음글사용여부';

COMMENT ON COLUMN TB_BBS_MASTR.TABLE_NM IS '테이블명';

COMMENT ON COLUMN TB_BBS_MASTR.DELETE_CD IS '삭제코드';

COMMENT ON COLUMN TB_BBS_MASTR.USE_AT IS '사용여부(Y:사용,N:미사용)';

ALTER TABLE TB_BBS_MASTR ADD
(
    CONSTRAINT PK_TB_BBS_MASTR
    PRIMARY KEY ( BBS_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TB_BBS_MASTR ADD
(
    CONSTRAINT FK_TB_BBS_MASTR_TMPLAT_INFO
    FOREIGN KEY ( TMPLAT_ID )
        REFERENCES UCMS22.TC_TMPLAT_INFO ( TMPLAT_ID )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TB_BBS_ESTN
-- 생성일 : 2017-01-06 오전 11:50:40
-- 최종수정일 : 2017-02-16 오후 5:55:21
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TB_BBS_ESTN CASCADE CONSTRAINTS;

CREATE TABLE TB_BBS_ESTN (
  NTT_ID                 NUMBER(10)         NOT NULL,
  BBS_ID                 VARCHAR2(16)       NOT NULL,
  SORT_ORDR              NUMBER(10),
  NTT_SJ                 VARCHAR2(1024),
  NTT_CN                 CLOB,
  NTCR_ID                VARCHAR2(64),
  NTCR_NM                VARCHAR2(128),
  NTCR_EMAD              VARCHAR2(512),
  NTCR_ZIP               VARCHAR2(7),
  NTCR_ADRES1            VARCHAR2(256),
  NTCR_ADRES2            VARCHAR2(512),
  NTCR_TELNO             VARCHAR2(32),
  NTCR_CPNO              VARCHAR2(32),
  NTCR_PIN               VARCHAR2(128),
  PASSWORD               VARCHAR2(256),
  INQIRE_CO              NUMBER(10),
  NTCE_BGNDE             VARCHAR2(10),
  NTCE_ENDDE             VARCHAR2(10),
  ANSWER_AT              CHAR(1),
  PARNTS_NO              NUMBER(10),
  NTT_NO                 NUMBER(10),
  ANSWER_LC              NUMBER(10),
  SECRET_AT              CHAR(1),
  NTT_TY_CD              VARCHAR2(16)       NOT NULL,
  USER_SN                NUMBER(10),
  ATCH_FILE_ID           CHAR(20),
  DEPT_ID                VARCHAR2(16),
  DEPT_NM                VARCHAR2(256),
  HTML_AT                CHAR(1)           DEFAULT 'N',
  BBS_SE_CD              VARCHAR2(16),
  IMAGE_REPLC_TEXT_CN    CLOB,
  SITE_ID                VARCHAR2(32),
  OPTN1                  VARCHAR2(4000),
  OPTN2                  VARCHAR2(4000),
  OPTN3                  VARCHAR2(4000),
  OPTN4                  VARCHAR2(4000),
  OPTN5                  VARCHAR2(4000),
  OPTN6                  VARCHAR2(4000),
  OPTN7                  VARCHAR2(4000),
  OPTN8                  VARCHAR2(4000),
  OPTN9                  VARCHAR2(4000),
  OPTN10                 VARCHAR2(4000),
  OPTN11                 VARCHAR2(4000),
  OPTN12                 VARCHAR2(4000),
  OPTN13                 VARCHAR2(4000),
  OPTN14                 VARCHAR2(4000),
  OPTN15                 VARCHAR2(4000),
  OPTN16                 VARCHAR2(4000),
  OPTN17                 VARCHAR2(4000),
  OPTN18                 VARCHAR2(4000),
  OPTN19                 VARCHAR2(4000),
  OPTN20                 VARCHAR2(4000),
  DELETE_CD              CHAR(1)           DEFAULT '0'            NOT NULL,
  USE_AT                 CHAR(1),
  REGIST_ID              VARCHAR2(64)       NOT NULL,
  REGIST_DT              DATE              DEFAULT SYSDATE               NOT NULL,
  UPDT_ID                VARCHAR2(64),
  UPDT_DT                DATE              DEFAULT SYSDATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TB_BBS_ESTN IS '게시판확장';

COMMENT ON COLUMN TB_BBS_ESTN.NTT_ID IS '게시물ID';

COMMENT ON COLUMN TB_BBS_ESTN.BBS_ID IS '게시판ID';

COMMENT ON COLUMN TB_BBS_ESTN.SORT_ORDR IS '정렬순서';

COMMENT ON COLUMN TB_BBS_ESTN.NTT_SJ IS '게시물제목';

COMMENT ON COLUMN TB_BBS_ESTN.NTT_CN IS '게시글내용';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_ID IS '게시자ID';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_NM IS '게시자명';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_EMAD IS '게시자이메일주소';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_ZIP IS '게시자우편번호';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_ADRES1 IS '게시자주소1';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_ADRES2 IS '게시자주소2';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_TELNO IS '게시자전화번호';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_CPNO IS '게시자휴대전화번호';

COMMENT ON COLUMN TB_BBS_ESTN.NTCR_PIN IS '게시자개인식별번호';

COMMENT ON COLUMN TB_BBS_ESTN.PASSWORD IS '비밀번호';

COMMENT ON COLUMN TB_BBS_ESTN.INQIRE_CO IS '조회횟수';

COMMENT ON COLUMN TB_BBS_ESTN.NTCE_BGNDE IS '게시시작일';

COMMENT ON COLUMN TB_BBS_ESTN.NTCE_ENDDE IS '게시종료일';

COMMENT ON COLUMN TB_BBS_ESTN.ANSWER_AT IS '답글여부';

COMMENT ON COLUMN TB_BBS_ESTN.PARNTS_NO IS '부모글번호';

COMMENT ON COLUMN TB_BBS_ESTN.NTT_NO IS '게시물번호';

COMMENT ON COLUMN TB_BBS_ESTN.ANSWER_LC IS '답글위치';

COMMENT ON COLUMN TB_BBS_ESTN.SECRET_AT IS '비밀여부';

COMMENT ON COLUMN TB_BBS_ESTN.NTT_TY_CD IS '게시글유형코드';

COMMENT ON COLUMN TB_BBS_ESTN.USER_SN IS '사용자일련번호';

COMMENT ON COLUMN TB_BBS_ESTN.ATCH_FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN TB_BBS_ESTN.DEPT_ID IS '부서ID';

COMMENT ON COLUMN TB_BBS_ESTN.DEPT_NM IS '부서명';

COMMENT ON COLUMN TB_BBS_ESTN.HTML_AT IS 'HTML여부';

COMMENT ON COLUMN TB_BBS_ESTN.BBS_SE_CD IS '게시판구분코드';

COMMENT ON COLUMN TB_BBS_ESTN.IMAGE_REPLC_TEXT_CN IS '이미지대체텍스트내용';

COMMENT ON COLUMN TB_BBS_ESTN.SITE_ID IS '사이트ID';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN1 IS '옵션1';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN2 IS '옵션2';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN3 IS '옵션3';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN4 IS '옵션4';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN5 IS '옵션5';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN6 IS '옵션6';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN7 IS '옵션7';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN8 IS '옵션8';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN9 IS '옵션9';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN10 IS '옵션10';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN11 IS '옵션11';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN12 IS '옵션12';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN13 IS '옵션13';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN14 IS '옵션14';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN15 IS '옵션15';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN16 IS '옵션16';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN17 IS '옵션17';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN18 IS '옵션18';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN19 IS '옵션19';

COMMENT ON COLUMN TB_BBS_ESTN.OPTN20 IS '옵션20';

COMMENT ON COLUMN TB_BBS_ESTN.DELETE_CD IS '삭제코드';

COMMENT ON COLUMN TB_BBS_ESTN.USE_AT IS '사용여부';

COMMENT ON COLUMN TB_BBS_ESTN.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TB_BBS_ESTN.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TB_BBS_ESTN.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TB_BBS_ESTN.UPDT_DT IS '수정일시';

/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.I_TB_BBS_ESTN_01
-- 생성일 : 2017-02-13 오전 10:02:56
-- 최종수정일 : 2017-02-13 오전 10:02:56
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP INDEX I_TB_BBS_ESTN_01;

CREATE INDEX I_TB_BBS_ESTN_01
ON TB_BBS_ESTN (BBS_ID, DELETE_CD, USE_AT, "REGIST_DT" DESC)
TABLESPACE TSDT_UCMS22
LOGGING
NOPARALLEL;

ALTER TABLE TB_BBS_ESTN ADD
(
    CONSTRAINT PK_TB_BBS_ESTN
    PRIMARY KEY ( NTT_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

ALTER TABLE TB_BBS_ESTN ADD
(
    CONSTRAINT FK_TB_BBS_ESTN_CMMN_FILE
    FOREIGN KEY ( ATCH_FILE_ID )
        REFERENCES UCMS22.TC_CMMN_FILE ( ATCH_FILE_ID )
);

ALTER TABLE TB_BBS_ESTN ADD
(
    CONSTRAINT FK_TB_BBS_ESTN_BBS_MASTR
    FOREIGN KEY ( BBS_ID )
        REFERENCES UCMS22.TB_BBS_MASTR ( BBS_ID )
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TB_BBS_CM
-- 생성일 : 2017-01-06 오전 11:26:11
-- 최종수정일 : 2017-02-21 오후 6:40:40
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TB_BBS_CM CASCADE CONSTRAINTS;

CREATE TABLE TB_BBS_CM (
  CM_ID           NUMBER(10)         NOT NULL,
  NTT_ID          NUMBER(10)         NOT NULL,
  NTT_SJ          VARCHAR2(1024),
  NTT_CN          CLOB,
  BBS_ID          VARCHAR2(16)       NOT NULL,
  NTCR_ID         VARCHAR2(64)       NOT NULL,
  NTCR_NM         VARCHAR2(128),
  PASSWORD        VARCHAR2(256),
  NTCR_EMAD       VARCHAR2(512),
  RECOMMEND_CO    NUMBER(10),
  CM_SE           VARCHAR2(64)       NOT NULL,
  USER_SN         NUMBER(10),
  OPTN1           VARCHAR2(4000),
  OPTN2           VARCHAR2(4000),
  OPTN3           VARCHAR2(4000),
  OPTN4           VARCHAR2(4000),
  OPTN5           VARCHAR2(4000),
  OPTN6           VARCHAR2(4000),
  OPTN7           VARCHAR2(4000),
  OPTN8           VARCHAR2(4000),
  OPTN9           VARCHAR2(4000),
  OPTN10          VARCHAR2(4000),
  EXPSR_AT        CHAR(1)            NOT NULL,
  DELETE_CD       CHAR(1),
  USE_AT          CHAR(1),
  REGIST_ID       VARCHAR2(64),
  REGIST_DT       DATE,
  UPDT_ID         VARCHAR2(64),
  UPDT_DT         DATE
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TB_BBS_CM IS '게시판코멘트';

COMMENT ON COLUMN TB_BBS_CM.DELETE_CD IS '삭제코드(0:보임,1:사용자삭제,2:관리자삭제)';

COMMENT ON COLUMN TB_BBS_CM.USE_AT IS '사용여부';

COMMENT ON COLUMN TB_BBS_CM.REGIST_ID IS '등록ID';

COMMENT ON COLUMN TB_BBS_CM.REGIST_DT IS '등록일시';

COMMENT ON COLUMN TB_BBS_CM.UPDT_ID IS '수정ID';

COMMENT ON COLUMN TB_BBS_CM.UPDT_DT IS '수정일시';

COMMENT ON COLUMN TB_BBS_CM.CM_ID IS '코멘트ID';

COMMENT ON COLUMN TB_BBS_CM.NTT_ID IS '게시물ID';

COMMENT ON COLUMN TB_BBS_CM.NTT_SJ IS '게시물제목';

COMMENT ON COLUMN TB_BBS_CM.NTT_CN IS '게시글내용';

COMMENT ON COLUMN TB_BBS_CM.BBS_ID IS '게시판ID';

COMMENT ON COLUMN TB_BBS_CM.NTCR_ID IS '게시자ID';

COMMENT ON COLUMN TB_BBS_CM.NTCR_NM IS '게시자명';

COMMENT ON COLUMN TB_BBS_CM.PASSWORD IS '비밀번호';

COMMENT ON COLUMN TB_BBS_CM.NTCR_EMAD IS '게시자이메일주소';

COMMENT ON COLUMN TB_BBS_CM.RECOMMEND_CO IS '추천수';

COMMENT ON COLUMN TB_BBS_CM.CM_SE IS '코멘트구분';

COMMENT ON COLUMN TB_BBS_CM.USER_SN IS '사용자일련번호';

COMMENT ON COLUMN TB_BBS_CM.OPTN1 IS '옵션1';

COMMENT ON COLUMN TB_BBS_CM.OPTN2 IS '옵션2';

COMMENT ON COLUMN TB_BBS_CM.OPTN3 IS '옵션3';

COMMENT ON COLUMN TB_BBS_CM.OPTN4 IS '옵션4';

COMMENT ON COLUMN TB_BBS_CM.OPTN5 IS '옵션5';

COMMENT ON COLUMN TB_BBS_CM.OPTN6 IS '옵션6';

COMMENT ON COLUMN TB_BBS_CM.OPTN7 IS '옵션7';

COMMENT ON COLUMN TB_BBS_CM.OPTN8 IS '옵션8';

COMMENT ON COLUMN TB_BBS_CM.OPTN9 IS '옵션9';

COMMENT ON COLUMN TB_BBS_CM.OPTN10 IS '옵션10';

COMMENT ON COLUMN TB_BBS_CM.EXPSR_AT IS '노출여부';

ALTER TABLE TB_BBS_CM ADD
(
    CONSTRAINT PK_TB_BBS_CM
    PRIMARY KEY ( CM_ID )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);


/*------------------------------------------------------------------------------
-- 개체명 : UCMS22.TB_ATTRB_INFO
-- 생성일 : 2017-01-05 오전 9:53:55
-- 최종수정일 : 2017-02-22 오후 2:45:56
-- 상태 : VALID
------------------------------------------------------------------------------*/
DROP TABLE TB_ATTRB_INFO CASCADE CONSTRAINTS;

CREATE TABLE TB_ATTRB_INFO (
  ATTRB_CD     VARCHAR2(16)       NOT NULL,
  ATTRB_NM     VARCHAR2(256),
  REGIST_DT    DATE               NOT NULL,
  TABLE_NM     VARCHAR2(256)      NOT NULL,
  ATTRB_DC     VARCHAR2(4000)
)
TABLESPACE TSDT_UCMS22
;

COMMENT ON TABLE TB_ATTRB_INFO IS '속성정보';

COMMENT ON COLUMN TB_ATTRB_INFO.TABLE_NM IS '테이블명';

COMMENT ON COLUMN TB_ATTRB_INFO.ATTRB_DC IS '속성설명';

COMMENT ON COLUMN TB_ATTRB_INFO.ATTRB_CD IS '속성코드';

COMMENT ON COLUMN TB_ATTRB_INFO.ATTRB_NM IS '속성명';

COMMENT ON COLUMN TB_ATTRB_INFO.REGIST_DT IS '등록일시';

ALTER TABLE TB_ATTRB_INFO ADD
(
    CONSTRAINT PK_TB_ATTRB_INFO
    PRIMARY KEY ( ATTRB_CD )
        USING INDEX
        TABLESPACE TSDT_UCMS22
);

