--------------------------------------------------------
--  파일이 생성됨 - 월요일-8월-14-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_ATTRB_INFO
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TB_ATTRB_INFO" 
   (	"ATTRB_CD" VARCHAR2(16 BYTE), 
	"ATTRB_NM" VARCHAR2(256 BYTE), 
	"REGIST_DT" DATE, 
	"TABLE_NM" VARCHAR2(256 BYTE), 
	"ATTRB_DC" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TB_ATTRB_INFO"."ATTRB_CD" IS '속성코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_ATTRB_INFO"."ATTRB_NM" IS '속성명';
 
   COMMENT ON COLUMN "UCMS22"."TB_ATTRB_INFO"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TB_ATTRB_INFO"."TABLE_NM" IS '테이블명';
 
   COMMENT ON COLUMN "UCMS22"."TB_ATTRB_INFO"."ATTRB_DC" IS '속성설명';
 
   COMMENT ON TABLE "UCMS22"."TB_ATTRB_INFO"  IS '속성정보';
--------------------------------------------------------
--  DDL for Table TB_BBS_CM
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TB_BBS_CM" 
   (	"CM_ID" NUMBER(10,0), 
	"NTT_ID" NUMBER(10,0), 
	"NTT_SJ" VARCHAR2(1024 BYTE), 
	"NTT_CN" CLOB, 
	"BBS_ID" VARCHAR2(16 BYTE), 
	"NTCR_ID" VARCHAR2(64 BYTE), 
	"NTCR_NM" VARCHAR2(128 BYTE), 
	"PASSWORD" VARCHAR2(256 BYTE), 
	"NTCR_EMAD" VARCHAR2(512 BYTE), 
	"RECOMMEND_CO" NUMBER(10,0), 
	"CM_SE" VARCHAR2(64 BYTE), 
	"USER_SN" NUMBER(10,0), 
	"OPTN1" VARCHAR2(4000 BYTE), 
	"OPTN2" VARCHAR2(4000 BYTE), 
	"OPTN3" VARCHAR2(4000 BYTE), 
	"OPTN4" VARCHAR2(4000 BYTE), 
	"OPTN5" VARCHAR2(4000 BYTE), 
	"OPTN6" VARCHAR2(4000 BYTE), 
	"OPTN7" VARCHAR2(4000 BYTE), 
	"OPTN8" VARCHAR2(4000 BYTE), 
	"OPTN9" VARCHAR2(4000 BYTE), 
	"OPTN10" VARCHAR2(4000 BYTE), 
	"EXPSR_AT" CHAR(1 BYTE), 
	"DELETE_CD" CHAR(1 BYTE), 
	"USE_AT" CHAR(1 BYTE), 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("NTT_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."CM_ID" IS '코멘트ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."NTT_ID" IS '게시물ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."NTT_SJ" IS '게시물제목';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."NTT_CN" IS '게시글내용';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."NTCR_ID" IS '게시자ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."NTCR_NM" IS '게시자명';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."PASSWORD" IS '비밀번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."NTCR_EMAD" IS '게시자이메일주소';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."RECOMMEND_CO" IS '추천수';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."CM_SE" IS '코멘트구분';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."USER_SN" IS '사용자일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN1" IS '옵션1';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN2" IS '옵션2';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN3" IS '옵션3';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN4" IS '옵션4';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN5" IS '옵션5';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN6" IS '옵션6';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN7" IS '옵션7';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN8" IS '옵션8';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN9" IS '옵션9';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."OPTN10" IS '옵션10';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."EXPSR_AT" IS '노출여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."DELETE_CD" IS '삭제코드(0:보임,1:사용자삭제,2:관리자삭제)';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_CM"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TB_BBS_CM"  IS '게시판코멘트';
--------------------------------------------------------
--  DDL for Table TB_BBS_ESTN
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TB_BBS_ESTN" 
   (	"NTT_ID" NUMBER(10,0), 
	"BBS_ID" VARCHAR2(16 BYTE), 
	"SORT_ORDR" NUMBER(10,0), 
	"NTT_SJ" VARCHAR2(1024 BYTE), 
	"NTT_CN" CLOB, 
	"NTCR_ID" VARCHAR2(64 BYTE), 
	"NTCR_NM" VARCHAR2(128 BYTE), 
	"NTCR_EMAD" VARCHAR2(512 BYTE), 
	"NTCR_ZIP" VARCHAR2(7 BYTE), 
	"NTCR_ADRES1" VARCHAR2(256 BYTE), 
	"NTCR_ADRES2" VARCHAR2(512 BYTE), 
	"NTCR_TELNO" VARCHAR2(32 BYTE), 
	"NTCR_CPNO" VARCHAR2(32 BYTE), 
	"NTCR_PIN" VARCHAR2(128 BYTE), 
	"PASSWORD" VARCHAR2(256 BYTE), 
	"INQIRE_CO" NUMBER(10,0), 
	"NTCE_BGNDE" VARCHAR2(10 BYTE), 
	"NTCE_ENDDE" VARCHAR2(10 BYTE), 
	"ANSWER_AT" CHAR(1 BYTE), 
	"PARNTS_NO" NUMBER(10,0), 
	"NTT_NO" NUMBER(10,0), 
	"ANSWER_LC" NUMBER(10,0), 
	"SECRET_AT" CHAR(1 BYTE), 
	"NTT_TY_CD" VARCHAR2(16 BYTE), 
	"USER_SN" NUMBER(10,0), 
	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"DEPT_ID" VARCHAR2(16 BYTE), 
	"DEPT_NM" VARCHAR2(256 BYTE), 
	"HTML_AT" CHAR(1 BYTE) DEFAULT 'N', 
	"BBS_SE_CD" VARCHAR2(16 BYTE), 
	"IMAGE_REPLC_TEXT_CN" CLOB, 
	"SITE_ID" VARCHAR2(32 BYTE), 
	"OPTN1" VARCHAR2(4000 BYTE), 
	"OPTN2" VARCHAR2(4000 BYTE), 
	"OPTN3" VARCHAR2(4000 BYTE), 
	"OPTN4" VARCHAR2(4000 BYTE), 
	"OPTN5" VARCHAR2(4000 BYTE), 
	"OPTN6" VARCHAR2(4000 BYTE), 
	"OPTN7" VARCHAR2(4000 BYTE), 
	"OPTN8" VARCHAR2(4000 BYTE), 
	"OPTN9" VARCHAR2(4000 BYTE), 
	"OPTN10" VARCHAR2(4000 BYTE), 
	"OPTN11" VARCHAR2(4000 BYTE), 
	"OPTN12" VARCHAR2(4000 BYTE), 
	"OPTN13" VARCHAR2(4000 BYTE), 
	"OPTN14" VARCHAR2(4000 BYTE), 
	"OPTN15" VARCHAR2(4000 BYTE), 
	"OPTN16" VARCHAR2(4000 BYTE), 
	"OPTN17" VARCHAR2(4000 BYTE), 
	"OPTN18" VARCHAR2(4000 BYTE), 
	"OPTN19" VARCHAR2(4000 BYTE), 
	"OPTN20" VARCHAR2(4000 BYTE), 
	"DELETE_CD" CHAR(1 BYTE) DEFAULT '0', 
	"USE_AT" CHAR(1 BYTE), 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE DEFAULT SYSDATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("NTT_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMAGE_REPLC_TEXT_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTT_ID" IS '게시물ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."SORT_ORDR" IS '정렬순서';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTT_SJ" IS '게시물제목';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTT_CN" IS '게시글내용';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_ID" IS '게시자ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_NM" IS '게시자명';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_EMAD" IS '게시자이메일주소';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_ZIP" IS '게시자우편번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_ADRES1" IS '게시자주소1';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_ADRES2" IS '게시자주소2';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_TELNO" IS '게시자전화번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_CPNO" IS '게시자휴대전화번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCR_PIN" IS '게시자개인식별번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."PASSWORD" IS '비밀번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."INQIRE_CO" IS '조회횟수';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCE_BGNDE" IS '게시시작일';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTCE_ENDDE" IS '게시종료일';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."ANSWER_AT" IS '답글여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."PARNTS_NO" IS '부모글번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTT_NO" IS '게시물번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."ANSWER_LC" IS '답글위치';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."SECRET_AT" IS '비밀여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."NTT_TY_CD" IS '게시글유형코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."USER_SN" IS '사용자일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."DEPT_ID" IS '부서ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."DEPT_NM" IS '부서명';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."HTML_AT" IS 'HTML여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."BBS_SE_CD" IS '게시판구분코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."IMAGE_REPLC_TEXT_CN" IS '이미지대체텍스트내용';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN1" IS '옵션1';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN2" IS '옵션2';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN3" IS '옵션3';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN4" IS '옵션4';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN5" IS '옵션5';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN6" IS '옵션6';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN7" IS '옵션7';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN8" IS '옵션8';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN9" IS '옵션9';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN10" IS '옵션10';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN11" IS '옵션11';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN12" IS '옵션12';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN13" IS '옵션13';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN14" IS '옵션14';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN15" IS '옵션15';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN16" IS '옵션16';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN17" IS '옵션17';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN18" IS '옵션18';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN19" IS '옵션19';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."OPTN20" IS '옵션20';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."DELETE_CD" IS '삭제코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_ESTN"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TB_BBS_ESTN"  IS '게시판확장';
--------------------------------------------------------
--  DDL for Table TB_BBS_MASTR
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TB_BBS_MASTR" 
   (	"BBS_ID" VARCHAR2(16 BYTE), 
	"BBS_TY_CD" VARCHAR2(16 BYTE), 
	"BBS_ATTRB_CD" VARCHAR2(16 BYTE), 
	"BBS_NM" VARCHAR2(512 BYTE), 
	"BBS_DC" VARCHAR2(4000 BYTE), 
	"REPLY_POSBL_AT" CHAR(1 BYTE), 
	"FILE_ATCH_POSBL_AT" CHAR(1 BYTE), 
	"ATCH_POSBL_FILE_CO" NUMBER(10,0), 
	"ATCH_POSBL_FILE_SIZE" VARCHAR2(32 BYTE), 
	"NTCE_BGNDE" VARCHAR2(10 BYTE), 
	"NTCE_ENDDE" VARCHAR2(10 BYTE), 
	"TMPLAT_ID" CHAR(20 BYTE), 
	"CM_POSBL_AT" CHAR(1 BYTE), 
	"ADIT_CNTNTS_CN" CLOB, 
	"PAGE_SIZE" NUMBER(10,0), 
	"PAGE_UNIT" NUMBER(10,0), 
	"PREV_NEXT_POSBL_AT" CHAR(1 BYTE), 
	"TABLE_NM" VARCHAR2(256 BYTE), 
	"DELETE_CD" CHAR(1 BYTE) DEFAULT '0', 
	"USE_AT" CHAR(1 BYTE), 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE DEFAULT SYSDATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("ADIT_CNTNTS_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."BBS_TY_CD" IS '게시판유형코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."BBS_ATTRB_CD" IS '게시판속성코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."BBS_NM" IS '게시판명';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."BBS_DC" IS '게시판설명';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."REPLY_POSBL_AT" IS '답글가능여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."FILE_ATCH_POSBL_AT" IS '파일첨부가능여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."ATCH_POSBL_FILE_CO" IS '첨부가능파일건수';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."ATCH_POSBL_FILE_SIZE" IS '첨부가능파일사이즈';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."NTCE_BGNDE" IS '게시시작일';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."NTCE_ENDDE" IS '게시종료일';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."TMPLAT_ID" IS '템플릿ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."CM_POSBL_AT" IS '코멘트가능여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."ADIT_CNTNTS_CN" IS '추가컨텐츠내용';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."PAGE_SIZE" IS '페이지사이즈';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."PAGE_UNIT" IS '페이지단위';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."PREV_NEXT_POSBL_AT" IS '이전글다음글사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."TABLE_NM" IS '테이블명';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."DELETE_CD" IS '삭제코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."USE_AT" IS '사용여부(Y:사용,N:미사용)';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_BBS_MASTR"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TB_BBS_MASTR"  IS '게시판마스터';
--------------------------------------------------------
--  DDL for Table TB_FIELD_INFO
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TB_FIELD_INFO" 
   (	"FIELD_ID" NUMBER(10,0), 
	"ATTRB_CD" VARCHAR2(16 BYTE), 
	"ATTRB_TY_CD" VARCHAR2(16 BYTE), 
	"FIELD_IEM_NM" VARCHAR2(256 BYTE), 
	"FIELD_TY_CD" VARCHAR2(16 BYTE), 
	"FIELD_DC" VARCHAR2(4000 BYTE), 
	"FIELD_ORDR" NUMBER(10,0) DEFAULT NULL, 
	"LIST_USE_AT" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TB_FIELD_INFO"."FIELD_ID" IS '필드ID';
 
   COMMENT ON COLUMN "UCMS22"."TB_FIELD_INFO"."ATTRB_CD" IS '속성코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_FIELD_INFO"."ATTRB_TY_CD" IS '속성유형코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_FIELD_INFO"."FIELD_IEM_NM" IS '필드항목명';
 
   COMMENT ON COLUMN "UCMS22"."TB_FIELD_INFO"."FIELD_TY_CD" IS '필드유형코드';
 
   COMMENT ON COLUMN "UCMS22"."TB_FIELD_INFO"."FIELD_DC" IS '필드설명';
 
   COMMENT ON COLUMN "UCMS22"."TB_FIELD_INFO"."FIELD_ORDR" IS '필드순서';
 
   COMMENT ON COLUMN "UCMS22"."TB_FIELD_INFO"."LIST_USE_AT" IS '리스트사용여부';
 
   COMMENT ON TABLE "UCMS22"."TB_FIELD_INFO"  IS '게시판 필드정보';
--------------------------------------------------------
--  DDL for Table TC_AUTHOR_INFO
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_AUTHOR_INFO" 
   (	"AUTHOR_CD" VARCHAR2(32 BYTE), 
	"AUTHOR_NM" VARCHAR2(256 BYTE), 
	"AUTHOR_DC" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"REGIST_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_AUTHOR_INFO"."AUTHOR_CD" IS '권한코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_AUTHOR_INFO"."AUTHOR_NM" IS '권한명';
 
   COMMENT ON COLUMN "UCMS22"."TC_AUTHOR_INFO"."AUTHOR_DC" IS '권한설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_AUTHOR_INFO"."REGIST_DT" IS '등록일시';
 
   COMMENT ON TABLE "UCMS22"."TC_AUTHOR_INFO"  IS '권한정보';
--------------------------------------------------------
--  DDL for Table TC_AUTHOR_SCLSRT
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_AUTHOR_SCLSRT" 
   (	"PARNTS_AUTHOR_CD" VARCHAR2(32 BYTE), 
	"CHLDRN_AUTHOR_CD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_AUTHOR_SCLSRT"."PARNTS_AUTHOR_CD" IS '부모권한';
 
   COMMENT ON COLUMN "UCMS22"."TC_AUTHOR_SCLSRT"."CHLDRN_AUTHOR_CD" IS '자식권한';
 
   COMMENT ON TABLE "UCMS22"."TC_AUTHOR_SCLSRT"  IS '권한계층';
--------------------------------------------------------
--  DDL for Table TC_BANNER
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_BANNER" 
   (	"BANNER_NO" NUMBER(10,0), 
	"BANNER_NM" VARCHAR2(256 BYTE), 
	"BANNER_URLAD" VARCHAR2(512 BYTE), 
	"BANNER_SE" VARCHAR2(16 BYTE), 
	"DONG_CD" VARCHAR2(16 BYTE), 
	"SORT_ORDR" NUMBER(10,0), 
	"EXPSR_AT" CHAR(1 BYTE), 
	"POPUP_AT" CHAR(1 BYTE) DEFAULT 'N', 
	"DEPT_ID" VARCHAR2(16 BYTE), 
	"SITE_ID_SE" VARCHAR2(512 BYTE), 
	"SITE_ID" VARCHAR2(32 BYTE), 
	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"BGNDE" DATE DEFAULT SYSDATE, 
	"ENDDE" DATE DEFAULT SYSDATE, 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."BANNER_NO" IS '배너번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."BANNER_NM" IS '배너명';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."BANNER_URLAD" IS '배너URL주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."BANNER_SE" IS '배너구분';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."DONG_CD" IS '동코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."SORT_ORDR" IS '정렬순서';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."EXPSR_AT" IS '노출여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."POPUP_AT" IS '팝업여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."DEPT_ID" IS '부서ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."SITE_ID_SE" IS '사이트ID구분';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."BGNDE" IS '시작일';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."ENDDE" IS '종료일';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_BANNER"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_BANNER"  IS '배너';
--------------------------------------------------------
--  DDL for Table TC_CMMN_CD_CL
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CMMN_CD_CL" 
   (	"CL_CD" VARCHAR2(16 BYTE), 
	"CL_CD_NM" VARCHAR2(256 BYTE), 
	"CL_CD_DC" VARCHAR2(4000 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CL"."CL_CD" IS '분류코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CL"."CL_CD_NM" IS '분류코드명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CL"."CL_CD_DC" IS '분류코드설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CL"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CL"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CL"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CL"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CL"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_CMMN_CD_CL"  IS '공통코드분류';
--------------------------------------------------------
--  DDL for Table TC_CMMN_CD_CTGRY
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CMMN_CD_CTGRY" 
   (	"CD_ID" VARCHAR2(16 BYTE), 
	"CL_CD" VARCHAR2(16 BYTE), 
	"CD_ID_NM" VARCHAR2(256 BYTE), 
	"CD_ID_ENG_NM" VARCHAR2(256 BYTE), 
	"CD_ID_DC" VARCHAR2(4000 BYTE), 
	"CD_ID_ENG_DC" VARCHAR2(4000 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."CD_ID" IS '코드ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."CL_CD" IS '분류코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."CD_ID_NM" IS '코드ID명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."CD_ID_ENG_NM" IS '코드ID영문명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."CD_ID_DC" IS '코드ID설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."CD_ID_ENG_DC" IS '코드ID영문설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_CTGRY"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_CMMN_CD_CTGRY"  IS '공통코드카테고리';
--------------------------------------------------------
--  DDL for Table TC_CMMN_CD_DETAIL
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CMMN_CD_DETAIL" 
   (	"CD" VARCHAR2(16 BYTE), 
	"CD_ID" VARCHAR2(16 BYTE), 
	"CD_NM" VARCHAR2(256 BYTE), 
	"CD_ENG_NM" VARCHAR2(256 BYTE), 
	"CD_DC" VARCHAR2(4000 BYTE), 
	"CD_ENG_DC" VARCHAR2(4000 BYTE), 
	"UPPER_CD" VARCHAR2(16 BYTE) DEFAULT '0', 
	"DP" NUMBER(10,0) DEFAULT 1, 
	"SORT_ORDR" NUMBER(10,0) DEFAULT 0, 
	"OPTN1" VARCHAR2(4000 BYTE), 
	"OPTN2" VARCHAR2(4000 BYTE), 
	"OPTN3" VARCHAR2(4000 BYTE), 
	"OPTN4" VARCHAR2(4000 BYTE), 
	"OPTN5" VARCHAR2(4000 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."CD" IS '코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."CD_ID" IS '코드ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."CD_NM" IS '코드명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."CD_ENG_NM" IS '코드영문명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."CD_DC" IS '코드설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."CD_ENG_DC" IS '코드영문설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."UPPER_CD" IS '상위코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."DP" IS '깊이';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."SORT_ORDR" IS '정렬순서';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."OPTN1" IS '옵션1';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."OPTN2" IS '옵션2';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."OPTN3" IS '옵션3';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."OPTN4" IS '옵션4';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."OPTN5" IS '옵션5';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_DETAIL"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_CMMN_CD_DETAIL"  IS '공통코드상세';
--------------------------------------------------------
--  DDL for Table TC_CMMN_CD_MULTI
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CMMN_CD_MULTI" 
   (	"CD_ID" VARCHAR2(16 BYTE), 
	"PROGRM_ID" VARCHAR2(32 BYTE), 
	"PROGRM_SN" NUMBER(10,0), 
	"CD" VARCHAR2(16 BYTE), 
	"REGIST_DT" DATE, 
	"MEMO" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_MULTI"."CD_ID" IS '코드ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_MULTI"."PROGRM_ID" IS '프로그램ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_MULTI"."PROGRM_SN" IS '프로그램일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_MULTI"."CD" IS '코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_MULTI"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_CD_MULTI"."MEMO" IS '메모';
 
   COMMENT ON TABLE "UCMS22"."TC_CMMN_CD_MULTI"  IS '공통코드다중';
--------------------------------------------------------
--  DDL for Table TC_CMMN_FILE
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CMMN_FILE" 
   (	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"REGIST_DT" DATE, 
	"USE_AT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE"."USE_AT" IS '사용여부';
 
   COMMENT ON TABLE "UCMS22"."TC_CMMN_FILE"  IS '공통파일';
--------------------------------------------------------
--  DDL for Table TC_CMMN_FILE_DETAIL
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CMMN_FILE_DETAIL" 
   (	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"FILE_SN" NUMBER(10,0), 
	"FILE_STRE_COURS" VARCHAR2(512 BYTE), 
	"STRE_FILE_NM" VARCHAR2(256 BYTE), 
	"ORIGNL_FILE_NM" VARCHAR2(256 BYTE) DEFAULT NULL, 
	"FILE_EXTSN_NM" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"FILE_SIZE" NUMBER(10,0) DEFAULT NULL, 
	"FILE_CN" CLOB, 
	"FILE_FIELD_NM" VARCHAR2(256 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("FILE_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."FILE_SN" IS '파일일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."FILE_STRE_COURS" IS '파일저장경로';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."STRE_FILE_NM" IS '저장파일명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."ORIGNL_FILE_NM" IS '원파일명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."FILE_EXTSN_NM" IS '파일확장자명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."FILE_SIZE" IS '파일사이즈';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."FILE_CN" IS '파일내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DETAIL"."FILE_FIELD_NM" IS '파일필드명';
 
   COMMENT ON TABLE "UCMS22"."TC_CMMN_FILE_DETAIL"  IS '공통파일상세';
--------------------------------------------------------
--  DDL for Table TC_CMMN_FILE_DWLD_HIST
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CMMN_FILE_DWLD_HIST" 
   (	"MNNO" NUMBER(22,0), 
	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"FILE_SN" NUMBER(10,0), 
	"MENU_NO" NUMBER(10,0), 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"SITE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DWLD_HIST"."MNNO" IS '관리번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DWLD_HIST"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DWLD_HIST"."FILE_SN" IS '파일일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DWLD_HIST"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DWLD_HIST"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DWLD_HIST"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_FILE_DWLD_HIST"."SITE_ID" IS '사이트ID';
 
   COMMENT ON TABLE "UCMS22"."TC_CMMN_FILE_DWLD_HIST"  IS '공통파일다운로드이력';
--------------------------------------------------------
--  DDL for Table TC_CMMN_SN
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CMMN_SN" 
   (	"TABLE_NM" VARCHAR2(256 BYTE), 
	"NEXT_SN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CMMN_SN"."TABLE_NM" IS '테이블명';
 
   COMMENT ON COLUMN "UCMS22"."TC_CMMN_SN"."NEXT_SN" IS '다음일련번호';
 
   COMMENT ON TABLE "UCMS22"."TC_CMMN_SN"  IS '공통일련번호';
--------------------------------------------------------
--  DDL for Table TC_CNTNTS_MANAGE
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_CNTNTS_MANAGE" 
   (	"MENU_NO" NUMBER(10,0), 
	"CNTNTS_MNNO" NUMBER(10,0), 
	"CNTNTS_CN" CLOB, 
	"DELETE_CD" CHAR(1 BYTE) DEFAULT '0', 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE DEFAULT SYSDATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("CNTNTS_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."CNTNTS_MNNO" IS '컨텐츠관리번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."CNTNTS_CN" IS '콘텐츠내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."DELETE_CD" IS '삭제코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_CNTNTS_MANAGE"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_CNTNTS_MANAGE"  IS '콘텐츠관리';
--------------------------------------------------------
--  DDL for Table TC_GLOBAL
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_GLOBAL" 
   (	"ATTRB_SN" NUMBER(10,0), 
	"ATTRB_NM" VARCHAR2(256 BYTE), 
	"ATTRB_VALUE" VARCHAR2(128 BYTE), 
	"ATTRB_DC" VARCHAR2(4000 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."ATTRB_SN" IS '속성일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."ATTRB_NM" IS '속성명';
 
   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."ATTRB_VALUE" IS '속성값';
 
   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."ATTRB_DC" IS '속성설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_GLOBAL"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_GLOBAL"  IS '글로벌:글로벌 변수설정하고 관리한다.';
--------------------------------------------------------
--  DDL for Table TC_MENU_AUTHOR
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_MENU_AUTHOR" 
   (	"MENU_NO" NUMBER(10,0), 
	"AUTHOR_CD" VARCHAR2(32 BYTE), 
	"MAP_CREAT_ID" VARCHAR2(16 BYTE), 
	"REGIST_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_MENU_AUTHOR"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_AUTHOR"."AUTHOR_CD" IS '권한코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_AUTHOR"."MAP_CREAT_ID" IS '맵생성ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_AUTHOR"."REGIST_DT" IS '등록일시';
 
   COMMENT ON TABLE "UCMS22"."TC_MENU_AUTHOR"  IS '메뉴권한';
--------------------------------------------------------
--  DDL for Table TC_MENU_INFO
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_MENU_INFO" 
   (	"MENU_NO" NUMBER(10,0), 
	"MENU_NM" VARCHAR2(256 BYTE), 
	"UPPER_MENU_NO" NUMBER(10,0), 
	"MENU_ORDR" NUMBER(10,0), 
	"MENU_DC" VARCHAR2(4000 BYTE), 
	"MENU_CNTNTS_CD" VARCHAR2(16 BYTE), 
	"MENU_LINK" VARCHAR2(512 BYTE), 
	"POPUP_AT" CHAR(1 BYTE), 
	"SITE_ID" VARCHAR2(32 BYTE), 
	"DEPT_ID" VARCHAR2(16 BYTE), 
	"USER_ID" VARCHAR2(64 BYTE), 
	"RELATE_MENU_NM_LIST" VARCHAR2(4000 BYTE), 
	"RELATE_MENU_LINK_LIST" VARCHAR2(4000 BYTE), 
	"ALL_MENU_COURS" VARCHAR2(4000 BYTE), 
	"CNTNTS_FILE_COURS" VARCHAR2(512 BYTE), 
	"MENU_LC" VARCHAR2(4000 BYTE), 
	"BBS_ID" VARCHAR2(16 BYTE), 
	"LEAF_NODE_AT" CHAR(1 BYTE), 
	"KWRD_NM" VARCHAR2(1024 BYTE), 
	"ADI_INFO" VARCHAR2(4000 BYTE), 
	"MENU_EXPSR_SE" VARCHAR2(10 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"DELETE_CD" CHAR(1 BYTE) DEFAULT '0', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."MENU_NM" IS '메뉴명';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."UPPER_MENU_NO" IS '상위메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."MENU_ORDR" IS '메뉴순서';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."MENU_DC" IS '메뉴설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."MENU_CNTNTS_CD" IS '메뉴콘텐츠코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."MENU_LINK" IS '메뉴링크';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."POPUP_AT" IS '팝업여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."DEPT_ID" IS '부서ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."USER_ID" IS '사용자ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."RELATE_MENU_NM_LIST" IS '관련메뉴명목록';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."RELATE_MENU_LINK_LIST" IS '관련메뉴링크목록';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."ALL_MENU_COURS" IS '전체메뉴경로';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."CNTNTS_FILE_COURS" IS '콘텐츠파일경로';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."MENU_LC" IS '메뉴위치';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."LEAF_NODE_AT" IS '최종하위메뉴유무';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."KWRD_NM" IS '키워드명';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."ADI_INFO" IS '부가정보';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."MENU_EXPSR_SE" IS '메뉴노출구분';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."DELETE_CD" IS '삭제코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MENU_INFO"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_MENU_INFO"  IS '메뉴정보';
--------------------------------------------------------
--  DDL for Table TC_MNGR_MAIN_ESTBS
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_MNGR_MAIN_ESTBS" 
   (	"MNNO" NUMBER(10,0), 
	"SE_CD" VARCHAR2(16 BYTE), 
	"BASS_MG" VARCHAR2(16 BYTE), 
	"ESTBS_CN" CLOB, 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE, 
	"USER_ID" VARCHAR2(64 BYTE), 
	"AR_MVL" NUMBER(10,0), 
	"AR_MNVL" NUMBER(10,0), 
	"HG_MVL" NUMBER(10,0), 
	"HG_MNVL" NUMBER(10,0), 
	"SIZE_UPDT_AT" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("ESTBS_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."MNNO" IS '관리번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."SE_CD" IS '설정구분코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."BASS_MG" IS '기본크기';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."ESTBS_CN" IS '설정내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."UPDT_DT" IS '수정일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."USER_ID" IS '사용자ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."AR_MVL" IS '넓이최대치';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."AR_MNVL" IS '넓이최소치';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."HG_MVL" IS '높이최대치';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."HG_MNVL" IS '높이최소치';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS"."SIZE_UPDT_AT" IS '사이즈변경여부';
 
   COMMENT ON TABLE "UCMS22"."TC_MNGR_MAIN_ESTBS"  IS '관리자메인설정';
--------------------------------------------------------
--  DDL for Table TC_MNGR_MAIN_ESTBS_DETAIL
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL" 
   (	"MNNO" NUMBER(10,0), 
	"SN" NUMBER(10,0), 
	"ESTBS_NM" VARCHAR2(512 BYTE), 
	"BBS_ID" VARCHAR2(16 BYTE), 
	"URLAD" VARCHAR2(512 BYTE), 
	"POPUP_AT" CHAR(1 BYTE), 
	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"FILE_FIELD_NM" VARCHAR2(256 BYTE), 
	"FIELD_ORDR" NUMBER(10,0), 
	"ICON_NM" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."MNNO" IS '관리번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."SN" IS '일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."ESTBS_NM" IS '설정명';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."URLAD" IS 'URL주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."POPUP_AT" IS '팝업여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."FILE_FIELD_NM" IS '파일필드명';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."FIELD_ORDR" IS '필드순서';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"."ICON_NM" IS '아이콘명';
 
   COMMENT ON TABLE "UCMS22"."TC_MNGR_MAIN_ESTBS_DETAIL"  IS '관리자메인설정상세';
--------------------------------------------------------
--  DDL for Table TC_MNGR_MAIN_LC_ESTBS
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_MNGR_MAIN_LC_ESTBS" 
   (	"SN" NUMBER(10,0), 
	"MNNO" NUMBER(10,0), 
	"LFT_CRDNT" NUMBER(10,0), 
	"UPEND_CRDNT" NUMBER(10,0), 
	"AR_VALUE" NUMBER(10,0), 
	"HG_VALUE" NUMBER(10,0), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"USER_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."SN" IS '일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."MNNO" IS '관리번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."LFT_CRDNT" IS '좌측좌표';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."UPEND_CRDNT" IS '탑좌표';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."AR_VALUE" IS '넓이값';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."HG_VALUE" IS '높이값';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."USER_ID" IS '사용자ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"."UPDT_DT" IS '수정일';
 
   COMMENT ON TABLE "UCMS22"."TC_MNGR_MAIN_LC_ESTBS"  IS '관리자메인위치설정';
--------------------------------------------------------
--  DDL for Table TC_NTCN_RELM
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_NTCN_RELM" 
   (	"NTCN_NO" NUMBER(10,0), 
	"NTCN_NM" VARCHAR2(256 BYTE), 
	"NTCN_URLAD" VARCHAR2(512 BYTE), 
	"NTCN_CN" CLOB, 
	"NTCN_TY_CD" VARCHAR2(16 BYTE), 
	"SORT_ORDR" NUMBER(10,0), 
	"POPUP_AT" CHAR(1 BYTE), 
	"MAP_USE_AT" CHAR(1 BYTE), 
	"DEPT_ID" VARCHAR2(16 BYTE), 
	"SITE_ID_SE" VARCHAR2(512 BYTE), 
	"SITE_ID" VARCHAR2(32 BYTE), 
	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"BGNDE" DATE DEFAULT SYSDATE, 
	"ENDDE" DATE DEFAULT SYSDATE, 
	"LINK_SE" CHAR(1 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("NTCN_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."NTCN_NO" IS '알림번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."NTCN_NM" IS '알림명';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."NTCN_URLAD" IS '알림URL주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."NTCN_CN" IS '알림내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."NTCN_TY_CD" IS '알림유형코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."SORT_ORDR" IS '정렬순서';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."POPUP_AT" IS '팝업여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."MAP_USE_AT" IS '맵사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."DEPT_ID" IS '부서ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."SITE_ID_SE" IS '사이트ID구분';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."BGNDE" IS '시작일';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."ENDDE" IS '종료일';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."LINK_SE" IS '링크구분';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_NTCN_RELM"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_NTCN_RELM"  IS '알림영역';
--------------------------------------------------------
--  DDL for Table TC_POPUP_MANAGE
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_POPUP_MANAGE" 
   (	"POPUP_NO" NUMBER(10,0), 
	"POPUP_SJ" VARCHAR2(1024 BYTE), 
	"POPUP_CN" CLOB, 
	"BGNDE" DATE DEFAULT SYSDATE, 
	"ENDDE" DATE DEFAULT SYSDATE, 
	"AR_VALUE" NUMBER(10,0), 
	"HG_VALUE" NUMBER(10,0), 
	"LFT_CRDNT" NUMBER(10,0), 
	"UPEND_CRDNT" NUMBER(10,0), 
	"CLOSE_USE_AT" CHAR(1 BYTE), 
	"SITE_ID_SE" VARCHAR2(512 BYTE), 
	"SITE_ID" VARCHAR2(32 BYTE), 
	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"URLAD" VARCHAR2(512 BYTE), 
	"SCRL_USE_AT" CHAR(1 BYTE), 
	"LINK_TY_CD" VARCHAR2(16 BYTE), 
	"MAP_CN" VARCHAR2(4000 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("POPUP_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."POPUP_NO" IS '팝업번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."POPUP_SJ" IS '팝업제목';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."POPUP_CN" IS '팝업내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."BGNDE" IS '시작일';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."ENDDE" IS '종료일';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."AR_VALUE" IS '넓이값';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."HG_VALUE" IS '높이값';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."LFT_CRDNT" IS '좌측좌표';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."UPEND_CRDNT" IS '탑좌표';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."CLOSE_USE_AT" IS '닫기사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."SITE_ID_SE" IS '사이트ID구분';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."URLAD" IS '링크주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."SCRL_USE_AT" IS '스크롤사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."LINK_TY_CD" IS '링크타입코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."MAP_CN" IS '맵내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_POPUP_MANAGE"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_POPUP_MANAGE"  IS '팝업관리';
--------------------------------------------------------
--  DDL for Table TC_PRHIBT_WRD_FLTER
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_PRHIBT_WRD_FLTER" 
   (	"WRD_SN" NUMBER(10,0), 
	"WRD_NM" VARCHAR2(256 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_PRHIBT_WRD_FLTER"."WRD_SN" IS '단어일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_PRHIBT_WRD_FLTER"."WRD_NM" IS '단어명';
 
   COMMENT ON COLUMN "UCMS22"."TC_PRHIBT_WRD_FLTER"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_PRHIBT_WRD_FLTER"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_PRHIBT_WRD_FLTER"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_PRHIBT_WRD_FLTER"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_PRHIBT_WRD_FLTER"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_PRHIBT_WRD_FLTER"  IS '금지단어필터';
--------------------------------------------------------
--  DDL for Table TC_QUSTNR
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_QUSTNR" 
   (	"QUSTNR_SN" NUMBER(10,0), 
	"QUSTNR_SJ" VARCHAR2(1024 BYTE), 
	"BGNDE" DATE, 
	"ENDDE" DATE, 
	"STTUS_CD" VARCHAR2(16 BYTE), 
	"TRGET_CD" VARCHAR2(16 BYTE), 
	"RESULT_OTHBC_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"DEPT_ID" VARCHAR2(16 BYTE), 
	"TELNO" VARCHAR2(32 BYTE), 
	"QESTNAR_CN" CLOB, 
	"DELETE_CD" CHAR(1 BYTE) DEFAULT '0', 
	"REGIST_DT" DATE DEFAULT SYSDATE, 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE DEFAULT SYSDATE, 
	"UPDT_ID" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("QESTNAR_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."QUSTNR_SN" IS '설문일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."QUSTNR_SJ" IS '설문제목';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."BGNDE" IS '시작일';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."ENDDE" IS '종료일';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."STTUS_CD" IS '상태코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."TRGET_CD" IS '대상코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."RESULT_OTHBC_AT" IS '결과보기공개여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."DEPT_ID" IS '부서ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."TELNO" IS '전화번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."QESTNAR_CN" IS '설문조사내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."DELETE_CD" IS '삭제코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."UPDT_DT" IS '수정일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR"."UPDT_ID" IS '수정ID';
 
   COMMENT ON TABLE "UCMS22"."TC_QUSTNR"  IS '설문조사';
--------------------------------------------------------
--  DDL for Table TC_QUSTNR_ANSWER
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_QUSTNR_ANSWER" 
   (	"ANSWER_SN" NUMBER(10,0), 
	"QESITM_SN" NUMBER(10,0), 
	"ANSWER_CN" VARCHAR2(4000 BYTE), 
	"SORT_ORDR" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_ANSWER"."ANSWER_SN" IS '답변일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_ANSWER"."QESITM_SN" IS '문항일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_ANSWER"."ANSWER_CN" IS '답변내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_ANSWER"."SORT_ORDR" IS '정렬순서';
 
   COMMENT ON TABLE "UCMS22"."TC_QUSTNR_ANSWER"  IS '설문답변';
--------------------------------------------------------
--  DDL for Table TC_QUSTNR_QESITM
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_QUSTNR_QESITM" 
   (	"QESITM_SN" NUMBER(10,0), 
	"QUSTNR_SN" NUMBER(10,0), 
	"QESITM_TY_CD" CHAR(1 BYTE), 
	"QESITM_SJ" VARCHAR2(1024 BYTE), 
	"ESSNTL_ANSWER_AT" CHAR(1 BYTE) DEFAULT 'N', 
	"ESSNTL_CHOISE_QY" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_QESITM"."QESITM_SN" IS '문항일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_QESITM"."QUSTNR_SN" IS '설문일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_QESITM"."QESITM_TY_CD" IS '문항유형코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_QESITM"."QESITM_SJ" IS '문항제목';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_QESITM"."ESSNTL_ANSWER_AT" IS '필수답변여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_QESITM"."ESSNTL_CHOISE_QY" IS '필수선택건수';
 
   COMMENT ON TABLE "UCMS22"."TC_QUSTNR_QESITM"  IS '설문항목';
--------------------------------------------------------
--  DDL for Table TC_QUSTNR_USER_ANSWER
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_QUSTNR_USER_ANSWER" 
   (	"USER_ANSWER_SN" NUMBER(10,0), 
	"QESITM_SN" NUMBER(10,0), 
	"ANSWER_SN" NUMBER(10,0), 
	"USER_SN" NUMBER(10,0), 
	"USER_ID" VARCHAR2(64 BYTE), 
	"ANSWER_CN" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_USER_ANSWER"."USER_ANSWER_SN" IS '사용자답변일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_USER_ANSWER"."QESITM_SN" IS '문항일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_USER_ANSWER"."ANSWER_SN" IS '답변일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_USER_ANSWER"."USER_SN" IS '사용자일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_USER_ANSWER"."USER_ID" IS '사용자ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_QUSTNR_USER_ANSWER"."ANSWER_CN" IS '답변내용';
 
   COMMENT ON TABLE "UCMS22"."TC_QUSTNR_USER_ANSWER"  IS '설문사용자답변';
--------------------------------------------------------
--  DDL for Table TC_SITE_CONECT_STATS
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_SITE_CONECT_STATS" 
   (	"CONECT_SN" NUMBER(22,0), 
	"SESION_ID" VARCHAR2(256 BYTE), 
	"SITE_ID" VARCHAR2(32 BYTE), 
	"CONECT_URLAD" VARCHAR2(512 BYTE), 
	"MENU_NO" NUMBER(10,0), 
	"CONECT_OPERSYSM_NM" VARCHAR2(256 BYTE), 
	"CONECT_WBSR_NM" VARCHAR2(256 BYTE), 
	"CONECT_PC_MOBILE_SE" VARCHAR2(64 BYTE), 
	"CONECT_YM" CHAR(6 BYTE), 
	"CONECT_DE" CHAR(8 BYTE), 
	"REGIST_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."CONECT_SN" IS '접속일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."SESION_ID" IS '세션ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."CONECT_URLAD" IS '접속URL주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."CONECT_OPERSYSM_NM" IS '접속운영체제명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."CONECT_WBSR_NM" IS '접속브라우저명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."CONECT_PC_MOBILE_SE" IS '접속PC모바일구분';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."CONECT_YM" IS '접속년월';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."CONECT_DE" IS '접속일자';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_CONECT_STATS"."REGIST_DT" IS '등록일시';
 
   COMMENT ON TABLE "UCMS22"."TC_SITE_CONECT_STATS"  IS '사이트접속통계';
--------------------------------------------------------
--  DDL for Table TC_SITE_GUIDE_MENU
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_SITE_GUIDE_MENU" 
   (	"MNNO" NUMBER(22,0), 
	"SITE_ID" VARCHAR2(32 BYTE), 
	"MENU_SE_CD" VARCHAR2(16 BYTE), 
	"MENU_NO" NUMBER(10,0), 
	"MENU_NM" VARCHAR2(256 BYTE), 
	"MENU_LINK" VARCHAR2(512 BYTE), 
	"MENU_ORDR" NUMBER(10,0), 
	"POPUP_AT" CHAR(1 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."MNNO" IS '관리번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."MENU_SE_CD" IS '메뉴구분코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."MENU_NM" IS '메뉴명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."MENU_LINK" IS '메뉴링크';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."MENU_ORDR" IS '메뉴순서';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."POPUP_AT" IS '팝업여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_GUIDE_MENU"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_SITE_GUIDE_MENU"  IS '사이트가이드메뉴';
--------------------------------------------------------
--  DDL for Table TC_SITE_HPCM
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_SITE_HPCM" 
   (	"HPCM_NO" NUMBER(11,0), 
	"HPCM_NM" VARCHAR2(256 BYTE), 
	"UPPER_HPCM_NO" NUMBER(11,0), 
	"GROUP_ID" VARCHAR2(256 BYTE), 
	"SRVC_ID" VARCHAR2(256 BYTE), 
	"SRVC_NM" VARCHAR2(256 BYTE), 
	"METHOD_ID" VARCHAR2(256 BYTE), 
	"HPCM_ORDR" NUMBER(11,0), 
	"HPCM_CN" CLOB, 
	"KWRD_NM" VARCHAR2(1024 BYTE), 
	"ADI_INFO" CLOB, 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" 
 LOB ("HPCM_CN") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ADI_INFO") STORE AS BASICFILE (
  TABLESPACE "TSDT_UCMS22" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."HPCM_NO" IS '도움말번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."HPCM_NM" IS '도움말명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."UPPER_HPCM_NO" IS '상위도움말번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."GROUP_ID" IS '그룹ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."SRVC_ID" IS '서비스ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."SRVC_NM" IS '서비스명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."METHOD_ID" IS '메소드ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."HPCM_ORDR" IS '도움말순서';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."HPCM_CN" IS '도움말내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."KWRD_NM" IS '키워드명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."ADI_INFO" IS '추가정보';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_SITE_HPCM"  IS '사이트도움말';
--------------------------------------------------------
--  DDL for Table TC_SITE_HPCM_MENU
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_SITE_HPCM_MENU" 
   (	"HPCM_NO" NUMBER(11,0), 
	"MENU_NO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM_MENU"."HPCM_NO" IS '도움말번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_HPCM_MENU"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON TABLE "UCMS22"."TC_SITE_HPCM_MENU"  IS '사이트도움말메뉴';
--------------------------------------------------------
--  DDL for Table TC_SITE_INFO
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_SITE_INFO" 
   (	"SITE_ID" VARCHAR2(32 BYTE), 
	"SITE_NM" VARCHAR2(256 BYTE), 
	"SITE_DC" VARCHAR2(4000 BYTE), 
	"SITE_URLAD" VARCHAR2(512 BYTE), 
	"SITE_IPAD" VARCHAR2(64 BYTE), 
	"SITE_PORT_NO" VARCHAR2(32 BYTE), 
	"SITE_ESTBS_CD" VARCHAR2(16 BYTE), 
	"STSFDG_USE_AT" CHAR(1 BYTE) DEFAULT 'N', 
	"DTA_MNGR_USE_AT" CHAR(1 BYTE) DEFAULT 'N', 
	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"ACCES_IPAD" VARCHAR2(2048 BYTE), 
	"SITE_SN" NUMBER(10,0), 
	"INSTT_NM" VARCHAR2(256 BYTE), 
	"INSTT_NM_USE_AT" CHAR(1 BYTE), 
	"CPYRHT_CN" VARCHAR2(4000 BYTE), 
	"CPYRHT_CN_USE_AT" CHAR(1 BYTE), 
	"ZIP" VARCHAR2(7 BYTE), 
	"ZIP_USE_AT" CHAR(1 BYTE), 
	"ADRES1" VARCHAR2(256 BYTE), 
	"ADRES1_USE_AT" CHAR(1 BYTE), 
	"ADRES2" VARCHAR2(512 BYTE), 
	"ADRES2_USE_AT" CHAR(1 BYTE), 
	"TELNO" VARCHAR2(32 BYTE), 
	"TELNO_USE_AT" CHAR(1 BYTE), 
	"FAXNO" VARCHAR2(32 BYTE), 
	"FAXNO_USE_AT" CHAR(1 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."SITE_NM" IS '사이트명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."SITE_DC" IS '사이트설명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."SITE_URLAD" IS '사이트URL주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."SITE_IPAD" IS '사이트IP주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."SITE_PORT_NO" IS '사이트포트번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."SITE_ESTBS_CD" IS '사이트설정코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."STSFDG_USE_AT" IS '만족도사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."DTA_MNGR_USE_AT" IS '자료관리자사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."ACCES_IPAD" IS '접근아이피주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."SITE_SN" IS '사이트일련번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."INSTT_NM" IS '기관명';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."INSTT_NM_USE_AT" IS '기관명사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."CPYRHT_CN" IS '저작권내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."CPYRHT_CN_USE_AT" IS '저작권내용사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."ZIP" IS '우편번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."ZIP_USE_AT" IS '우편번호사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."ADRES1" IS '주소1';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."ADRES1_USE_AT" IS '주소1사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."ADRES2" IS '주소2';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."ADRES2_USE_AT" IS '주소2사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."TELNO" IS '전화번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."TELNO_USE_AT" IS '전화번호사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."FAXNO" IS '팩스번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."FAXNO_USE_AT" IS '팩스번호사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_SITE_INFO"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_SITE_INFO"  IS '사이트정보';
--------------------------------------------------------
--  DDL for Table TC_STSFDG
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_STSFDG" 
   (	"STSFDG_NO" NUMBER(10,0), 
	"SITE_ID" VARCHAR2(32 BYTE), 
	"MENU_NO" NUMBER(10,0), 
	"STSFDG_IDEX" NUMBER(10,0), 
	"OPINION_CN" VARCHAR2(4000 BYTE), 
	"USER_ID" VARCHAR2(64 BYTE), 
	"USER_IPAD" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_STSFDG"."STSFDG_NO" IS '만족도번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_STSFDG"."SITE_ID" IS '사이트ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_STSFDG"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_STSFDG"."STSFDG_IDEX" IS '만족도지수';
 
   COMMENT ON COLUMN "UCMS22"."TC_STSFDG"."OPINION_CN" IS '의견내용';
 
   COMMENT ON COLUMN "UCMS22"."TC_STSFDG"."USER_ID" IS '사용자ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_STSFDG"."USER_IPAD" IS '사용자IP주소';
 
   COMMENT ON COLUMN "UCMS22"."TC_STSFDG"."REGIST_DT" IS '등록일시';
 
   COMMENT ON TABLE "UCMS22"."TC_STSFDG"  IS '만족도';
--------------------------------------------------------
--  DDL for Table TC_TMPLAT_INFO
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_TMPLAT_INFO" 
   (	"TMPLAT_ID" CHAR(20 BYTE), 
	"TMPLAT_NM" VARCHAR2(256 BYTE), 
	"TMPLAT_SE_CD" CHAR(16 BYTE), 
	"TMPLAT_COURS" VARCHAR2(512 BYTE), 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y', 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"REGIST_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."TMPLAT_ID" IS '템플릿ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."TMPLAT_NM" IS '템플릿명';
 
   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."TMPLAT_SE_CD" IS '템플릿구분코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."TMPLAT_COURS" IS '템플릿경로';
 
   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_TMPLAT_INFO"."UPDT_DT" IS '수정일시';
 
   COMMENT ON TABLE "UCMS22"."TC_TMPLAT_INFO"  IS '템플릿정보';
--------------------------------------------------------
--  DDL for Table TC_USER_AUTHOR
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_USER_AUTHOR" 
   (	"USER_ID" VARCHAR2(64 BYTE), 
	"USER_TY_CD" VARCHAR2(16 BYTE), 
	"AUTHOR_CD" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_USER_AUTHOR"."USER_ID" IS '사용자ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_AUTHOR"."USER_TY_CD" IS '사용자구분코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_AUTHOR"."AUTHOR_CD" IS '권한코드';
 
   COMMENT ON TABLE "UCMS22"."TC_USER_AUTHOR"  IS '사용자별권한';
--------------------------------------------------------
--  DDL for Table TC_USER_MAIN_CNTNTS
--------------------------------------------------------

  CREATE TABLE "UCMS22"."TC_USER_MAIN_CNTNTS" 
   (	"RELM_SE_CD" VARCHAR2(2 BYTE), 
	"MAIN_CNTNTS_CD" VARCHAR2(16 BYTE), 
	"BBS_ID" VARCHAR2(16 BYTE), 
	"MENU_LINK" VARCHAR2(512 BYTE), 
	"ATCH_FILE_ID" CHAR(20 BYTE), 
	"REGIST_DT" DATE, 
	"REGIST_ID" VARCHAR2(64 BYTE), 
	"UPDT_DT" DATE, 
	"UPDT_ID" VARCHAR2(64 BYTE), 
	"POPUP_AT" CHAR(1 BYTE), 
	"MENU_NO" NUMBER, 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSDT_UCMS22" ;
 

   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."RELM_SE_CD" IS '영역구분코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."MAIN_CNTNTS_CD" IS '메인콘텐츠코드';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."MENU_LINK" IS '메뉴링크';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."REGIST_DT" IS '등록일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."REGIST_ID" IS '등록ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."UPDT_DT" IS '수정일시';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."UPDT_ID" IS '수정ID';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."POPUP_AT" IS '팝업여부';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "UCMS22"."TC_USER_MAIN_CNTNTS"."USE_AT" IS '사용여부';
 
   COMMENT ON TABLE "UCMS22"."TC_USER_MAIN_CNTNTS"  IS '사용자메인콘텐츠관리';
