
/* Drop Tables */

DROP TABLE TM_USER_INFO CASCADE CONSTRAINTS;
DROP TABLE TB_BBS_ESTN CASCADE CONSTRAINTS;
DROP TABLE TC_POPUP_MANAGE CASCADE CONSTRAINTS;
DROP TABLE TC_CMMN_FILE_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TC_NTCN_RELM CASCADE CONSTRAINTS;
DROP TABLE TC_BANNER CASCADE CONSTRAINTS;
DROP TABLE TC_STSFDG CASCADE CONSTRAINTS;
DROP TABLE TC_MENU_AUTHOR CASCADE CONSTRAINTS;
DROP TABLE TC_CNTNTS_MANAGE CASCADE CONSTRAINTS;
DROP TABLE TC_MENU_INFO CASCADE CONSTRAINTS;
DROP TABLE TC_SITE_INFO CASCADE CONSTRAINTS;
DROP TABLE TB_BBS_BASS CASCADE CONSTRAINTS;
DROP TABLE TC_CMMN_FILE CASCADE CONSTRAINTS;
DROP TABLE TC_CMMN_SN CASCADE CONSTRAINTS;
DROP TABLE TM_MNGR_INFO CASCADE CONSTRAINTS;
DROP TABLE TC_USER_AUTHOR CASCADE CONSTRAINTS;
DROP TABLE TC_AUTHOR_INFO CASCADE CONSTRAINTS;
DROP TABLE TC_WORD_DICARY CASCADE CONSTRAINTS;
DROP TABLE TC_PRHIBT_WRD_FLTER CASCADE CONSTRAINTS;
DROP TABLE TC_CMMN_CD_MULTI CASCADE CONSTRAINTS;
DROP TABLE TC_CMMN_CD_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TC_CMMN_CD_CTGRY CASCADE CONSTRAINTS;
DROP TABLE TC_GLOBAL CASCADE CONSTRAINTS;
DROP TABLE TC_AUTHOR_SCLSRT CASCADE CONSTRAINTS;
DROP TABLE TC_MNGR_MAIN_ESTBS_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TC_MNGR_MAIN_ESTBS CASCADE CONSTRAINTS;
DROP TABLE TC_CMMN_CD_CL CASCADE CONSTRAINTS;
DROP TABLE TB_BBS_MASTR CASCADE CONSTRAINTS;
DROP TABLE TC_TMPLAT_INFO CASCADE CONSTRAINTS;
DROP TABLE TC_QUSTNR_USER_ANSWER CASCADE CONSTRAINTS;
DROP TABLE TC_QUSTNR_ANSWER CASCADE CONSTRAINTS;
DROP TABLE TC_QUSTNR_QESITM CASCADE CONSTRAINTS;
DROP TABLE TC_QUSTNR CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE Q_TB_FIELD_INFO_01;




/* Create Sequences */

CREATE SEQUENCE Q_TB_FIELD_INFO_01 INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE TC_CMMN_FILE
(
	ATCH_FILE_ID char(20) NOT NULL,
	-- Y:사용,N:미사용
	USE_AT char(1) NOT NULL,
	REGIST_DT date NOT NULL,
	CONSTRAINT PK_TC_CMMN_FILE PRIMARY KEY (ATCH_FILE_ID)
);


CREATE TABLE TC_CMMN_SN
(
	TABLE_NM varchar2(256) NOT NULL,
	NEXT_SN number(10,0) NOT NULL,
	CONSTRAINT PK_TC_CMMN_SN PRIMARY KEY (TABLE_NM)
);


CREATE TABLE TC_CMMN_FILE_DETAIL
(
	ATCH_FILE_ID char(20) NOT NULL,
	FILE_SN number(10,0) NOT NULL,
	FILE_STRE_COURS varchar2(512) NOT NULL,
	STRE_FILE_NM varchar2(256) NOT NULL,
	ORIGNL_FILE_NM varchar2(256),
	FILE_EXTSN_NM varchar2(128),
	FILE_SIZE number(10,0),
	FILE_CN clob,
	FILE_FIELD_NM varchar2(256),
	CONSTRAINT PK_TC_CMMN_FILE_DETAIL PRIMARY KEY (ATCH_FILE_ID, FILE_SN)
);


CREATE TABLE TC_AUTHOR_INFO
(
	AUTHOR_CD varchar2(32) NOT NULL,
	AUTHOR_NM varchar2(256) NOT NULL,
	AUTHOR_DC varchar2(4000),
	REGIST_DT date NOT NULL,
	CONSTRAINT PK_TC_AUTHOR_INFO PRIMARY KEY (AUTHOR_CD)
);


CREATE TABLE TC_STSFDG
(
	STSFDG_NO number(10,0) NOT NULL,
	-- 사이트ID
	SITE_ID varchar2(32) NOT NULL UNIQUE,
	MENU_NO number(10,0) NOT NULL,
	STSFDG_IDEX number(10,0) NOT NULL,
	OPINION_CN varchar2(4000),
	USER_ID varchar2(64),
	USER_IPAD varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	CONSTRAINT PK_TC_STSFDG PRIMARY KEY (STSFDG_NO)
);


CREATE TABLE TC_SITE_INFO
(
	-- 사이트ID
	SITE_ID varchar2(32) NOT NULL UNIQUE,
	SITE_NM varchar2(256) NOT NULL,
	SITE_DC varchar2(4000),
	SITE_URLAD varchar2(512),
	SITE_IPAD varchar2(64),
	SITE_PORT_NO varchar2(32),
	SITE_ESTBS_CD varchar2(16),
	STSFDG_USE_AT char(1) DEFAULT 'N',
	DTA_MNGR_USE_AT char(1) DEFAULT 'N',
	ATCH_FILE_ID char(20),
	ACCES_IPAD varchar2(2048),
	SITE_SN number(10,0),
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_SITE_INFO PRIMARY KEY (SITE_ID)
);


CREATE TABLE TC_MENU_AUTHOR
(
	MENU_NO number(10,0) NOT NULL,
	AUTHOR_CD varchar2(32) NOT NULL,
	MAPCREAT_ID varchar2(16),
	REGIST_DT date,
	CONSTRAINT PK_TC_MENU_AUTHOR PRIMARY KEY (MENU_NO, AUTHOR_CD)
);


CREATE TABLE TC_WORD_DICARY
(
	MNNO number(10,0) NOT NULL,
	WORD_SE varchar2(64),
	WORD_NM varchar2(256),
	WORD_ENG_NM varchar2(1024),
	WORD_ENG_ABRV_NM varchar2(1024),
	WORD_DFN varchar2(4000),
	THEMA_AREA_SE varchar2(1024),
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_WORD_DICARY PRIMARY KEY (MNNO)
);


CREATE TABLE TC_PRHIBT_WRD_FLTER
(
	WRD_NO number(10,0) NOT NULL,
	WRD_NM varchar2(256) NOT NULL,
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_PRHIBT_WRD_FLTER PRIMARY KEY (WRD_NO)
);


CREATE TABLE TC_CMMN_CD_CTGRY
(
	CD_ID varchar2(16) NOT NULL,
	CL_CD varchar2(16) NOT NULL,
	CD_ID_NM varchar2(256),
	CD_ID_ENG_NM varchar2(256),
	CD_ID_DC varchar2(4000),
	CD_ID_ENG_DC varchar2(4000),
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_CMMN_CD_CTGRY PRIMARY KEY (CD_ID)
);


CREATE TABLE TC_USER_AUTHOR
(
	USER_ID varchar2(64) NOT NULL,
	USER_TY_CD varchar2(16) NOT NULL,
	AUTHOR_CD varchar2(32) NOT NULL,
	CONSTRAINT PK_TC_USER_AUTHOR PRIMARY KEY (USER_ID, USER_TY_CD)
);


CREATE TABLE TC_CNTNTS_MANAGE
(
	MENU_NO number(10,0) NOT NULL,
	CNTNTS_MNNO number(10,0) NOT NULL,
	CNTNTS_CN clob,
	-- 0:보임,1:사용자삭제,2:관리자삭제
	DELETE_CD char(1) DEFAULT '0' NOT NULL,
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y',
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date DEFAULT SYSDATE NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date DEFAULT SYSDATE,
	CONSTRAINT PK_TC_CNTNTS_MANAGE PRIMARY KEY (MENU_NO, CNTNTS_MNNO)
);


CREATE TABLE TC_GLOBAL
(
	ATTRB_NM varchar2(128) NOT NULL,
	ATTRB_VALUE varchar2(1024) NOT NULL,
	ATTRB_DC varchar2(4000),
	CONSTRAINT PK_TC_GLOBAL PRIMARY KEY (ATTRB_NM)
);


CREATE TABLE TC_AUTHOR_SCLSRT
(
	CHLDRN_AUTH_CD varchar2(32) NOT NULL,
	PARNTS_AUTH_CD varchar2(32) NOT NULL,
	PRIMARY KEY (CHLDRN_AUTH_CD, PARNTS_AUTH_CD)
);


CREATE TABLE TC_CMMN_CD_DETAIL
(
	CD varchar2(16) NOT NULL,
	CD_ID varchar2(16) NOT NULL,
	CD_NM varchar2(256),
	CD_ENG_NM varchar2(2565),
	CD_DC varchar2(4000),
	CD_ENG_DC varchar2(4000),
	UPPER_CD varchar2(16) DEFAULT '0',
	DP number(10,0) DEFAULT 1,
	SORT_ORDR number(10,0) DEFAULT 0,
	OPTN1 varchar2(4000),
	OPTN2 varchar2(4000),
	OPTN3 varchar2(4000),
	OPTN4 varchar2(4000),
	OPTN5 varchar2(4000),
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_CMMN_CD_DETAIL PRIMARY KEY (CD, CD_ID)
);


CREATE TABLE TC_MNGR_MAIN_ESTBS
(
	MNNO number(10,0) NOT NULL,
	SE_CD varchar2(16) NOT NULL,
	BASS_MG varchar2(16) NOT NULL,
	ESTBS_CN clob,
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_MNGR_MAIN_ESTBS PRIMARY KEY (MNNO)
);


CREATE TABLE TC_MNGR_MAIN_ESTBS_DETAIL
(
	MNNO number(10,0) NOT NULL,
	SN number(10,0) NOT NULL,
	ESTBS_NM varchar2(512),
	BBS_ID varchar2(16),
	URLAD varchar2(512),
	POPUP_AT char(1),
	ATCH_FILE_ID char(20),
	FILE_FIELD_NM varchar2(256),
	FIELD_ORDR number(10,0) NOT NULL,
	ICON varchar2(64),
	CONSTRAINT PK_TC_MNGR_MAIN_ESTBS_DETAIL PRIMARY KEY (MNNO, SN)
);


CREATE TABLE TC_MENU_INFO
(
	MENU_NO number(10,0) NOT NULL,
	MENU_NM varchar2(256) NOT NULL,
	-- 상위메뉴번호
	UPPER_MENU_NO number(10,0) NOT NULL,
	MENU_ORDR number(10,0) NOT NULL,
	MENU_DC varchar2(4000),
	MENU_LINK varchar2(512),
	POPUP_AT char(1),
	-- 사이트ID
	SITE_ID varchar2(32) NOT NULL,
	DEPT_ID varchar2(16),
	USER_ID varchar2(64),
	RELATE_MENU_NM_LIST varchar2(4000),
	RELATE_MENU_LINK_LIST varchar2(4000),
	ALL_MENU_COURS varchar2(4000),
	CNTNTS_FILE_COURS varchar2(512),
	MENU_LC varchar2(4000),
	BBS_ID varchar2(16),
	LEAF_NODE_AT char(1),
	KWRD_NM varchar2(1024),
	ADI_INFO varchar2(4000),
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_MENU_INFO PRIMARY KEY (MENU_NO)
);

CREATE INDEX I_TC_MENU_INFO_01
ON TC_MENU_INFO (SITE_ID, DELETE_CD, UPPER_MENU_NO, MENU_ORDR)


CREATE TABLE TC_BANNER
(
	BANNER_NO number(10,0) NOT NULL,
	BANNER_NM varchar2(256) NOT NULL,
	BANNER_URLAD varchar2(512),
	BANNER_SE varchar2(16),
	DONG_CD varchar2(16),
	SORT_ORDR number(10,0),
	EXPSR_AT char(1),
	POPUP_AT char(1) DEFAULT 'N',
	DEPT_ID varchar2(16),
	SITE_ID_SE varchar2(512),
	-- 사이트ID
	SITE_ID varchar2(32),
	ATCH_FILE_ID char(20),
	BGNDE date DEFAULT SYSDATE,
	ENDDE date DEFAULT SYSDATE,
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_BANNER PRIMARY KEY (BANNER_NO)
);


CREATE TABLE TC_NTCN_RELM
(
	NTCN_NO number(10,0) NOT NULL,
	NTCN_NM varchar2(256) NOT NULL,
	NTCN_URLAD varchar2(512),
	NTCN_CN clob,
	NTCN_TY_CD varchar2(16),
	SORT_ORDR number(10,0),
	POPUP_AT char(1),
	MAP_USE_AT char(1),
	DEPT_ID varchar2(16),
	SITE_ID_SE varchar2(512),
	-- 사이트ID
	SITE_ID varchar2(32),
	ATCH_FILE_ID char(20),
	BGNDE date DEFAULT SYSDATE,
	ENDDE date DEFAULT SYSDATE,
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_NTCN_RELM PRIMARY KEY (NTCN_NO)
);


CREATE TABLE TC_CMMN_CD_CL
(
	CL_CD varchar2(16) NOT NULL,
	CL_CD_NM varchar2(256),
	CL_CD_DC varchar2(4000),
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_CMMN_CD_CL PRIMARY KEY (CL_CD)
);


CREATE TABLE TC_TMPLAT_INFO
(
	TMPLAT_ID char(20) NOT NULL,
	TMPLAT_NM varchar2(256),
	TMPLAT_SE_CD varchar2(16),
	TMPLAT_COURS varchar2(512),
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_TMPLAT_INFO PRIMARY KEY (TMPLAT_ID)
);


CREATE TABLE TC_POPUP_MANAGE
(
	POPUP_NO number(10,0) NOT NULL,
	POPUP_SJ varchar2(1024) NOT NULL,
	POPUP_CN clob,
	BGNDE date DEFAULT SYSDATE,
	ENDDE date DEFAULT SYSDATE,
	AR_VALUE number(10,0),
	HG_VALUE number(10,0),
	LFT_CRDNT number(10,0),
	UPEND_CRDNT number(10,0),
	CLOSE_USE_AT char(1),
	SITE_ID_SE varchar2(512),
	-- 사이트ID
	SITE_ID varchar2(32),
	ATCH_FILE_ID char(20),
	URLAD varchar2(512),
	SCRL_USE_AT char(1),
	LINK_TY_CD varchar2(16),
	MAP_CN varchar2(4000),
	-- Y:사용,N:미사용
	USE_AT char(1) DEFAULT 'Y' NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	REGIST_DT date NOT NULL,
	UPDT_ID varchar2(64),
	UPDT_DT date,
	CONSTRAINT PK_TC_POPUP_MANAGE PRIMARY KEY (POPUP_NO)
);


CREATE TABLE TC_CMMN_CD_MULTI
(
	CD_ID varchar2(16) NOT NULL,
	PROGRM_ID varchar2(32) NOT NULL,
	PROGRM_SN number(10,0) NOT NULL,
	CD varchar2(16) NOT NULL,
	REGIST_DT date,
	MEMO varchar2(4000),
	CONSTRAINT PK_TC_CMMN_CD_MULTI PRIMARY KEY (CD_ID, PROGRM_ID, PROGRM_SN, CD)
);


CREATE TABLE TC_QUSTNR_ANSWER
(
	-- 답변일련번호
	ANSWER_SN number(10,0) NOT NULL,
	-- 설문항목번호
	QESITM_SN number(10,0) NOT NULL,
	-- 답변내용
	ANSWER_CN varchar2(4000),
	SORT_ORDR number(10,0) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_TC_QUSTNR_ANSWER PRIMARY KEY (ANSWER_SN)
);


CREATE TABLE TC_QUSTNR
(
	QUSTNR_SN number(10,0) NOT NULL,
	-- 설문주제
	QUSTNR_SJ varchar2(1024) NOT NULL,
	BGNDE date NOT NULL,
	ENDDE date NOT NULL,
	STTUS_CD varchar2(16) NOT NULL,
	-- 설문대상코드(학생,일반)
	TRGET_CD varchar2(16),
	RESULT_OTHBC_AT char(1) DEFAULT 'Y' NOT NULL,
	DEPT_ID varchar2(16) NOT NULL,
	-- 전화번호
	TELNO varchar2(32),
	-- 설문조사내용
	QESTNAR_CN clob,
	-- 0:보임,1:사용자삭제,2:관리자삭제
	DELETE_CD char(1) DEFAULT '0' NOT NULL,
	REGIST_DT date DEFAULT SYSDATE NOT NULL,
	REGIST_ID varchar2(64) NOT NULL,
	UPDT_DT date DEFAULT SYSDATE,
	-- 수정ID
	UPDT_ID varchar2(64),
	CONSTRAINT PK_TC_QUSTNR PRIMARY KEY (QUSTNR_SN)
);


CREATE TABLE TC_QUSTNR_QESITM
(
	QESITM_SN number(10,0) NOT NULL,
	-- 설문번호
	QUSTNR_SN number(10,0) NOT NULL,
	-- 문항유형코드
	QESITM_TY_CD varchar2(16) NOT NULL,
	QESITM_SJ varchar2(1024) NOT NULL,
	ESSNTL_ANSWER_AT char(1) DEFAULT 'N' NOT NULL,
	ESSNTL_CHOISE_QY number(10,0) DEFAULT 0,
	CONSTRAINT PK_TC_QUSTNR_QESITM PRIMARY KEY (QESITM_SN)
);


CREATE TABLE TC_QUSTNR_USER_ANSWER
(
	USER_ANSWER_SN number(10,0) NOT NULL,
	QESITM_SN number(10,0) NOT NULL,
	-- 답변일련번호
	ANSWER_SN number(10,0),
	USER_SN number(10,0),
	USER_ID varchar2(64),
	ANSWER_CN varchar2(4000),
	CONSTRAINT PK_TC_QUSTNR_USER_ANSWER PRIMARY KEY (USER_ANSWER_SN)
);



/* Create Foreign Keys */

ALTER TABLE TM_USER_INFO
	ADD FOREIGN KEY (ATCH_FILE_ID)
	REFERENCES TC_CMMN_FILE (ATCH_FILE_ID)
;


ALTER TABLE TB_BBS_ESTN
	ADD CONSTRAINT FK_TB_BBS_ESTN_CMMN_FILE FOREIGN KEY (ATCH_FILE_ID)
	REFERENCES TC_CMMN_FILE (ATCH_FILE_ID)
;


ALTER TABLE TC_POPUP_MANAGE
	ADD CONSTRAINT FK_TC_POPUP_MANAGE_CMMN_FILE FOREIGN KEY (ATCH_FILE_ID)
	REFERENCES TC_CMMN_FILE (ATCH_FILE_ID)
;


ALTER TABLE TC_CMMN_FILE_DETAIL
	ADD CONSTRAINT FK_TC_CMMN_FILE_DETAIL_FILE FOREIGN KEY (ATCH_FILE_ID)
	REFERENCES TC_CMMN_FILE (ATCH_FILE_ID)
	ON DELETE NO ACTION
;


ALTER TABLE TC_NTCN_RELM
	ADD CONSTRAINT FK_TC_NTCN_RELM_CMMN_FILE FOREIGN KEY (ATCH_FILE_ID)
	REFERENCES TC_CMMN_FILE (ATCH_FILE_ID)
;


ALTER TABLE TC_BANNER
	ADD CONSTRAINT FK_TC_BANNER_CMMN_FILE FOREIGN KEY (ATCH_FILE_ID)
	REFERENCES TC_CMMN_FILE (ATCH_FILE_ID)
;


ALTER TABLE TC_SITE_INFO
	ADD FOREIGN KEY (ATCH_FILE_ID)
	REFERENCES TC_CMMN_FILE (ATCH_FILE_ID)
;


ALTER TABLE TB_BBS_BASS
	ADD CONSTRAINT FK_TB_BBS_BASS_CMMN_FILE FOREIGN KEY (ATCH_FILE_ID)
	REFERENCES TC_CMMN_FILE (ATCH_FILE_ID)
;


ALTER TABLE TM_MNGR_INFO
	ADD CONSTRAINT FK_TC_AUTHOR_INFO_MNGR_INFO FOREIGN KEY (AUTHOR_CD)
	REFERENCES TC_AUTHOR_INFO (AUTHOR_CD)
;


ALTER TABLE TC_MENU_AUTHOR
	ADD CONSTRAINT FK_TC_MENU_AUTHOR_INFO FOREIGN KEY (AUTHOR_CD)
	REFERENCES TC_AUTHOR_INFO (AUTHOR_CD)
;


ALTER TABLE TM_USER_INFO
	ADD CONSTRAINT FK_TC_AUTHOR_INFO_USER_INFO FOREIGN KEY (AUTHOR_CD)
	REFERENCES TC_AUTHOR_INFO (AUTHOR_CD)
;


ALTER TABLE TC_USER_AUTHOR
	ADD CONSTRAINT FK_TC_USER_AUTHOR_AUTHOR_INFO FOREIGN KEY (AUTHOR_CD)
	REFERENCES TC_AUTHOR_INFO (AUTHOR_CD)
;


ALTER TABLE TM_USER_INFO
	ADD FOREIGN KEY (SITE_ID)
	REFERENCES TC_SITE_INFO (SITE_ID)
;


ALTER TABLE TB_BBS_ESTN
	ADD CONSTRAINT FK_TB_BBS_ESTN_SITE_INFO FOREIGN KEY (SITE_ID)
	REFERENCES TC_SITE_INFO (SITE_ID)
;


ALTER TABLE TC_STSFDG
	ADD FOREIGN KEY (SITE_ID)
	REFERENCES TC_SITE_INFO (SITE_ID)
;


ALTER TABLE TC_MENU_INFO
	ADD CONSTRAINT FK_TC_MENU_INFO_SITE_INFO FOREIGN KEY (SITE_ID)
	REFERENCES TC_SITE_INFO (SITE_ID)
;


ALTER TABLE TC_CMMN_CD_DETAIL
	ADD CONSTRAINT FK_TC_CMMN_CD_DETAIL_CMMN_CD_CTGRY FOREIGN KEY (CD_ID)
	REFERENCES TC_CMMN_CD_CTGRY (CD_ID)
	ON DELETE NO ACTION
;


ALTER TABLE TC_CMMN_CD_MULTI
	ADD CONSTRAINT FK_TC_CMMN_CD_MULTI_CMMN_CD_DETAIL FOREIGN KEY (CD_ID, CD)
	REFERENCES TC_CMMN_CD_DETAIL (CD_ID, CD)
;


ALTER TABLE TC_MNGR_MAIN_ESTBS_DETAIL
	ADD CONSTRAINT FK_TC_MNGR_MAIN_ESTBS_DETAIL FOREIGN KEY (MNNO)
	REFERENCES TC_MNGR_MAIN_ESTBS (MNNO)
;


ALTER TABLE TC_MENU_AUTHOR
	ADD CONSTRAINT FK_TC_MENU_AUTHOR_MENU_INFO FOREIGN KEY (MENU_NO)
	REFERENCES TC_MENU_INFO (MENU_NO)
;


ALTER TABLE TC_CNTNTS_MANAGE
	ADD CONSTRAINT FK_TC_CNTNTS_MANAGE_MENU_INFO FOREIGN KEY (MENU_NO)
	REFERENCES TC_MENU_INFO (MENU_NO)
;


ALTER TABLE TC_CMMN_CD_CTGRY
	ADD CONSTRAINT FK_TC_CMMN_CD_CTGRY_CMMN_CD_CL FOREIGN KEY (CL_CD)
	REFERENCES TC_CMMN_CD_CL (CL_CD)
;


ALTER TABLE TB_BBS_MASTR
	ADD CONSTRAINT FK_TB_BBS_MASTR_TMPLAT_INFO FOREIGN KEY (TMPLAT_ID)
	REFERENCES TC_TMPLAT_INFO (TMPLAT_ID)
;


ALTER TABLE TC_QUSTNR_USER_ANSWER
	ADD CONSTRAINT FK_QUSTNR_USER_ANSWER_ANSWER FOREIGN KEY (ANSWER_SN)
	REFERENCES TC_QUSTNR_ANSWER (ANSWER_SN)
;


ALTER TABLE TC_QUSTNR_QESITM
	ADD CONSTRAINT FK_QESITM_QUSTNR FOREIGN KEY (QUSTNR_SN)
	REFERENCES TC_QUSTNR (QUSTNR_SN)
;


ALTER TABLE TC_QUSTNR_ANSWER
	ADD CONSTRAINT FK_QUSTNR_ANSWER_QESITM FOREIGN KEY (QESITM_SN)
	REFERENCES TC_QUSTNR_QESITM (QESITM_SN)
;


ALTER TABLE TC_QUSTNR_USER_ANSWER
	ADD CONSTRAINT FK_QUSTNR_USER_ANSWER_QESITM FOREIGN KEY (QESITM_SN)
	REFERENCES TC_QUSTNR_QESITM (QESITM_SN)
;



/* Comments */

COMMENT ON TABLE TC_CMMN_FILE IS '공통파일';
COMMENT ON COLUMN TC_CMMN_FILE.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN TC_CMMN_FILE.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_CMMN_FILE.REGIST_DT IS '등록일시';
COMMENT ON TABLE TC_CMMN_SN IS '공통일련번호';
COMMENT ON COLUMN TC_CMMN_SN.TABLE_NM IS '테이블명';
COMMENT ON COLUMN TC_CMMN_SN.NEXT_SN IS '다음일련번호';
COMMENT ON TABLE TC_CMMN_FILE_DETAIL IS '공통파일상세';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_SN IS '파일일련번호';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_STRE_COURS IS '파일저장경로';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.STRE_FILE_NM IS '저장파일명';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.ORIGNL_FILE_NM IS '원본파일명';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_EXTSN_NM IS '파일확장자명';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_SIZE IS '파일사이즈';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_CN IS '파일내용';
COMMENT ON COLUMN TC_CMMN_FILE_DETAIL.FILE_FIELD_NM IS '파일필드명';
COMMENT ON TABLE TC_AUTHOR_INFO IS '권한정보';
COMMENT ON COLUMN TC_AUTHOR_INFO.AUTHOR_CD IS '권한코드';
COMMENT ON COLUMN TC_AUTHOR_INFO.AUTHOR_NM IS '권한명';
COMMENT ON COLUMN TC_AUTHOR_INFO.AUTHOR_DC IS '권한설명';
COMMENT ON COLUMN TC_AUTHOR_INFO.REGIST_DT IS '등록일시';
COMMENT ON TABLE TC_STSFDG IS '만족도';
COMMENT ON COLUMN TC_STSFDG.STSFDG_NO IS '만족도번호';
COMMENT ON COLUMN TC_STSFDG.SITE_ID IS '사이트ID';
COMMENT ON COLUMN TC_STSFDG.MENU_NO IS '메뉴번호';
COMMENT ON COLUMN TC_STSFDG.STSFDG_IDEX IS '만족도지수';
COMMENT ON COLUMN TC_STSFDG.OPINION_CN IS '의견내용';
COMMENT ON COLUMN TC_STSFDG.USER_ID IS '사용자ID';
COMMENT ON COLUMN TC_STSFDG.USER_IPAD IS '사용자IP주소';
COMMENT ON COLUMN TC_STSFDG.REGIST_DT IS '등록일시';
COMMENT ON TABLE TC_SITE_INFO IS '사이트정보';
COMMENT ON COLUMN TC_SITE_INFO.SITE_ID IS '사이트ID';
COMMENT ON COLUMN TC_SITE_INFO.SITE_NM IS '사이트명';
COMMENT ON COLUMN TC_SITE_INFO.SITE_DC IS '사이트설명';
COMMENT ON COLUMN TC_SITE_INFO.SITE_URLAD IS '사이트URL주소';
COMMENT ON COLUMN TC_SITE_INFO.SITE_IPAD IS '사이트IP주소';
COMMENT ON COLUMN TC_SITE_INFO.SITE_PORT_NO IS '사이트포트번호';
COMMENT ON COLUMN TC_SITE_INFO.SITE_ESTBS_CD IS '사이트설정코드';
COMMENT ON COLUMN TC_SITE_INFO.STSFDG_USE_AT IS '만족도사용여부';
COMMENT ON COLUMN TC_SITE_INFO.DTA_MNGR_USE_AT IS '자료관리자사용여부';
COMMENT ON COLUMN TC_SITE_INFO.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN TC_SITE_INFO.ACCES_IPAD IS '접근아이피주소';
COMMENT ON COLUMN TC_SITE_INFO.SITE_SN IS '사이트일련번호';
COMMENT ON COLUMN TC_SITE_INFO.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_SITE_INFO.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_SITE_INFO.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_SITE_INFO.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_SITE_INFO.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_MENU_AUTHOR IS '메뉴권한';
COMMENT ON COLUMN TC_MENU_AUTHOR.MENU_NO IS '메뉴번호';
COMMENT ON COLUMN TC_MENU_AUTHOR.AUTHOR_CD IS '권한코드';
COMMENT ON COLUMN TC_MENU_AUTHOR.MAPCREAT_ID IS '맵생성ID';
COMMENT ON COLUMN TC_MENU_AUTHOR.REGIST_DT IS '등록일시';
COMMENT ON TABLE TC_WORD_DICARY IS '용어사전';
COMMENT ON COLUMN TC_WORD_DICARY.MNNO IS '관리번호';
COMMENT ON COLUMN TC_WORD_DICARY.WORD_SE IS '용어구분';
COMMENT ON COLUMN TC_WORD_DICARY.WORD_NM IS '용어명';
COMMENT ON COLUMN TC_WORD_DICARY.WORD_ENG_NM IS '용어영문명';
COMMENT ON COLUMN TC_WORD_DICARY.WORD_ENG_ABRV_NM IS '용어영문약어명';
COMMENT ON COLUMN TC_WORD_DICARY.WORD_DFN IS '용어정의';
COMMENT ON COLUMN TC_WORD_DICARY.THEMA_AREA_SE IS '주제영역구분';
COMMENT ON COLUMN TC_WORD_DICARY.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_WORD_DICARY.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_WORD_DICARY.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_WORD_DICARY.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_WORD_DICARY.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_PRHIBT_WRD_FLTER IS '금지용어필터';
COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.WRD_NO IS '용어번호';
COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.WRD_NM IS '용어명';
COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_PRHIBT_WRD_FLTER.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_CMMN_CD_CTGRY IS '공통코드카테고리';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID IS '코드ID';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CL_CD IS '분류코드';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID_NM IS '코드ID명';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID_ENG_NM IS '코드ID영문명';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID_DC IS '코드ID설명';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.CD_ID_ENG_DC IS '코드ID영문설명';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_CMMN_CD_CTGRY.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_USER_AUTHOR IS '사용자별권한';
COMMENT ON COLUMN TC_USER_AUTHOR.USER_ID IS '사용자ID';
COMMENT ON COLUMN TC_USER_AUTHOR.USER_TY_CD IS '사용자구분코드';
COMMENT ON COLUMN TC_USER_AUTHOR.AUTHOR_CD IS '권한코드';
COMMENT ON TABLE TC_CNTNTS_MANAGE IS '콘텐츠관리';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.MENU_NO IS '메뉴번호';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.CNTNTS_MNNO IS '컨텐츠관리번호';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.CNTNTS_CN IS '콘텐츠내용';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.DELETE_CD IS '삭제코드';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_CNTNTS_MANAGE.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_GLOBAL IS '글로벌';
COMMENT ON COLUMN TC_GLOBAL.ATTRB_NM IS '속성명';
COMMENT ON COLUMN TC_GLOBAL.ATTRB_VALUE IS '속성값';
COMMENT ON COLUMN TC_GLOBAL.ATTRB_DC IS 'ATTRB_DC';
COMMENT ON TABLE TC_AUTHOR_SCLSRT IS '권한계층';
COMMENT ON COLUMN TC_AUTHOR_SCLSRT.CHLDRN_AUTH_CD IS '자식권한코드';
COMMENT ON COLUMN TC_AUTHOR_SCLSRT.PARNTS_AUTH_CD IS '부모권한코드';
COMMENT ON TABLE TC_CMMN_CD_DETAIL IS '공통코드상세';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD IS '코드';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_ID IS '코드ID';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_NM IS '코드명';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_ENG_NM IS '코드영문명';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_DC IS '코드설명';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.CD_ENG_DC IS '코드영문설명';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.UPPER_CD IS '상위코드';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.DP IS '깊이';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.SORT_ORDR IS '정렬순서';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN1 IS '옵션1';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN2 IS '옵션2';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN3 IS '옵션3';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN4 IS '옵션4';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.OPTN5 IS '옵션5';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_CMMN_CD_DETAIL.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_MNGR_MAIN_ESTBS IS '관리자메인설정';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.MNNO IS '관리번호';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.SE_CD IS '설정구분코드';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.BASS_MG IS '기본크기';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.ESTBS_CN IS '설정내용';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_MNGR_MAIN_ESTBS_DETAIL IS '관리자메인설정상세';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.MNNO IS '관리번호';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.SN IS '일련번호';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.ESTBS_NM IS '설정명';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.BBS_ID IS '게시판ID';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.URLAD IS 'URL주소';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.POPUP_AT IS '팝업여부';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.FILE_FIELD_NM IS '파일필드명';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.FIELD_ORDR IS '필드순서';
COMMENT ON COLUMN TC_MNGR_MAIN_ESTBS_DETAIL.ICON IS '아이콘';
COMMENT ON TABLE TC_MENU_INFO IS '메뉴정보';
COMMENT ON COLUMN TC_MENU_INFO.MENU_NO IS '메뉴번호';
COMMENT ON COLUMN TC_MENU_INFO.MENU_NM IS '메뉴명';
COMMENT ON COLUMN TC_MENU_INFO.UPPER_MENU_NO IS '상위메뉴번호';
COMMENT ON COLUMN TC_MENU_INFO.MENU_ORDR IS '메뉴순서';
COMMENT ON COLUMN TC_MENU_INFO.MENU_DC IS '메뉴설명';
COMMENT ON COLUMN TC_MENU_INFO.MENU_LINK IS '메뉴링크';
COMMENT ON COLUMN TC_MENU_INFO.POPUP_AT IS '팝업여부';
COMMENT ON COLUMN TC_MENU_INFO.SITE_ID IS '사이트ID';
COMMENT ON COLUMN TC_MENU_INFO.DEPT_ID IS '부서ID';
COMMENT ON COLUMN TC_MENU_INFO.USER_ID IS '사용자ID';
COMMENT ON COLUMN TC_MENU_INFO.RELATE_MENU_NM_LIST IS '관련메뉴명목록';
COMMENT ON COLUMN TC_MENU_INFO.RELATE_MENU_LINK_LIST IS '관련메뉴링크목록';
COMMENT ON COLUMN TC_MENU_INFO.ALL_MENU_COURS IS '전체메뉴경로';
COMMENT ON COLUMN TC_MENU_INFO.CNTNTS_FILE_COURS IS '콘텐츠파일경로';
COMMENT ON COLUMN TC_MENU_INFO.MENU_LC IS '메뉴위치';
COMMENT ON COLUMN TC_MENU_INFO.BBS_ID IS '게시판ID';
COMMENT ON COLUMN TC_MENU_INFO.LEAF_NODE_AT IS '최종하위메뉴유무';
COMMENT ON COLUMN TC_MENU_INFO.KWRD_NM IS '메타태그키워드명';
COMMENT ON COLUMN TC_MENU_INFO.ADI_INFO IS '부가정보';
COMMENT ON COLUMN TC_MENU_INFO.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_MENU_INFO.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_MENU_INFO.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_MENU_INFO.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_MENU_INFO.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_BANNER IS '배너';
COMMENT ON COLUMN TC_BANNER.BANNER_NO IS '배너번호';
COMMENT ON COLUMN TC_BANNER.BANNER_NM IS '배너명';
COMMENT ON COLUMN TC_BANNER.BANNER_URLAD IS '배너URL주소';
COMMENT ON COLUMN TC_BANNER.BANNER_SE IS '배너구분';
COMMENT ON COLUMN TC_BANNER.DONG_CD IS '동코드';
COMMENT ON COLUMN TC_BANNER.SORT_ORDR IS '정렬순서';
COMMENT ON COLUMN TC_BANNER.EXPSR_AT IS '노출여부';
COMMENT ON COLUMN TC_BANNER.POPUP_AT IS '팝업여부';
COMMENT ON COLUMN TC_BANNER.DEPT_ID IS '부서ID';
COMMENT ON COLUMN TC_BANNER.SITE_ID_SE IS '사이트ID구분';
COMMENT ON COLUMN TC_BANNER.SITE_ID IS '사이트ID';
COMMENT ON COLUMN TC_BANNER.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN TC_BANNER.BGNDE IS '시작일';
COMMENT ON COLUMN TC_BANNER.ENDDE IS '종료일';
COMMENT ON COLUMN TC_BANNER.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_BANNER.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_BANNER.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_BANNER.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_BANNER.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_NTCN_RELM IS '알림영역';
COMMENT ON COLUMN TC_NTCN_RELM.NTCN_NO IS '알림번호';
COMMENT ON COLUMN TC_NTCN_RELM.NTCN_NM IS '알림명';
COMMENT ON COLUMN TC_NTCN_RELM.NTCN_URLAD IS '알림URL주소';
COMMENT ON COLUMN TC_NTCN_RELM.NTCN_CN IS '알림내용';
COMMENT ON COLUMN TC_NTCN_RELM.NTCN_TY_CD IS '알림유형코드';
COMMENT ON COLUMN TC_NTCN_RELM.SORT_ORDR IS '정렬순서';
COMMENT ON COLUMN TC_NTCN_RELM.POPUP_AT IS '팝업여부';
COMMENT ON COLUMN TC_NTCN_RELM.MAP_USE_AT IS '맵사용여부';
COMMENT ON COLUMN TC_NTCN_RELM.DEPT_ID IS '부서ID';
COMMENT ON COLUMN TC_NTCN_RELM.SITE_ID_SE IS '사이트ID구분';
COMMENT ON COLUMN TC_NTCN_RELM.SITE_ID IS '사이트ID';
COMMENT ON COLUMN TC_NTCN_RELM.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN TC_NTCN_RELM.BGNDE IS '시작일';
COMMENT ON COLUMN TC_NTCN_RELM.ENDDE IS '종료일';
COMMENT ON COLUMN TC_NTCN_RELM.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_NTCN_RELM.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_NTCN_RELM.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_NTCN_RELM.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_NTCN_RELM.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_CMMN_CD_CL IS '공통코드분류';
COMMENT ON COLUMN TC_CMMN_CD_CL.CL_CD IS '분류코드';
COMMENT ON COLUMN TC_CMMN_CD_CL.CL_CD_NM IS '분류코드명';
COMMENT ON COLUMN TC_CMMN_CD_CL.CL_CD_DC IS '분류코드 설명';
COMMENT ON COLUMN TC_CMMN_CD_CL.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_CMMN_CD_CL.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_CMMN_CD_CL.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_CMMN_CD_CL.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_CMMN_CD_CL.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_TMPLAT_INFO IS '템플릿정보';
COMMENT ON COLUMN TC_TMPLAT_INFO.TMPLAT_ID IS '템플릿ID';
COMMENT ON COLUMN TC_TMPLAT_INFO.TMPLAT_NM IS '템플릿명';
COMMENT ON COLUMN TC_TMPLAT_INFO.TMPLAT_SE_CD IS '템플릿구분코드';
COMMENT ON COLUMN TC_TMPLAT_INFO.TMPLAT_COURS IS '템플릿경로';
COMMENT ON COLUMN TC_TMPLAT_INFO.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_TMPLAT_INFO.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_TMPLAT_INFO.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_TMPLAT_INFO.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_TMPLAT_INFO.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_POPUP_MANAGE IS '팝업관리';
COMMENT ON COLUMN TC_POPUP_MANAGE.POPUP_NO IS '팝업번호';
COMMENT ON COLUMN TC_POPUP_MANAGE.POPUP_SJ IS '팝업제목';
COMMENT ON COLUMN TC_POPUP_MANAGE.POPUP_CN IS '팝업내용';
COMMENT ON COLUMN TC_POPUP_MANAGE.BGNDE IS '시작일';
COMMENT ON COLUMN TC_POPUP_MANAGE.ENDDE IS '종료일';
COMMENT ON COLUMN TC_POPUP_MANAGE.AR_VALUE IS '넓이값';
COMMENT ON COLUMN TC_POPUP_MANAGE.HG_VALUE IS '높이값';
COMMENT ON COLUMN TC_POPUP_MANAGE.LFT_CRDNT IS '좌측좌표';
COMMENT ON COLUMN TC_POPUP_MANAGE.UPEND_CRDNT IS '탑좌표';
COMMENT ON COLUMN TC_POPUP_MANAGE.CLOSE_USE_AT IS '닫기사용여부';
COMMENT ON COLUMN TC_POPUP_MANAGE.SITE_ID_SE IS '사이트ID구분';
COMMENT ON COLUMN TC_POPUP_MANAGE.SITE_ID IS '사이트ID';
COMMENT ON COLUMN TC_POPUP_MANAGE.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN TC_POPUP_MANAGE.URLAD IS '링크주소';
COMMENT ON COLUMN TC_POPUP_MANAGE.SCRL_USE_AT IS '스크롤사용여부';
COMMENT ON COLUMN TC_POPUP_MANAGE.LINK_TY_CD IS '링크타입코드';
COMMENT ON COLUMN TC_POPUP_MANAGE.MAP_CN IS '맵내용';
COMMENT ON COLUMN TC_POPUP_MANAGE.USE_AT IS '사용여부';
COMMENT ON COLUMN TC_POPUP_MANAGE.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_POPUP_MANAGE.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_POPUP_MANAGE.UPDT_ID IS '수정ID';
COMMENT ON COLUMN TC_POPUP_MANAGE.UPDT_DT IS '수정일시';
COMMENT ON TABLE TC_CMMN_CD_MULTI IS '공통코드다중';
COMMENT ON COLUMN TC_CMMN_CD_MULTI.CD_ID IS '코드ID';
COMMENT ON COLUMN TC_CMMN_CD_MULTI.PROGRM_ID IS '프로그램ID';
COMMENT ON COLUMN TC_CMMN_CD_MULTI.PROGRM_SN IS '프로그램일련번호';
COMMENT ON COLUMN TC_CMMN_CD_MULTI.CD IS '코드';
COMMENT ON COLUMN TC_CMMN_CD_MULTI.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_CMMN_CD_MULTI.MEMO IS '메모';
COMMENT ON TABLE TC_QUSTNR_ANSWER IS '설문답변';
COMMENT ON COLUMN TC_QUSTNR_ANSWER.ANSWER_SN IS '답변일련번호';
COMMENT ON COLUMN TC_QUSTNR_ANSWER.QESITM_SN IS '문항일련번호';
COMMENT ON COLUMN TC_QUSTNR_ANSWER.ANSWER_CN IS '답변내용';
COMMENT ON COLUMN TC_QUSTNR_ANSWER.SORT_ORDR IS '정렬순서';
COMMENT ON TABLE TC_QUSTNR IS '설문조사';
COMMENT ON COLUMN TC_QUSTNR.QUSTNR_SN IS '설문일련번호';
COMMENT ON COLUMN TC_QUSTNR.QUSTNR_SJ IS '설문주제';
COMMENT ON COLUMN TC_QUSTNR.BGNDE IS '시작일';
COMMENT ON COLUMN TC_QUSTNR.ENDDE IS '종료일';
COMMENT ON COLUMN TC_QUSTNR.STTUS_CD IS '상태코드';
COMMENT ON COLUMN TC_QUSTNR.TRGET_CD IS '대상코드';
COMMENT ON COLUMN TC_QUSTNR.RESULT_OTHBC_AT IS '결과보기공개여부';
COMMENT ON COLUMN TC_QUSTNR.DEPT_ID IS '부서ID';
COMMENT ON COLUMN TC_QUSTNR.TELNO IS '전화번호';
COMMENT ON COLUMN TC_QUSTNR.QESTNAR_CN IS '설문조사내용';
COMMENT ON COLUMN TC_QUSTNR.DELETE_CD IS '삭제코드';
COMMENT ON COLUMN TC_QUSTNR.REGIST_DT IS '등록일시';
COMMENT ON COLUMN TC_QUSTNR.REGIST_ID IS '등록ID';
COMMENT ON COLUMN TC_QUSTNR.UPDT_DT IS '수정일시';
COMMENT ON COLUMN TC_QUSTNR.UPDT_ID IS '수정ID';
COMMENT ON TABLE TC_QUSTNR_QESITM IS '설문항목';
COMMENT ON COLUMN TC_QUSTNR_QESITM.QESITM_SN IS '문항일련번호';
COMMENT ON COLUMN TC_QUSTNR_QESITM.QUSTNR_SN IS '설문일련번호';
COMMENT ON COLUMN TC_QUSTNR_QESITM.QESITM_TY_CD IS '문항유형코드';
COMMENT ON COLUMN TC_QUSTNR_QESITM.QESITM_SJ IS '문항제목';
COMMENT ON COLUMN TC_QUSTNR_QESITM.ESSNTL_ANSWER_AT IS '필수답변여부';
COMMENT ON COLUMN TC_QUSTNR_QESITM.ESSNTL_CHOISE_QY IS '필수선택건수';
COMMENT ON TABLE TC_QUSTNR_USER_ANSWER IS '설문사용자답변';
COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.USER_ANSWER_SN IS '사용자답변일련번호';
COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.QESITM_SN IS '문항일련번호';
COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.ANSWER_SN IS '답변일련번호';
COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.USER_SN IS '사용자일련번호';
COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.USER_ID IS '사용자ID';
COMMENT ON COLUMN TC_QUSTNR_USER_ANSWER.ANSWER_CN IS '답변내용';



